In [38]:
import pandas as pd

In [39]:
#load FSC master exce5
df1 = pd.read_excel("C:\\Users\\taslim.siddiqui\\Downloads\\ABHFL+ABM FSC Mapping_04_Apr_2025 1 (1).xlsx",sheet_name="ABHFL+ABM FSC Master")
df1

,PRODUCTION Function ID,Function,Skill ID,skil,Concept ID,Concepts,Concept Description,Core/Elective
0,24,Analytics,254,Analytics Digital Solutions,5773,Advanced Data Analytics,Proficiency in advanced data analytics techniq...,Core
1,24,Analytics,254,Analytics Digital Solutions,4641,Data Visualization,Skills in presenting data through visual eleme...,Core
2,24,Analytics,254,Analytics Digital Solutions,5829,Real-time Data Analytics,Competence in real-time data analytics tools a...,Core
3,24,Analytics,62,Artificial Intelligence & Machine Learning,6529,AI Deployment and Scaling,Proficiency in deploying AI models into produc...,Core
4,24,Analytics,62,Artificial Intelligence & Machine Learning,6502,AI-Driven Automation,Ability to automate routine tasks and processe...,Core
...,...,...,...,...,...,...,...,...
7004,50,Legal,35,Customer Relationship Management,7787,Regulatory Compliance,Ensuring compliance with regulatory standards ...,Elective
7005,50,Legal,57,Database Management,7788,Regulatory Compliance,Ensuring regulatory compliance in database man...,Elective
7006,50,Legal,102,Cybersecurity & Information Security,6754,Compliance and Regulatory Knowledge,Knowledge of legal and regulatory requirements...,Elective
7007,50,Legal,106,Hardware & Networking,7789,Regulatory Compliance,Ensuring hardware and network systems adhere t...,Elective
7008,50,Legal,44,Vendor Management,5722,Compliance and Auditing,Skills in ensuring vendor compliance with lega...,Elective

In [40]:
#load data file
df2 = pd.read_excel("C:\\Users\\taslim.siddiqui\\Downloads\\Udemy FSC 1.xlsx")
df2

,product_sfid,product_id,CPP Name,course_journey__c,product_name,course_level,function_ids,function Name,skill_id,skill Name,concepts,concepts Name
0,0AbIh9To,24901,Udemy,B2B,"(Jetpack, Architecture and More)Advanced And...",Beginner,22,Information Technology,293,Parallel Computing,6876,Models
1,0AbXa8Ut,24645,Udemy,B2B,Object-oriented Programming in JavaScript,Intermediate,22,Information Technology,103,Front-End Developer,6849,JavaScript
2,0AnKw5Rl,24128,Udemy,B2B,Vue - The Complete Guide (incl. Router and C...,Beginner,22,Information Technology,103,Front-End Developer,6849,JavaScript
3,0AnKw5Rl,24128,Udemy,B2B,Vue - The Complete Guide (incl. Router and C...,Beginner,22,Information Technology,298,Perl,6864,Syntax
4,0ArCd7Lv,27407,Udemy,B2B,Bootstrap 5 From Scratch | Build 5 Modern Webs...,Beginner,22,Information Technology,103,Front-End Developer,6817,CSS
...,...,...,...,...,...,...,...,...,...,...,...,...
38691,przzd0g0p1,28069,Udemy,B2B,Email Marketing: Subscriber List Growth With C...,Beginner,42,HR - Rewards,255,Leadership,5041,Leadership - Decision Making
38692,przzd0g0p1,28069,Udemy,B2B,Email Marketing: Subscriber List Growth With C...,Beginner,43,HR - Talent Acquisition,255,Leadership,5041,Leadership - Decision Making
38693,przzd0g0p1,28069,Udemy,B2B,Email Marketing: Subscriber List Growth With C...,Beginner,47,Audit - Functional,255,Leadership,5041,Leadership - Decision Making
38694,przzd0g0p1,28069,Udemy,B2B,Email Marketing: Subscriber List Growth With C...,Beginner,48,Audit - Internal - IS IT,255,Leadership,5041,Leadership - Decision Making
38695,przzd0g0p1,28069,Udemy,B2B,Email Marketing: Subscriber List Growth With C...,Beginner,49,Audit - Internal - Offsite CCM,255,Leadership,5041,Leadership - Decision Making

In [ ]:
# Concept Column Row splitting code
df2['concepts'] = df2['concepts'].apply(
    lambda x: [int(i.strip()) for i in x.split(',')] if isinstance(x, str) else x
)

# Explode the 'concepts' column to create separate rows
df = df2.explode('concepts', ignore_index=True)
df['concepts'] = df['concepts'].fillna(0).astype(int)

df

,product_sfid,product_id,CPP Name,course_journey__c,product_name,course_level,function_ids,function Name,skill_id,skill Name,concepts,concepts Name
0,0AbIh9To,24901,Udemy,B2B,"(Jetpack, Architecture and More)Advanced And...",Beginner,22,Information Technology,293,Parallel Computing,6876,Models
1,0AbXa8Ut,24645,Udemy,B2B,Object-oriented Programming in JavaScript,Intermediate,22,Information Technology,103,Front-End Developer,6849,JavaScript
2,0AnKw5Rl,24128,Udemy,B2B,Vue - The Complete Guide (incl. Router and C...,Beginner,22,Information Technology,103,Front-End Developer,6849,JavaScript
3,0AnKw5Rl,24128,Udemy,B2B,Vue - The Complete Guide (incl. Router and C...,Beginner,22,Information Technology,298,Perl,6864,Syntax
4,0ArCd7Lv,27407,Udemy,B2B,Bootstrap 5 From Scratch | Build 5 Modern Webs...,Beginner,22,Information Technology,103,Front-End Developer,6817,CSS
...,...,...,...,...,...,...,...,...,...,...,...,...
38691,przzd0g0p1,28069,Udemy,B2B,Email Marketing: Subscriber List Growth With C...,Beginner,42,HR - Rewards,255,Leadership,5041,Leadership - Decision Making
38692,przzd0g0p1,28069,Udemy,B2B,Email Marketing: Subscriber List Growth With C...,Beginner,43,HR - Talent Acquisition,255,Leadership,5041,Leadership - Decision Making
38693,przzd0g0p1,28069,Udemy,B2B,Email Marketing: Subscriber List Growth With C...,Beginner,47,Audit - Functional,255,Leadership,5041,Leadership - Decision Making
38694,przzd0g0p1,28069,Udemy,B2B,Email Marketing: Subscriber List Growth With C...,Beginner,48,Audit - Internal - IS IT,255,Leadership,5041,Leadership - Decision Making
38695,przzd0g0p1,28069,Udemy,B2B,Email Marketing: Subscriber List Growth With C...,Beginner,49,Audit - Internal - Offsite CCM,255,Leadership,5041,Leadership - Decision Making

In [42]:
df['course_level'].unique()

array(['Beginner', 'Intermediate', 'Advanced'], dtype=object)

In [43]:
# Renaming Flexible to Beginner in Course level column
df['course_level'] = df['course_level'].replace('Flexible', 'Beginner')

In [44]:
df['course_level'].unique()

array(['Beginner', 'Intermediate', 'Advanced'], dtype=object)

In [45]:
# Concat of Skill Concept
df['FSC_concat'] = df['skill_id'].astype(str)+'|'+df['concepts'].astype(str)
df

,product_sfid,product_id,CPP Name,course_journey__c,product_name,course_level,function_ids,function Name,skill_id,skill Name,concepts,concepts Name,FSC_concat
0,0AbIh9To,24901,Udemy,B2B,"(Jetpack, Architecture and More)Advanced And...",Beginner,22,Information Technology,293,Parallel Computing,6876,Models,293|6876
1,0AbXa8Ut,24645,Udemy,B2B,Object-oriented Programming in JavaScript,Intermediate,22,Information Technology,103,Front-End Developer,6849,JavaScript,103|6849
2,0AnKw5Rl,24128,Udemy,B2B,Vue - The Complete Guide (incl. Router and C...,Beginner,22,Information Technology,103,Front-End Developer,6849,JavaScript,103|6849
3,0AnKw5Rl,24128,Udemy,B2B,Vue - The Complete Guide (incl. Router and C...,Beginner,22,Information Technology,298,Perl,6864,Syntax,298|6864
4,0ArCd7Lv,27407,Udemy,B2B,Bootstrap 5 From Scratch | Build 5 Modern Webs...,Beginner,22,Information Technology,103,Front-End Developer,6817,CSS,103|6817
...,...,...,...,...,...,...,...,...,...,...,...,...,...
38691,przzd0g0p1,28069,Udemy,B2B,Email Marketing: Subscriber List Growth With C...,Beginner,42,HR - Rewards,255,Leadership,5041,Leadership - Decision Making,255|5041
38692,przzd0g0p1,28069,Udemy,B2B,Email Marketing: Subscriber List Growth With C...,Beginner,43,HR - Talent Acquisition,255,Leadership,5041,Leadership - Decision Making,255|5041
38693,przzd0g0p1,28069,Udemy,B2B,Email Marketing: Subscriber List Growth With C...,Beginner,47,Audit - Functional,255,Leadership,5041,Leadership - Decision Making,255|5041
38694,przzd0g0p1,28069,Udemy,B2B,Email Marketing: Subscriber List Growth With C...,Beginner,48,Audit - Internal - IS IT,255,Leadership,5041,Leadership - Decision Making,255|5041
38695,przzd0g0p1,28069,Udemy,B2B,Email Marketing: Subscriber List Growth With C...,Beginner,49,Audit - Internal - Offsite CCM,255,Leadership,5041,Leadership - Decision Making,255|5041

In [46]:
# Making new dataframe of Advanced course level only.
Advanced = df[df['course_level'] == 'Advanced']
Advanced

,product_sfid,product_id,CPP Name,course_journey__c,product_name,course_level,function_ids,function Name,skill_id,skill Name,concepts,concepts Name,FSC_concat
18,0BeZm1Cn,25323,Udemy,B2B,AWS Certified Machine Learning Specialty Full ...,Advanced,22,Information Technology,44,Vendor Management,5005,Cost Management,44|5005
19,0BeZm1Cn,25323,Udemy,B2B,AWS Certified Machine Learning Specialty Full ...,Advanced,27,Collections,44,Vendor Management,5005,Cost Management,44|5005
20,0BeZm1Cn,25323,Udemy,B2B,AWS Certified Machine Learning Specialty Full ...,Advanced,28,Compliance,44,Vendor Management,5005,Cost Management,44|5005
21,0BeZm1Cn,25323,Udemy,B2B,AWS Certified Machine Learning Specialty Full ...,Advanced,35,Operations,44,Vendor Management,5005,Cost Management,44|5005
22,0BeZm1Cn,25323,Udemy,B2B,AWS Certified Machine Learning Specialty Full ...,Advanced,36,Business Excellence,44,Vendor Management,5005,Cost Management,44|5005
...,...,...,...,...,...,...,...,...,...,...,...,...,...
38475,przvqmdfmp,30989,Udemy,B2B,PMI-ACP Agile Certified Exam Prep - 21 PDUs,Advanced,38,Risk Management,37,Business Management,4590,Project Management,37|4590
38476,przvqmdfmp,30989,Udemy,B2B,PMI-ACP Agile Certified Exam Prep - 21 PDUs,Advanced,40,HR - Business,37,Business Management,4590,Project Management,37|4590
38477,przvqmdfmp,30989,Udemy,B2B,PMI-ACP Agile Certified Exam Prep - 21 PDUs,Advanced,41,HR - Talent & L&D,37,Business Management,4590,Project Management,37|4590
38478,przvqmdfmp,30989,Udemy,B2B,PMI-ACP Agile Certified Exam Prep - 21 PDUs,Advanced,42,HR - Rewards,37,Business Management,4590,Project Management,37|4590
38479,przvqmdfmp,30989,Udemy,B2B,PMI-ACP Agile Certified Exam Prep - 21 PDUs,Advanced,43,HR - Talent Acquisition,37,Business Management,4590,Project Management,37|4590

In [47]:
# Counting the number of courses in Advanced course level against the FSC_concat column.
result_Advanced =  Advanced.groupby("FSC_concat")["product_id"].nunique().reset_index()
result_Advanced.columns = ["FSC_concat", "Function_count_Advanced"]
result_Advanced

    FSC_concat  Function_count_Advanced
0     100|5647                        1
1     100|5932                        1
2     103|6816                        2
3     103|6817                        2
4     103|6849                        1
..         ...                      ...
129    68|4640                        1
130    68|5712                        1
131    69|5399                        1
132    97|5770                        1
133    97|5987                        1

[134 rows x 2 columns]

In [48]:
Beginner = df[df['course_level'] == 'Beginner']
Beginner

,product_sfid,product_id,CPP Name,course_journey__c,product_name,course_level,function_ids,function Name,skill_id,skill Name,concepts,concepts Name,FSC_concat
0,0AbIh9To,24901,Udemy,B2B,"(Jetpack, Architecture and More)Advanced And...",Beginner,22,Information Technology,293,Parallel Computing,6876,Models,293|6876
2,0AnKw5Rl,24128,Udemy,B2B,Vue - The Complete Guide (incl. Router and C...,Beginner,22,Information Technology,103,Front-End Developer,6849,JavaScript,103|6849
3,0AnKw5Rl,24128,Udemy,B2B,Vue - The Complete Guide (incl. Router and C...,Beginner,22,Information Technology,298,Perl,6864,Syntax,298|6864
4,0ArCd7Lv,27407,Udemy,B2B,Bootstrap 5 From Scratch | Build 5 Modern Webs...,Beginner,22,Information Technology,103,Front-End Developer,6817,CSS,103|6817
5,0ArCd7Lv,27407,Udemy,B2B,Bootstrap 5 From Scratch | Build 5 Modern Webs...,Beginner,22,Information Technology,103,Front-End Developer,6849,JavaScript,103|6849
...,...,...,...,...,...,...,...,...,...,...,...,...,...
38691,przzd0g0p1,28069,Udemy,B2B,Email Marketing: Subscriber List Growth With C...,Beginner,42,HR - Rewards,255,Leadership,5041,Leadership - Decision Making,255|5041
38692,przzd0g0p1,28069,Udemy,B2B,Email Marketing: Subscriber List Growth With C...,Beginner,43,HR - Talent Acquisition,255,Leadership,5041,Leadership - Decision Making,255|5041
38693,przzd0g0p1,28069,Udemy,B2B,Email Marketing: Subscriber List Growth With C...,Beginner,47,Audit - Functional,255,Leadership,5041,Leadership - Decision Making,255|5041
38694,przzd0g0p1,28069,Udemy,B2B,Email Marketing: Subscriber List Growth With C...,Beginner,48,Audit - Internal - IS IT,255,Leadership,5041,Leadership - Decision Making,255|5041
38695,przzd0g0p1,28069,Udemy,B2B,Email Marketing: Subscriber List Growth With C...,Beginner,49,Audit - Internal - Offsite CCM,255,Leadership,5041,Leadership - Decision Making,255|5041

In [49]:
result_Beginner =  Beginner.groupby("FSC_concat")["product_id"].nunique().reset_index()
result_Beginner.columns = ["FSC_concat", "Function_count_beginner"]
result_Beginner

    FSC_concat  Function_count_beginner
0     100|6114                        1
1     102|4698                       11
2     102|4733                        2
3     102|5573                        2
4     102|5888                        5
..         ...                      ...
731    98|6057                        3
732    98|6263                        5
733    98|6367                        2
734    98|6368                        3
735    98|6416                        3

[736 rows x 2 columns]

In [50]:
Intermediate = df[df['course_level'] == 'Intermediate']
Intermediate

,product_sfid,product_id,CPP Name,course_journey__c,product_name,course_level,function_ids,function Name,skill_id,skill Name,concepts,concepts Name,FSC_concat
1,0AbXa8Ut,24645,Udemy,B2B,Object-oriented Programming in JavaScript,Intermediate,22,Information Technology,103,Front-End Developer,6849,JavaScript,103|6849
9,0AuDz1Me,23482,Udemy,B2B,Microsoft Access 2013 Advanced Course,Intermediate,24,Analytics,319,ML Ops,6879,Data Management,319|6879
10,0AuDz1Me,23482,Udemy,B2B,Microsoft Access 2013 Advanced Course,Intermediate,25,Distribution,319,ML Ops,6879,Data Management,319|6879
11,0AuDz1Me,23482,Udemy,B2B,Microsoft Access 2013 Advanced Course,Intermediate,29,Sales,319,ML Ops,6879,Data Management,319|6879
41,0BgNf2Hm,23103,Udemy,B2B,Creating Bespoke Data Visualisations in Tablea...,Intermediate,24,Analytics,254,Analytics Digital Solutions,4641,Data Visualization,254|4641
...,...,...,...,...,...,...,...,...,...,...,...,...,...
38417,przswc0czv,28138,Udemy,B2B,Quick Start Guide to Oracle SOA 12c,Intermediate,28,Compliance,44,Vendor Management,4561,Project Risk Management,44|4561
38418,przswc0czv,28138,Udemy,B2B,Quick Start Guide to Oracle SOA 12c,Intermediate,35,Operations,44,Vendor Management,4561,Project Risk Management,44|4561
38419,przswc0czv,28138,Udemy,B2B,Quick Start Guide to Oracle SOA 12c,Intermediate,36,Business Excellence,44,Vendor Management,4561,Project Risk Management,44|4561
38420,przswc0czv,28138,Udemy,B2B,Quick Start Guide to Oracle SOA 12c,Intermediate,37,Finance & Accounts,44,Vendor Management,4561,Project Risk Management,44|4561
38421,przswc0czv,28138,Udemy,B2B,Quick Start Guide to Oracle SOA 12c,Intermediate,38,Risk Management,44,Vendor Management,4561,Project Risk Management,44|4561

In [51]:
result_Intermediate =  Intermediate.groupby("FSC_concat")["product_id"].nunique().reset_index()
result_Intermediate.columns = ["FSC_concat", "Function_count_intermediate"]
result_Intermediate

    FSC_concat  Function_count_intermediate
0     100|5428                            1
1     100|6114                            1
2     102|4733                            1
3     102|5888                            1
4     102|5927                            1
..         ...                          ...
451    79|6425                            2
452    79|6605                            2
453    96|4663                            1
454    98|4782                            1
455    98|6416                            1

[456 rows x 2 columns]

In [52]:
unique_values_df = df.drop_duplicates(subset=['FSC_concat'])
unique_values_df = unique_values_df[['FSC_concat']]
unique_values_df

      FSC_concat
0       293|6876
1       103|6849
3       298|6864
4       103|6817
6       294|6782
...          ...
38376   431|7366
38378   439|7368
38379   439|7369
38380   452|7337
38381   452|7341

[843 rows x 1 columns]

In [53]:
merged_df = pd.merge(unique_values_df, result_Beginner, on="FSC_concat", how="left")  # Merge df1 and df2
merged_df = pd.merge(merged_df, result_Intermediate, on="FSC_concat", how="left")  # Merge with df3
merged_df = pd.merge(merged_df, result_Advanced, on="FSC_concat", how="left")
merged_df

,FSC_concat,Function_count_beginner,Function_count_intermediate,Function_count_Advanced
0,293|6876,429.0,89.0,7.0
1,103|6849,373.0,67.0,1.0
2,298|6864,201.0,26.0,2.0
3,103|6817,223.0,26.0,2.0
4,294|6782,28.0,4.0,NaN
...,...,...,...,...
838,431|7366,1.0,NaN,NaN
839,439|7368,1.0,NaN,NaN
840,439|7369,1.0,NaN,NaN
841,452|7337,1.0,NaN,NaN
842,452|7341,1.0,NaN,NaN

In [54]:
# If you're working with a single column but want to keep it as a DataFrame:
merged_df['Function_count_beginner'] = merged_df['Function_count_beginner'].fillna(0).astype(int)
merged_df['Function_count_intermediate'] = merged_df['Function_count_intermediate'].fillna(0).astype(int)
merged_df['Function_count_Advanced'] = merged_df['Function_count_Advanced'].fillna(0).astype(int)
merged_df

,FSC_concat,Function_count_beginner,Function_count_intermediate,Function_count_Advanced
0,293|6876,429,89,7
1,103|6849,373,67,1
2,298|6864,201,26,2
3,103|6817,223,26,2
4,294|6782,28,4,0
...,...,...,...,...
838,431|7366,1,0,0
839,439|7368,1,0,0
840,439|7369,1,0,0
841,452|7337,1,0,0
842,452|7341,1,0,0

In [55]:
#df1['Skill ID'].unique()
df1['FSC_concat']= df1['Skill ID'].fillna(0).astype(int).astype(str)+"|"+df1['Concept ID'].fillna(0).astype(int).astype(str)
df1

,PRODUCTION Function ID,Function,Skill ID,skil,Concept ID,Concepts,Concept Description,Core/Elective,FSC_concat
0,24,Analytics,254,Analytics Digital Solutions,5773,Advanced Data Analytics,Proficiency in advanced data analytics techniq...,Core,254|5773
1,24,Analytics,254,Analytics Digital Solutions,4641,Data Visualization,Skills in presenting data through visual eleme...,Core,254|4641
2,24,Analytics,254,Analytics Digital Solutions,5829,Real-time Data Analytics,Competence in real-time data analytics tools a...,Core,254|5829
3,24,Analytics,62,Artificial Intelligence & Machine Learning,6529,AI Deployment and Scaling,Proficiency in deploying AI models into produc...,Core,62|6529
4,24,Analytics,62,Artificial Intelligence & Machine Learning,6502,AI-Driven Automation,Ability to automate routine tasks and processe...,Core,62|6502
...,...,...,...,...,...,...,...,...,...
7004,50,Legal,35,Customer Relationship Management,7787,Regulatory Compliance,Ensuring compliance with regulatory standards ...,Elective,35|7787
7005,50,Legal,57,Database Management,7788,Regulatory Compliance,Ensuring regulatory compliance in database man...,Elective,57|7788
7006,50,Legal,102,Cybersecurity & Information Security,6754,Compliance and Regulatory Knowledge,Knowledge of legal and regulatory requirements...,Elective,102|6754
7007,50,Legal,106,Hardware & Networking,7789,Regulatory Compliance,Ensuring hardware and network systems adhere t...,Elective,106|7789
7008,50,Legal,44,Vendor Management,5722,Compliance and Auditing,Skills in ensuring vendor compliance with lega...,Elective,44|5722

In [56]:
automated_df = pd.merge(df1,merged_df, on ='FSC_concat', how = 'left' )
automated_df['Function_count_beginner'] = automated_df['Function_count_beginner'].fillna(0).astype(int)
automated_df['Function_count_intermediate'] = automated_df['Function_count_intermediate'].fillna(0).astype(int)
automated_df['Function_count_Advanced'] = automated_df['Function_count_Advanced'].fillna(0).astype(int)
automated_df

,PRODUCTION Function ID,Function,Skill ID,skil,Concept ID,Concepts,Concept Description,Core/Elective,FSC_concat,Function_count_beginner,Function_count_intermediate,Function_count_Advanced
0,24,Analytics,254,Analytics Digital Solutions,5773,Advanced Data Analytics,Proficiency in advanced data analytics techniq...,Core,254|5773,4,0,0
1,24,Analytics,254,Analytics Digital Solutions,4641,Data Visualization,Skills in presenting data through visual eleme...,Core,254|4641,129,13,0
2,24,Analytics,254,Analytics Digital Solutions,5829,Real-time Data Analytics,Competence in real-time data analytics tools a...,Core,254|5829,4,0,0
3,24,Analytics,62,Artificial Intelligence & Machine Learning,6529,AI Deployment and Scaling,Proficiency in deploying AI models into produc...,Core,62|6529,0,0,0
4,24,Analytics,62,Artificial Intelligence & Machine Learning,6502,AI-Driven Automation,Ability to automate routine tasks and processe...,Core,62|6502,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
7004,50,Legal,35,Customer Relationship Management,7787,Regulatory Compliance,Ensuring compliance with regulatory standards ...,Elective,35|7787,0,0,0
7005,50,Legal,57,Database Management,7788,Regulatory Compliance,Ensuring regulatory compliance in database man...,Elective,57|7788,0,0,0
7006,50,Legal,102,Cybersecurity & Information Security,6754,Compliance and Regulatory Knowledge,Knowledge of legal and regulatory requirements...,Elective,102|6754,0,0,0
7007,50,Legal,106,Hardware & Networking,7789,Regulatory Compliance,Ensuring hardware and network systems adhere t...,Elective,106|7789,0,0,0
7008,50,Legal,44,Vendor Management,5722,Compliance and Auditing,Skills in ensuring vendor compliance with lega...,Elective,44|5722,0,0,0

In [57]:
automated_df.to_excel("C:\\Users\\taslim.siddiqui\\Downloads//automated_deficiet_10-04-2025_Udemy.xlsx")