**Time Converter

In [1]:
import pandas as pd
#load excel
df = pd.read_csv("C:\\Users\\taslim.siddiqui\\Downloads\\production_recoRatingDataRecords (9).csv")
#df=pd.read_excel("//Users//romitbenkar//Desktop//Office//07-11-2024//other_output.xlsx")

# Replace 'apple' with 'orange' and 'banana' with 'grape' in column 'B'
df['duration_medium__c'] = df['duration_medium__c'].replace({'Day': 'Days', 'Month': 'Months','Year':'Years'})

# Define conversion factors to seconds for each mode
conversion_factors = {
    'years': 365 * 24 * 60 * 60,        # approximate (ignores leap years)
    'months': 30.44 * 24 * 60 * 60,     # average month
    'weeks': 7 * 24 * 60 * 60,
    'days': 24 * 60 * 60,
    'hours': 60 * 60,
    'minutes': 60
}

df['duration_medium__c']=df['duration_medium__c'].astype(str)


# Function to convert duration based on the mode
def convert_to_seconds(row):
    duration = row['course_duration__c']
    mode = row['duration_medium__c'].strip().lower()  # normalize to lowercase
    return duration * conversion_factors.get(mode, 1)  # Default to 1 if mode is not found

# Apply the conversion function to each row
df['Duration_in_seconds'] = df.apply(convert_to_seconds, axis=1)

# Add a column that checks if the duration in seconds is less than or equal to a week
df['Is_within_a_week'] = df['Duration_in_seconds'] <= 7 * 24 * 60 * 60

# Save the result back to Excel
#df.to_excel('//Users//romitbenkar//Desktop//Office//19-11-24//timeconvertoutput.xlsx', index=False)
df

,product_sfid,product_id,mpid,course_provider_platform_name__c,product_name,course_level,duration_medium__c,course_duration__c,price__c,loan_amount__c,inr_amount__c,skill_id,concepts,Duration_in_seconds,Is_within_a_week
0,01t8n000000GrJPAA0,4641,17890,Amity Future Academy,PG Program in Digital Marketing Strategies (PG...,Advanced,Months,12.00,NaN,170000.0,170000.0,120,NaN,31560192.0,False
1,01t8n000000GrJQAA0,4642,16262,Amity Future Academy,PG Program in Product Management (PGP-PM),Advanced,Months,12.00,NaN,215000.0,215000.0,36,5336,31560192.0,False
2,01t8n000000GrJRAA0,4643,16885,Amity Future Academy,Post Graduate Diploma in Management,Advanced,Months,6.00,NaN,120000.0,120000.0,98,4550,15780096.0,False
3,01t8n000000GrJSAA0,4644,17637,Amity Future Academy,Post Graduate Diploma in Management,Advanced,Months,6.00,NaN,120000.0,120000.0,39,NaN,15780096.0,False
4,01t8n000000GrJTAA0,4645,15978,Amity Future Academy,Post Graduate Program in Big Data Architecture...,Advanced,Months,6.00,NaN,100000.0,100000.0,63,5652,15780096.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20940,przzd0g0p1,28069,26535,Udemy,Email Marketing: Subscriber List Growth With C...,Beginner,Minutes,215.00,23850.0,23850.0,23850.0,107,6615,12900.0,True
20941,przzj4igrr,14130,14308,Coursera,Resourcing a Project Schedule,Beginner,Hours,0.30,1.0,0.0,0.0,39,6101,1080.0,True
20942,przzltt2yl,34946,35729,GVC,"Programming Languages, Part B",Intermediate,Hours,18.00,NaN,1.0,1.0,164,6893,64800.0,True
20943,przzvn6z59,14710,11674,Coursera,Exam Prep CKA: Certified Kubernetes Administrator,Intermediate,Hours,18.93,1.0,0.0,0.0,107,NaN,68148.0,True
20944,przzxluxi8,20241,12028,Coursera,Generative AI Primer,Beginner,Hours,1.48,1.0,0.0,0.0,317,NaN,5328.0,True

Integration

In [2]:
values_to_check = ['Henry Harvin Education','Henry Harvin','Guvi Geeks','Edujournal','Sharpener','Business Toys Skills School']

# Check if any values in the DataFrame are in the list
df['Integration'] = df['course_provider_platform_name__c'].isin(values_to_check)
df

,product_sfid,product_id,mpid,course_provider_platform_name__c,product_name,course_level,duration_medium__c,course_duration__c,price__c,loan_amount__c,inr_amount__c,skill_id,concepts,Duration_in_seconds,Is_within_a_week,Integration
0,01t8n000000GrJPAA0,4641,17890,Amity Future Academy,PG Program in Digital Marketing Strategies (PG...,Advanced,Months,12.00,NaN,170000.0,170000.0,120,NaN,31560192.0,False,False
1,01t8n000000GrJQAA0,4642,16262,Amity Future Academy,PG Program in Product Management (PGP-PM),Advanced,Months,12.00,NaN,215000.0,215000.0,36,5336,31560192.0,False,False
2,01t8n000000GrJRAA0,4643,16885,Amity Future Academy,Post Graduate Diploma in Management,Advanced,Months,6.00,NaN,120000.0,120000.0,98,4550,15780096.0,False,False
3,01t8n000000GrJSAA0,4644,17637,Amity Future Academy,Post Graduate Diploma in Management,Advanced,Months,6.00,NaN,120000.0,120000.0,39,NaN,15780096.0,False,False
4,01t8n000000GrJTAA0,4645,15978,Amity Future Academy,Post Graduate Program in Big Data Architecture...,Advanced,Months,6.00,NaN,100000.0,100000.0,63,5652,15780096.0,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20940,przzd0g0p1,28069,26535,Udemy,Email Marketing: Subscriber List Growth With C...,Beginner,Minutes,215.00,23850.0,23850.0,23850.0,107,6615,12900.0,True,False
20941,przzj4igrr,14130,14308,Coursera,Resourcing a Project Schedule,Beginner,Hours,0.30,1.0,0.0,0.0,39,6101,1080.0,True,False
20942,przzltt2yl,34946,35729,GVC,"Programming Languages, Part B",Intermediate,Hours,18.00,NaN,1.0,1.0,164,6893,64800.0,True,False
20943,przzvn6z59,14710,11674,Coursera,Exam Prep CKA: Certified Kubernetes Administrator,Intermediate,Hours,18.93,1.0,0.0,0.0,107,NaN,68148.0,True,False
20944,przzxluxi8,20241,12028,Coursera,Generative AI Primer,Beginner,Hours,1.48,1.0,0.0,0.0,317,NaN,5328.0,True,False

Concept Count

In [3]:
def count_commas(val):
    if pd.isna(val):
        return 0
    elif ',' in val:
        return val.count(',') + 1
    else:
        return 1
df['concept_count']=df['concepts'].apply(count_commas)
df

,product_sfid,product_id,mpid,course_provider_platform_name__c,product_name,course_level,duration_medium__c,course_duration__c,price__c,loan_amount__c,inr_amount__c,skill_id,concepts,Duration_in_seconds,Is_within_a_week,Integration,concept_count
0,01t8n000000GrJPAA0,4641,17890,Amity Future Academy,PG Program in Digital Marketing Strategies (PG...,Advanced,Months,12.00,NaN,170000.0,170000.0,120,NaN,31560192.0,False,False,0
1,01t8n000000GrJQAA0,4642,16262,Amity Future Academy,PG Program in Product Management (PGP-PM),Advanced,Months,12.00,NaN,215000.0,215000.0,36,5336,31560192.0,False,False,1
2,01t8n000000GrJRAA0,4643,16885,Amity Future Academy,Post Graduate Diploma in Management,Advanced,Months,6.00,NaN,120000.0,120000.0,98,4550,15780096.0,False,False,1
3,01t8n000000GrJSAA0,4644,17637,Amity Future Academy,Post Graduate Diploma in Management,Advanced,Months,6.00,NaN,120000.0,120000.0,39,NaN,15780096.0,False,False,0
4,01t8n000000GrJTAA0,4645,15978,Amity Future Academy,Post Graduate Program in Big Data Architecture...,Advanced,Months,6.00,NaN,100000.0,100000.0,63,5652,15780096.0,False,False,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20940,przzd0g0p1,28069,26535,Udemy,Email Marketing: Subscriber List Growth With C...,Beginner,Minutes,215.00,23850.0,23850.0,23850.0,107,6615,12900.0,True,False,1
20941,przzj4igrr,14130,14308,Coursera,Resourcing a Project Schedule,Beginner,Hours,0.30,1.0,0.0,0.0,39,6101,1080.0,True,False,1
20942,przzltt2yl,34946,35729,GVC,"Programming Languages, Part B",Intermediate,Hours,18.00,NaN,1.0,1.0,164,6893,64800.0,True,False,1
20943,przzvn6z59,14710,11674,Coursera,Exam Prep CKA: Certified Kubernetes Administrator,Intermediate,Hours,18.93,1.0,0.0,0.0,107,NaN,68148.0,True,False,0
20944,przzxluxi8,20241,12028,Coursera,Generative AI Primer,Beginner,Hours,1.48,1.0,0.0,0.0,317,NaN,5328.0,True,False,0

In [4]:
deficit_0 =(df['concept_count']== 0 ).sum()
deficit_0

2576

No concept column

In [5]:
df['no_concept'] = df['concepts'].isna()

Only Udemy data

In [6]:

# Sample DataFrame
df# data is the file which will only have CPP names

# List of values to check
values_to_check = ['Udemy']

# Check if any values in the DataFrame are in the list
df['Udemy'] = df['course_provider_platform_name__c'].isin(values_to_check)
udemy_df = df.query("Udemy == True and no_concept == False")
udemy_df
#df.to_excel("//Users//romitbenkar//Desktop//Office//19-11-2024//Udemy_output.xlsx")

,product_sfid,product_id,mpid,course_provider_platform_name__c,product_name,course_level,duration_medium__c,course_duration__c,price__c,loan_amount__c,inr_amount__c,skill_id,concepts,Duration_in_seconds,Is_within_a_week,Integration,concept_count,no_concept,Udemy
1404,0AbIh9To,24901,23122,Udemy,"(Jetpack, Architecture and More)Advanced And...",Beginner,Minutes,2250.0,23850.0,23850.0,23850.0,293,6876,135000.0,True,False,1,False,True
1405,0AbXa8Ut,24645,22866,Udemy,Object-oriented Programming in JavaScript,Intermediate,Minutes,234.0,23850.0,23850.0,23850.0,103,6849,14040.0,True,False,1,False,True
1406,0AnKw5Rl,24128,22349,Udemy,Vue - The Complete Guide (incl. Router and C...,Beginner,Minutes,1912.0,23850.0,23850.0,23850.0,103,6849,114720.0,True,False,1,False,True
1407,0ArCd7Lv,27407,25631,Udemy,Bootstrap 5 From Scratch | Build 5 Modern Webs...,Beginner,Minutes,798.0,23850.0,23850.0,23850.0,103,"6817 , 6849",47880.0,True,False,2,False,True
1408,0ArKm5Sb,24969,23190,Udemy,Complete Deep Learning In R With Keras and O...,Beginner,Minutes,475.0,23850.0,23850.0,23850.0,293,6778,28500.0,True,False,1,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20920,przy1fgag3,28644,27110,Udemy,Microsoft Teams: Teams Essentials for the work...,Beginner,Minutes,135.0,23850.0,23850.0,23850.0,44,4561,8100.0,True,False,1,False,True
20925,przyc3rjqv,31300,29856,Udemy,Master Certified Fraud Examiner (CFE) Essentia...,Beginner,Minutes,121.0,0.0,23850.0,23850.0,24,5635,7260.0,True,False,1,False,True
20926,przyhu62lv,29152,27615,Udemy,Negotiating Your Salary and Compensation,Beginner,Minutes,133.0,23850.0,23850.0,23850.0,255,5041,7980.0,True,False,1,False,True
20936,przyxra2de,29045,27508,Udemy,Advanced Cryptography Concepts,Beginner,Minutes,260.0,23850.0,23850.0,23850.0,291,4648,15600.0,True,False,1,False,True
20940,przzd0g0p1,28069,26535,Udemy,Email Marketing: Subscriber List Growth With C...,Beginner,Minutes,215.0,23850.0,23850.0,23850.0,107,6615,12900.0,True,False,1,False,True

In [7]:

# Sample DataFrame
df# data is the file which will only have CPP names

# List of values to check
values_to_check = ['Udemy']

# Check if any values in the DataFrame are in the list
df['Udemy'] = df['course_provider_platform_name__c'].isin(values_to_check)
udemy_0_df = df.query("Udemy == True and no_concept == True")
udemy_0_df

,product_sfid,product_id,mpid,course_provider_platform_name__c,product_name,course_level,duration_medium__c,course_duration__c,price__c,loan_amount__c,inr_amount__c,skill_id,concepts,Duration_in_seconds,Is_within_a_week,Integration,concept_count,no_concept,Udemy
1726,1FkNf0Wo,22871,21092,Udemy,ACCA MA (F2) A Complete Course on Management A...,Beginner,Minutes,2014.0,23850.0,23850.0,23850.0,49,NaN,120840.0,True,False,0,True,True
1978,2FeBo7Oj,25745,23967,Udemy,AWS Technical Essentials - Hands-On Training ...,Beginner,Minutes,866.0,23850.0,23850.0,23850.0,44,NaN,51960.0,True,False,0,True,True
2862,5TgAx9Cg,22983,21204,Udemy,Certified Key Performance Indicators Professio...,Beginner,Minutes,448.0,23850.0,23850.0,23850.0,49,NaN,26880.0,True,False,0,True,True
2915,5YrGr8Hy,22895,21116,Udemy,Automated Cryptocurrency Portfolio Investing w...,Beginner,Minutes,1931.0,23850.0,23850.0,23850.0,261,NaN,115860.0,True,False,0,True,True
3211,7BpKm9Gj,23448,21669,Udemy,"Master PMP Cost Management: Plan, Budget, Esti...",Beginner,Minutes,224.0,23850.0,23850.0,23850.0,261,NaN,13440.0,True,False,0,True,True
3592,8ObDt0Ty,23451,21672,Udemy,Master SWOT Analysis and Business Strategy f...,Beginner,Minutes,185.0,23850.0,23850.0,23850.0,49,NaN,11100.0,True,False,0,True,True
4025,pr04rriz87,29480,27943,Udemy,Effective Leadership,Beginner,Minutes,49.0,23850.0,23850.0,23850.0,255,NaN,2940.0,True,False,0,True,True
5754,pr3vmyyxgg,30260,28723,Udemy,Chaos Engineering using Azure Chaos Studio,Beginner,Minutes,74.0,23850.0,23850.0,23850.0,261,NaN,4440.0,True,False,0,True,True
5942,pr48w18bp0,28040,26506,Udemy,Leadership: Practical Leadership Skills,Beginner,Minutes,200.0,23850.0,23850.0,23850.0,255,NaN,12000.0,True,False,0,True,True
6173,pr4rce05qb,30210,28673,Udemy,"Ethical AI Decision Making, Insights for Leade...",Beginner,Minutes,126.0,23850.0,23850.0,23850.0,261,NaN,7560.0,True,False,0,True,True
7306,pr72kec05o,27984,26450,Udemy,Lean Six Sigma Green Belt Online Course (2023),Beginner,Minutes,967.0,23850.0,23850.0,23850.0,39,NaN,58020.0,True,False,0,True,True
8367,pr9d9b50m9,28381,26847,Udemy,Informed Risk Taking : Risk Management Process...,Beginner,Minutes,532.0,23850.0,23850.0,23850.0,406,NaN,31920.0,True,False,0,True,True
8373,pr9dhr23kk,29614,28077,Udemy,Developing Your Executive Leadership Skills,Intermediate,Minutes,52.0,23850.0,23850.0,23850.0,255,NaN,3120.0,True,False,0,True,True
9304,prbg329x5m,28263,26729,Udemy,"Leadership: How to Influence, Inspire and Impa...",Beginner,Minutes,91.0,23850.0,23850.0,23850.0,255,NaN,5460.0,True,False,0,True,True
9873,prckjmlvhq,29660,28123,Udemy,Managing a Global Team with Confidence,Beginner,Minutes,35.0,23850.0,23850.0,23850.0,255,NaN,2100.0,True,False,0,True,True
10726,preelbycur,29646,28109,Udemy,Leadership - Rise of a Leader (Lead people wit...,Beginner,Minutes,91.0,23850.0,23850.0,23850.0,255,NaN,5460.0,True,False,0,True,True
11622,prgh28omad,30150,28613,Udemy,Web Performance In Practice: Master Core Web V...,Beginner,Minutes,204.0,23850.0,23850.0,23850.0,106,NaN,12240.0,True,False,0,True,True
12469,pridfixh08,29375,27838,Udemy,Enterprise Risk Management,Advanced,Minutes,1055.0,23850.0,23850.0,23850.0,21,NaN,63300.0,True,False,0,True,True
14037,prllet9osu,30939,29495,Udemy,Manage Change Through Collaboration and Team Work,Beginner,Minutes,102.0,0.0,0.0,0.0,262,NaN,6120.0,True,False,0,True,True
16712,prr7lx775u,29532,27995,Udemy,Leading & Managing People [Effectively],Beginner,Minutes,119.0,23850.0,23850.0,23850.0,255,NaN,7140.0,True,False,0,True,True
16942,prrn4jj0va,28014,26480,Udemy,"Management - Leadership, Negotiating, Assertiv...",Beginner,Minutes,128.0,23850.0,23850.0,23850.0,255,NaN,7680.0,True,False,0,True,True
17951,prtq3w17ir,29930,28393,Udemy,Product Owner II for Agile Intermediate: Certi...,Beginner,Minutes,379.0,23850.0,23850.0,23850.0,36,NaN,22740.0,True,False,0,True,True
18635,prv7lg5yyb,29127,27590,Udemy,Leadership & Management Skills: 2-in-1 Masterc...,Beginner,Minutes,2655.0,23850.0,23850.0,23850.0,255,NaN,159300.0,True,False,0,True,True
19298,prwkzmf60z,30271,28734,Udemy,Leadership Style: Discover & Maximize Your Lea...,Beginner,Minutes,100.0,23850.0,23850.0,23850.0,255,NaN,6000.0,True,False,0,True,True
19666,prxcjr25z4,30054,28517,Udemy,Body Language & Nonverbal Communication in Bus...,Beginner,Minutes,125.0,23850.0,23850.0,23850.0,64,NaN,7500.0,True,False,0,True,True
19676,prxd7fln6n,29050,27513,Udemy,Smart Tips: Leadership,Beginner,Minutes,172.0,23850.0,23850.0,23850.0,255,NaN,10320.0,True,False,0,True,True
19799,prxn9li6ss,31017,29573,Udemy,Collaboration with Emotional Intelligence,Intermediate,Minutes,184.0,0.0,0.0,0.0,262,NaN,11040.0,True,False,0,True,True
19829,prxp6bib17,28731,27197,Udemy,Jira Crash Course | Jira Fundamentals for Agil...,Beginner,Minutes,138.0,23850.0,23850.0,23850.0,39,NaN,8280.0,True,False,0,True,True

Only ABC data

In [8]:
# List of values to check
values_to_check = ['Coursera','GVC','Gyanodaya Virtual Campus','CIEL']

# Check if values in 'course_provider_platform_name__c' column are in the list, and create a boolean column 'ABC'
df['ABC'] = df['course_provider_platform_name__c'].isin(values_to_check)

# Save the updated DataFrame to a new Excel file
#df.to_excel("//Users//romitbenkar//Desktop//Office//07-11-2024//ABCoutput.xlsx", index=False)
abc_df = df.query("ABC == True and no_concept == False")
abc_df
#df.to_excel("//Users//romitbenkar//Desktop//Office//19-11-2024//Udemy_output.xlsx")

,product_sfid,product_id,mpid,course_provider_platform_name__c,product_name,course_level,duration_medium__c,course_duration__c,price__c,loan_amount__c,inr_amount__c,skill_id,concepts,Duration_in_seconds,Is_within_a_week,Integration,concept_count,no_concept,Udemy,ABC
3972,pr000be54a,22145,20095,GVC,Advanced Visualizations & Dashboards: Visualiz...,Intermediate,Hours,0.34,1.0,0.0,1.0,336,4641,1224.0,True,False,1,False,False,True
3974,pr00ll9a88,14368,15208,Coursera,Use SurveyMonkey to Create a Survey and Analyz...,Beginner,Hours,0.40,1.0,0.0,0.0,123,5497,1440.0,True,False,1,False,False,True
3975,pr00nc2nuj,19718,12119,Coursera,Getting Started with Facebook Pixel,Beginner,Hours,NaN,1.0,0.0,0.0,117,5274,NaN,False,False,1,False,False,True
3980,pr015bytb9,12844,8295,GVC,CompTIA A+ Core 1: Wireless Networking & Services,Intermediate,Hours,2.25,1.0,0.0,0.0,106,6575,8100.0,True,False,1,False,False,True
3982,pr01iiouag,34882,35609,GVC,Cryptography and Information Theory,Intermediate,Hours,4.60,NaN,1.0,1.0,290,4648,16560.0,True,False,1,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20935,przyx8v5ue,14285,10322,Coursera,"Cluster Analysis, Association Mining, and Mode...",Intermediate,Hours,3.95,1.0,0.0,0.0,123,5224,14220.0,True,False,1,False,False,True
20937,przz7qgy8j,20005,14847,Coursera,Technical Managerial Written Skills,Beginner,Hours,18.87,1.0,0.0,0.0,130,6061,67932.0,True,False,1,False,False,True
20938,przz9s4oct,16916,10069,Coursera,Building Your Freelancing Career Capstone,Intermediate,Hours,11.93,1.0,0.0,0.0,129,5334,42948.0,True,False,1,False,False,True
20941,przzj4igrr,14130,14308,Coursera,Resourcing a Project Schedule,Beginner,Hours,0.30,1.0,0.0,0.0,39,6101,1080.0,True,False,1,False,False,True
20942,przzltt2yl,34946,35729,GVC,"Programming Languages, Part B",Intermediate,Hours,18.00,NaN,1.0,1.0,164,6893,64800.0,True,False,1,False,False,True

In [9]:
# List of values to check
values_to_check = ['Coursera','GVC','Gyanodaya Virtual Campus','CIEL']

# Check if values in 'course_provider_platform_name__c' column are in the list, and create a boolean column 'ABC'
df['ABC'] = df['course_provider_platform_name__c'].isin(values_to_check)

# Save the updated DataFrame to a new Excel file
#df.to_excel("//Users//romitbenkar//Desktop//Office//07-11-2024//ABCoutput.xlsx", index=False)
abc_0_df = df.query("ABC == True and no_concept == True")
abc_0_df
#df.to_excel("//Users//romitbenkar//Desktop//Office//19-11-2024//Udemy_output.xlsx")

,product_sfid,product_id,mpid,course_provider_platform_name__c,product_name,course_level,duration_medium__c,course_duration__c,price__c,loan_amount__c,inr_amount__c,skill_id,concepts,Duration_in_seconds,Is_within_a_week,Integration,concept_count,no_concept,Udemy,ABC
3973,pr0072y7ai,17054,13847,Coursera,"Personal Productivity, Time Management and Pri...",Beginner,Hours,6.32,1.0,0.0,0.0,130,NaN,22752.0,True,False,0,True,False,True
4045,pr06e8hqrz,14035,14086,Coursera,Project Management: Control using the Earned V...,Beginner,Hours,1.87,1.0,0.0,0.0,37,NaN,6732.0,True,False,0,True,False,True
4059,pr07ffp1wt,14715,14357,Coursera,Running a Node.js Container on Google Kubernet...,Beginner,Hours,0.67,1.0,0.0,0.0,108,NaN,2412.0,True,False,0,True,False,True
4080,pr08pu8d3g,19039,14138,Coursera,PyCaret: Anatomy of Classification,Intermediate,Hours,0.20,1.0,0.0,0.0,65,NaN,720.0,True,False,0,True,False,True
4081,pr08qdarvu,17992,10918,Coursera,Creativity Toolkit I: Changing Perspectives,Advanced,Hours,10.70,1.0,0.0,0.0,262,NaN,38520.0,True,False,0,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20899,przwql4s97,19202,13317,Coursera,Machine Learning Operations (MLOps) with Verte...,Intermediate,Hours,NaN,1.0,0.0,0.0,319,NaN,NaN,False,False,0,True,False,True
20918,przxwst6s4,16924,13794,Coursera,Our Share: Employee Ownership as a Wealth Shar...,Beginner,Hours,15.08,1.0,0.0,0.0,267,NaN,54288.0,True,False,0,True,False,True
20921,przy2ytv16,21460,19450,Coursera,Database Design and Operational Business Intel...,Beginner,Hours,NaN,1.0,0.0,1.0,66,NaN,NaN,False,False,0,True,False,True
20943,przzvn6z59,14710,11674,Coursera,Exam Prep CKA: Certified Kubernetes Administrator,Intermediate,Hours,18.93,1.0,0.0,0.0,107,NaN,68148.0,True,False,0,True,False,True
20944,przzxluxi8,20241,12028,Coursera,Generative AI Primer,Beginner,Hours,1.48,1.0,0.0,0.0,317,NaN,5328.0,True,False,0,True,False,True

non_corporate_df(No ABC and Udemy)

In [10]:

non_corporate_df = df.query("ABC == False and Udemy == False and no_concept == False").sort_values(by='Duration_in_seconds')
non_corporate_df

,product_sfid,product_id,mpid,course_provider_platform_name__c,product_name,course_level,duration_medium__c,course_duration__c,price__c,loan_amount__c,inr_amount__c,skill_id,concepts,Duration_in_seconds,Is_within_a_week,Integration,concept_count,no_concept,Udemy,ABC
1300,01t8n000000JE6wAAG,10007,15551,Skill Smith,Java Booster Program Offline,Advanced,Minutes,3.0,15.0,118000.00,118000.0,213,6107,1.800000e+02,True,False,1,False,False,False
1301,01t8n000000JE6yAAG,10009,15708,Skill Smith,Angular Master Program Offline,Advanced,Minutes,3.0,5.0,118000.00,118000.0,111,5747,1.800000e+02,True,False,1,False,False,False
1298,01t8n000000JE6uAAG,10005,15553,Skill Smith,Full Stack Program (React JS and Node JS) Offline,Advanced,Minutes,6.0,15.0,1295.48,1274.0,213,6107,3.600000e+02,True,False,1,False,False,False
19202,prwea1wbu6,32056,30730,Expertrons,Business Analysis using Excel,Beginner,Minutes,18.0,20000.0,20000.00,20000.0,259,5002,1.080000e+03,True,False,1,False,False,False
15507,prom1ezo1m,32060,30734,Expertrons,Basics of LinkedIn,Beginner,Minutes,25.0,20000.0,20000.00,20000.0,130,5812,1.500000e+03,True,False,1,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
462,01t8n000000GrsuAAC,6842,15579,Masters Union,Undergraduate Programme,Beginner,Years,6.0,NaN,2925000.00,2925000.0,21,5051,1.892160e+08,False,False,1,False,False,False
11369,prfwoo5mcq,27775,25999,IMI Delhi,Post Graduate Diploma in Management (Online),Advanced,Years,24.0,295000.0,295000.00,295000.0,64,4928,7.568640e+08,False,False,1,False,False,False
529,01t8n000000GrxEAAS,7140,17371,upGrad,MBA Leading Business Transformation,Advanced,Months,585.0,365000.0,1344753.00,1344753.0,130,6213,1.538559e+09,False,False,1,False,False,False
85,01t8n000000GrYbAAK,5575,16657,Edudelphi,Certified Fraud Examiner Course in India,Advanced,nan,NaN,NaN,439.32,36990.0,256,"5400 , 5503 , 5593 , 5611 , 5645 , 5740 , 5760...",NaN,False,False,11,False,False,False
150,01t8n000000GreMAAS,5940,14641,Fireblaze AI School,SQL for Data Science,Advanced,nan,NaN,NaN,2499.00,2499.0,164,4778,NaN,False,False,1,False,False,False

In [11]:
non_corporate_0_df = df.query("ABC == False and Udemy == False and no_concept == True").sort_values(by='Duration_in_seconds')
non_corporate_0_df

,product_sfid,product_id,mpid,course_provider_platform_name__c,product_name,course_level,duration_medium__c,course_duration__c,price__c,loan_amount__c,inr_amount__c,skill_id,concepts,Duration_in_seconds,Is_within_a_week,Integration,concept_count,no_concept,Udemy,ABC
1306,01t8n000000JE73AAG,10014,15544,Skill Smith,Master React Native Program Online,Advanced,Minutes,3.0,9.0,777.29,764.0,110,NaN,180.0,True,False,0,True,False,False
1305,01t8n000000JE72AAG,10013,16508,Skill Smith,Master React Native Program Offline,Advanced,Minutes,3.0,9.0,777.29,764.0,110,NaN,180.0,True,False,0,True,False,False
1299,01t8n000000JE6vAAG,10006,15552,Skill Smith,Full Stack Program (React JS and Node JS) Online,Advanced,Minutes,6.0,15.0,1295.48,1274.0,104,NaN,360.0,True,False,0,True,False,False
4488,pr140tds7q,21046,18972,Eduonix,Business Analytics for Beginners,Beginner,Minutes,15.0,22488.0,22488.00,22488.0,125,NaN,900.0,True,False,0,True,False,False
6256,pr4vvkrab4,31390,29946,EBC Learning,Private Equity and Venture Capital: Mastering ...,Advanced,Minutes,42.0,5900.0,5900.00,5900.0,29,NaN,2520.0,True,False,0,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1393,01tTZ000000gwEvYAI,10504,5894,The Design Village Easebuzz,Interaction & Ux Design,Beginner,Years,4.0,2200000.0,2200000.00,2200000.0,73,NaN,126144000.0,False,False,0,True,False,False
1398,01tTZ000000gwFWYAY,10541,5922,The Design Village Easebuzz,Product Design,Beginner,Years,4.0,2200000.0,2200000.00,2200000.0,79,NaN,126144000.0,False,False,0,True,False,False
5803,pr3yro2h81,11180,15999,Physics Wallah,UG Course in Computer Science & Artificial Int...,Advanced,Years,4.0,1519000.0,1519000.00,1519000.0,62,NaN,126144000.0,False,False,0,True,False,False
998,01t8n000000GwvOAAS,9053,16407,Lovely Professional University,BBA [2+2 with International Credit Transfer Op...,Intermediate,Years,4.0,640000.0,640000.00,640000.0,37,NaN,126144000.0,False,False,0,True,False,False
1004,01t8n000000GwxiAAC,9197,16417,Lovely Professional University,Integrated BBA - MBA,Advanced,Years,4.0,480000.0,480000.00,480000.0,37,NaN,126144000.0,False,False,0,True,False,False

Ranking non_corporate

In [12]:
non_corporate_df = non_corporate_df.sort_values(
    by=["Duration_in_seconds", "Integration", "inr_amount__c"],
    ascending=[True, False, True]
).reset_index(drop=True)

# Assign sequence rankings based on sorted order
non_corporate_df['Rank'] = 600 - (non_corporate_df.index * 0.01)
non_corporate_df

,product_sfid,product_id,mpid,course_provider_platform_name__c,product_name,course_level,duration_medium__c,course_duration__c,price__c,loan_amount__c,...,skill_id,concepts,Duration_in_seconds,Is_within_a_week,Integration,concept_count,no_concept,Udemy,ABC,Rank
0,01t8n000000JE6wAAG,10007,15551,Skill Smith,Java Booster Program Offline,Advanced,Minutes,3.0,15.0,118000.00,...,213,6107,1.800000e+02,True,False,1,False,False,False,600.00
1,01t8n000000JE6yAAG,10009,15708,Skill Smith,Angular Master Program Offline,Advanced,Minutes,3.0,5.0,118000.00,...,111,5747,1.800000e+02,True,False,1,False,False,False,599.99
2,01t8n000000JE6uAAG,10005,15553,Skill Smith,Full Stack Program (React JS and Node JS) Offline,Advanced,Minutes,6.0,15.0,1295.48,...,213,6107,3.600000e+02,True,False,1,False,False,False,599.98
3,prwea1wbu6,32056,30730,Expertrons,Business Analysis using Excel,Beginner,Minutes,18.0,20000.0,20000.00,...,259,5002,1.080000e+03,True,False,1,False,False,False,599.97
4,prom1ezo1m,32060,30734,Expertrons,Basics of LinkedIn,Beginner,Minutes,25.0,20000.0,20000.00,...,130,5812,1.500000e+03,True,False,1,False,False,False,599.96
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5119,01t8n000000GrsuAAC,6842,15579,Masters Union,Undergraduate Programme,Beginner,Years,6.0,NaN,2925000.00,...,21,5051,1.892160e+08,False,False,1,False,False,False,548.81
5120,prfwoo5mcq,27775,25999,IMI Delhi,Post Graduate Diploma in Management (Online),Advanced,Years,24.0,295000.0,295000.00,...,64,4928,7.568640e+08,False,False,1,False,False,False,548.80
5121,01t8n000000GrxEAAS,7140,17371,upGrad,MBA Leading Business Transformation,Advanced,Months,585.0,365000.0,1344753.00,...,130,6213,1.538559e+09,False,False,1,False,False,False,548.79
5122,01t8n000000GreMAAS,5940,14641,Fireblaze AI School,SQL for Data Science,Advanced,nan,NaN,NaN,2499.00,...,164,4778,NaN,False,False,1,False,False,False,548.78
5123,01t8n000000GrYbAAK,5575,16657,Edudelphi,Certified Fraud Examiner Course in India,Advanced,nan,NaN,NaN,439.32,...,256,"5400 , 5503 , 5593 , 5611 , 5645 , 5740 , 5760...",NaN,False,False,11,False,False,False,548.77

In [13]:
non_corporate_0_df = non_corporate_0_df.sort_values(
    by=["Duration_in_seconds", "Integration", "inr_amount__c"],
    ascending=[True, False, True]
).reset_index(drop=True)

# Assign sequence rankings based on sorted order
non_corporate_0_df['Rank'] = 550 - (non_corporate_0_df.index * 0.01)
non_corporate_0_df

,product_sfid,product_id,mpid,course_provider_platform_name__c,product_name,course_level,duration_medium__c,course_duration__c,price__c,loan_amount__c,...,skill_id,concepts,Duration_in_seconds,Is_within_a_week,Integration,concept_count,no_concept,Udemy,ABC,Rank
0,01t8n000000JE73AAG,10014,15544,Skill Smith,Master React Native Program Online,Advanced,Minutes,3.0,9.0,777.29,...,110,NaN,180.0,True,False,0,True,False,False,550.00
1,01t8n000000JE72AAG,10013,16508,Skill Smith,Master React Native Program Offline,Advanced,Minutes,3.0,9.0,777.29,...,110,NaN,180.0,True,False,0,True,False,False,549.99
2,01t8n000000JE6vAAG,10006,15552,Skill Smith,Full Stack Program (React JS and Node JS) Online,Advanced,Minutes,6.0,15.0,1295.48,...,104,NaN,360.0,True,False,0,True,False,False,549.98
3,pr140tds7q,21046,18972,Eduonix,Business Analytics for Beginners,Beginner,Minutes,15.0,22488.0,22488.00,...,125,NaN,900.0,True,False,0,True,False,False,549.97
4,pr4vvkrab4,31390,29946,EBC Learning,Private Equity and Venture Capital: Mastering ...,Advanced,Minutes,42.0,5900.0,5900.00,...,29,NaN,2520.0,True,False,0,True,False,False,549.96
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1442,pr3yro2h81,11180,15999,Physics Wallah,UG Course in Computer Science & Artificial Int...,Advanced,Years,4.0,1519000.0,1519000.00,...,62,NaN,126144000.0,False,False,0,True,False,False,535.58
1443,01tTZ000000gwEnYAI,10496,5887,The Design Village Easebuzz,Graphics & Communication,Beginner,Years,4.0,2200000.0,2200000.00,...,73,NaN,126144000.0,False,False,0,True,False,False,535.57
1444,01tTZ000000gwEvYAI,10504,5894,The Design Village Easebuzz,Interaction & Ux Design,Beginner,Years,4.0,2200000.0,2200000.00,...,73,NaN,126144000.0,False,False,0,True,False,False,535.56
1445,01tTZ000000gwFWYAY,10541,5922,The Design Village Easebuzz,Product Design,Beginner,Years,4.0,2200000.0,2200000.00,...,79,NaN,126144000.0,False,False,0,True,False,False,535.55
1446,01t8n000000GrstAAC,6841,16928,Masters Union,UG Programme in Tech and Business Management,Intermediate,Years,4.0,NaN,4368000.00,...,37,NaN,126144000.0,False,False,0,True,False,False,535.54

Ranking ABC

In [14]:
abc_df = abc_df.sort_values(
    by=["Duration_in_seconds", "Integration", "inr_amount__c"],
    ascending=[True, False, True]
).reset_index(drop=True)

# Assign sequence rankings based on sorted order
abc_df['Rank'] = 500 - (abc_df.index * 0.01)
abc_df

,product_sfid,product_id,mpid,course_provider_platform_name__c,product_name,course_level,duration_medium__c,course_duration__c,price__c,loan_amount__c,...,skill_id,concepts,Duration_in_seconds,Is_within_a_week,Integration,concept_count,no_concept,Udemy,ABC,Rank
0,pr6ggb6crn,13720,9169,GVC,Sharing Multiple Screens Simultaneously,Beginner,Hours,0.01,1.0,0.0,...,259,5002,36.0,True,False,1,False,False,True,500.00
1,prz439vl3r,12700,8151,GVC,Scheduling a Meeting with Outlook,Beginner,Hours,0.01,1.0,0.0,...,272,5002,36.0,True,False,1,False,False,True,499.99
2,prwjj6sgg7,13783,19765,GVC,Recognizing and Addressing Micro-behaviors in ...,Beginner,Hours,0.01,1.0,0.0,...,255,4888,36.0,True,False,1,False,False,True,499.98
3,pr0ramdk0c,13667,9117,GVC,Closed Captioning,Beginner,Hours,0.02,1.0,0.0,...,260,5002,72.0,True,False,1,False,False,True,499.97
4,prnl3tqozi,13112,8562,GVC,Sharing Your Screen,Beginner,Hours,0.02,1.0,0.0,...,285,5002,72.0,True,False,1,False,False,True,499.96
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7980,przurvq0im,22264,20214,GVC,CompTIA Linux+: SELinux & AppArmor,Intermediate,Hours,NaN,1.0,0.0,...,108,6301,NaN,False,False,1,False,False,True,420.20
7981,przvahytsh,22157,20107,GVC,Outlook 2016 (Mac): Sending & Receiving Email,Beginner,Hours,NaN,1.0,0.0,...,272,5002,NaN,False,False,1,False,False,True,420.19
7982,przyu0in9m,22779,20873,GVC,Microsoft Azure Services and Lifecycles,Beginner,Hours,NaN,1.0,0.0,...,288,5947,NaN,False,False,1,False,False,True,420.18
7983,prqqlga689,17818,14709,Gyanodaya Virtual Campus,Strategic Sourcing,Beginner,Hours,NaN,1.0,23600.0,...,341,5119,NaN,False,False,1,False,False,True,420.17
7984,pro59osu24,22748,20841,Coursera,Academic English: Writing,Beginner,Hours,NaN,1.0,0.0,...,130,6213,NaN,False,False,1,False,False,True,420.16

In [15]:
abc_0_df = abc_0_df.sort_values(
    by=["Duration_in_seconds", "Integration", "inr_amount__c"],
    ascending=[True, False, True]
).reset_index(drop=True)

# Assign sequence rankings based on sorted order
abc_0_df['Rank'] = 420 - (abc_0_df.index * 0.01)
abc_0_df

,product_sfid,product_id,mpid,course_provider_platform_name__c,product_name,course_level,duration_medium__c,course_duration__c,price__c,loan_amount__c,...,skill_id,concepts,Duration_in_seconds,Is_within_a_week,Integration,concept_count,no_concept,Udemy,ABC,Rank
0,prai5zubue,14804,14664,Coursera,Static Website Hosting and Cross-Region Replic...,Beginner,Hours,0.1,1.0,0.0,...,55,NaN,360.0,True,False,0,True,False,True,420.00
1,priofhwu49,14375,10553,Coursera,Create a Boggle Word Solver using recursion in...,Intermediate,Hours,0.1,1.0,0.0,...,67,NaN,360.0,True,False,0,True,False,True,419.99
2,prj50a1zil,16862,11768,Coursera,Fast Typer Game using Pygame,Beginner,Hours,0.1,1.0,0.0,...,53,NaN,360.0,True,False,0,True,False,True,419.98
3,prpp90zk8u,18219,14252,Coursera,Recreate the First Ever Easter Egg from Advent...,Beginner,Hours,0.1,1.0,0.0,...,313,NaN,360.0,True,False,0,True,False,True,419.97
4,prrtje596c,15301,14737,Coursera,Style Images with CSS,Intermediate,Hours,0.1,1.0,0.0,...,111,NaN,360.0,True,False,0,True,False,True,419.96
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1096,prvem1d31q,22626,20710,Coursera,Agile Development,Beginner,Hours,NaN,1.0,0.0,...,284,NaN,NaN,False,False,0,True,False,True,409.04
1097,prwbrwx3rr,22534,20612,Coursera,Google Advanced Data Analytics,Beginner,Hours,NaN,1.0,0.0,...,213,NaN,NaN,False,False,0,True,False,True,409.03
1098,prxblezp5c,22763,20857,GVC,Data Manipulation at Scale: Systems and Algori...,Beginner,Hours,NaN,1.0,0.0,...,57,NaN,NaN,False,False,0,True,False,True,409.02
1099,prxxilay2h,21520,19565,GVC,Project Scheduling: Estimate Activity Durations,Beginner,Hours,NaN,1.0,0.0,...,37,NaN,NaN,False,False,0,True,False,True,409.01
1100,przy2ytv16,21460,19450,Coursera,Database Design and Operational Business Intel...,Beginner,Hours,NaN,1.0,0.0,...,66,NaN,NaN,False,False,0,True,False,True,409.00

Ranking Udemy_courses

In [16]:
udemy_df = udemy_df.sort_values(
    by=["Duration_in_seconds", "Integration", "inr_amount__c"],
    ascending=[True, False, True]
).reset_index(drop=True)

# Assign sequence rankings based on sorted order
udemy_df['Rank'] = 400 - (udemy_df.index * 0.01)
udemy_df

,product_sfid,product_id,mpid,course_provider_platform_name__c,product_name,course_level,duration_medium__c,course_duration__c,price__c,loan_amount__c,inr_amount__c,skill_id,concepts,Duration_in_seconds,Is_within_a_week,Integration,concept_count,no_concept,Udemy,Rank
0,pr0y1ipl5c,31002,29558,Udemy,Project Management Certified Associate: CAPM P...,Intermediate,Hours,0.1,0.0,0.0,0.0,37,4590,360.0,True,False,1,False,True,400.00
1,prcdxzvedk,31166,29722,Udemy,ISO 22301Business Continuity Management (BCM &...,Beginner,Hours,0.1,0.0,0.0,0.0,40,"4586 , 5436",360.0,True,False,2,False,True,399.99
2,prgw6evcc9,31137,29693,Udemy,Project Management - Theory of Constraints way...,Beginner,Hours,0.1,0.0,0.0,0.0,37,4590,360.0,True,False,1,False,True,399.98
3,prhzt6h99t,31340,29896,Udemy,Life Insurance & Annuity Ultimate Buyers Guide,Beginner,Hours,0.1,0.0,0.0,0.0,45,4568,360.0,True,False,1,False,True,399.97
4,prr0pknjsi,31322,29878,Udemy,Digital Compliance Monitoring,Intermediate,Hours,0.1,0.0,0.0,0.0,40,4564,360.0,True,False,1,False,True,399.96
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5255,5OqCv2Pw,25043,23264,Udemy,Selenium Java : Beginner to Advanced [Live Pro...,Beginner,Minutes,11327.0,23850.0,23850.0,23850.0,103,"6817 , 6849",679620.0,False,False,2,False,True,347.45
5256,3TgEl5Xn,27077,25300,Udemy,"SAP ABAP, OOPS, CROSSAPP, WEBDYNPRO, WORKFLOW,...",Beginner,Minutes,11547.0,23850.0,23850.0,23850.0,316,6938,692820.0,False,False,1,False,True,347.44
5257,prbgu9bqhd,33590,33488,Udemy,KPI and metrics for Management Consultants & M...,Advanced,Hours,334.0,22842.0,22842.0,22842.0,63,5506,1202400.0,False,False,1,False,True,347.43
5258,prpnv1ebe6,33589,33487,Udemy,Critical Thinker Academy: Learn to Think Like ...,Intermediate,Hours,1173.0,22842.0,22842.0,22842.0,314,"5025 , 7005 , 7006 , 7007 , 7008 , 7009 , 7010...",4222800.0,False,False,10,False,True,347.42
5259,prz666dzq4,29616,28785,Udemy,ISC2 Certified in Cybersecurity (CC) Full Prac...,Beginner,Minutes,NaN,23850.0,23850.0,23850.0,130,6063,NaN,False,False,1,False,True,347.41

In [17]:
udemy_0_df = udemy_0_df.sort_values(
    by=["Duration_in_seconds", "Integration", "inr_amount__c"],
    ascending=[True, False, True]
).reset_index(drop=True)

# Assign sequence rankings based on sorted order
udemy_0_df['Rank'] = 340 - (udemy_0_df.index * 0.01)
udemy_0_df

,product_sfid,product_id,mpid,course_provider_platform_name__c,product_name,course_level,duration_medium__c,course_duration__c,price__c,loan_amount__c,inr_amount__c,skill_id,concepts,Duration_in_seconds,Is_within_a_week,Integration,concept_count,no_concept,Udemy,Rank
0,prckjmlvhq,29660,28123,Udemy,Managing a Global Team with Confidence,Beginner,Minutes,35.0,23850.0,23850.0,23850.0,255,NaN,2100.0,True,False,0,True,True,340.00
1,pr04rriz87,29480,27943,Udemy,Effective Leadership,Beginner,Minutes,49.0,23850.0,23850.0,23850.0,255,NaN,2940.0,True,False,0,True,True,339.99
2,pr9dhr23kk,29614,28077,Udemy,Developing Your Executive Leadership Skills,Intermediate,Minutes,52.0,23850.0,23850.0,23850.0,255,NaN,3120.0,True,False,0,True,True,339.98
3,pr3vmyyxgg,30260,28723,Udemy,Chaos Engineering using Azure Chaos Studio,Beginner,Minutes,74.0,23850.0,23850.0,23850.0,261,NaN,4440.0,True,False,0,True,True,339.97
4,prbg329x5m,28263,26729,Udemy,"Leadership: How to Influence, Inspire and Impa...",Beginner,Minutes,91.0,23850.0,23850.0,23850.0,255,NaN,5460.0,True,False,0,True,True,339.96
5,preelbycur,29646,28109,Udemy,Leadership - Rise of a Leader (Lead people wit...,Beginner,Minutes,91.0,23850.0,23850.0,23850.0,255,NaN,5460.0,True,False,0,True,True,339.95
6,prwkzmf60z,30271,28734,Udemy,Leadership Style: Discover & Maximize Your Lea...,Beginner,Minutes,100.0,23850.0,23850.0,23850.0,255,NaN,6000.0,True,False,0,True,True,339.94
7,prllet9osu,30939,29495,Udemy,Manage Change Through Collaboration and Team Work,Beginner,Minutes,102.0,0.0,0.0,0.0,262,NaN,6120.0,True,False,0,True,True,339.93
8,prr7lx775u,29532,27995,Udemy,Leading & Managing People [Effectively],Beginner,Minutes,119.0,23850.0,23850.0,23850.0,255,NaN,7140.0,True,False,0,True,True,339.92
9,prxcjr25z4,30054,28517,Udemy,Body Language & Nonverbal Communication in Bus...,Beginner,Minutes,125.0,23850.0,23850.0,23850.0,64,NaN,7500.0,True,False,0,True,True,339.91
10,pr4rce05qb,30210,28673,Udemy,"Ethical AI Decision Making, Insights for Leade...",Beginner,Minutes,126.0,23850.0,23850.0,23850.0,261,NaN,7560.0,True,False,0,True,True,339.90
11,prrn4jj0va,28014,26480,Udemy,"Management - Leadership, Negotiating, Assertiv...",Beginner,Minutes,128.0,23850.0,23850.0,23850.0,255,NaN,7680.0,True,False,0,True,True,339.89
12,prxp6bib17,28731,27197,Udemy,Jira Crash Course | Jira Fundamentals for Agil...,Beginner,Minutes,138.0,23850.0,23850.0,23850.0,39,NaN,8280.0,True,False,0,True,True,339.88
13,prxd7fln6n,29050,27513,Udemy,Smart Tips: Leadership,Beginner,Minutes,172.0,23850.0,23850.0,23850.0,255,NaN,10320.0,True,False,0,True,True,339.87
14,prxn9li6ss,31017,29573,Udemy,Collaboration with Emotional Intelligence,Intermediate,Minutes,184.0,0.0,0.0,0.0,262,NaN,11040.0,True,False,0,True,True,339.86
15,8ObDt0Ty,23451,21672,Udemy,Master SWOT Analysis and Business Strategy f...,Beginner,Minutes,185.0,23850.0,23850.0,23850.0,49,NaN,11100.0,True,False,0,True,True,339.85
16,pr48w18bp0,28040,26506,Udemy,Leadership: Practical Leadership Skills,Beginner,Minutes,200.0,23850.0,23850.0,23850.0,255,NaN,12000.0,True,False,0,True,True,339.84
17,prgh28omad,30150,28613,Udemy,Web Performance In Practice: Master Core Web V...,Beginner,Minutes,204.0,23850.0,23850.0,23850.0,106,NaN,12240.0,True,False,0,True,True,339.83
18,7BpKm9Gj,23448,21669,Udemy,"Master PMP Cost Management: Plan, Budget, Esti...",Beginner,Minutes,224.0,23850.0,23850.0,23850.0,261,NaN,13440.0,True,False,0,True,True,339.82
19,prtq3w17ir,29930,28393,Udemy,Product Owner II for Agile Intermediate: Certi...,Beginner,Minutes,379.0,23850.0,23850.0,23850.0,36,NaN,22740.0,True,False,0,True,True,339.81
20,5TgAx9Cg,22983,21204,Udemy,Certified Key Performance Indicators Professio...,Beginner,Minutes,448.0,23850.0,23850.0,23850.0,49,NaN,26880.0,True,False,0,True,True,339.80
21,pr9d9b50m9,28381,26847,Udemy,Informed Risk Taking : Risk Management Process...,Beginner,Minutes,532.0,23850.0,23850.0,23850.0,406,NaN,31920.0,True,False,0,True,True,339.79
22,2FeBo7Oj,25745,23967,Udemy,AWS Technical Essentials - Hands-On Training ...,Beginner,Minutes,866.0,23850.0,23850.0,23850.0,44,NaN,51960.0,True,False,0,True,True,339.78
23,pr72kec05o,27984,26450,Udemy,Lean Six Sigma Green Belt Online Course (2023),Beginner,Minutes,967.0,23850.0,23850.0,23850.0,39,NaN,58020.0,True,False,0,True,True,339.77
24,pridfixh08,29375,27838,Udemy,Enterprise Risk Management,Advanced,Minutes,1055.0,23850.0,23850.0,23850.0,21,NaN,63300.0,True,False,0,True,True,339.76
25,5YrGr8Hy,22895,21116,Udemy,Automated Cryptocurrency Portfolio Investing w...,Beginner,Minutes,1931.0,23850.0,23850.0,23850.0,261,NaN,115860.0,True,False,0,True,True,339.75
26,1FkNf0Wo,22871,21092,Udemy,ACCA MA (F2) A Complete Course on Management A...,Beginner,Minutes,2014.0,23850.0,23850.0,23850.0,49,NaN,120840.0,True,False,0,True,True,339.74
27,prv7lg5yyb,29127,27590,Udemy,Leadership & Management Skills: 2-in-1 Masterc...,Beginner,Minutes,2655.0,23850.0,23850.0,23850.0,255,NaN,159300.0,True,False,0,True,True,339.73

Concanating all the dataframe

In [18]:
pieces = {"x": non_corporate_df,"x1":non_corporate_0_df, "y": abc_df,"y1": abc_0_df, "z": udemy_df,"z1": udemy_0_df}
result = pd.concat(pieces)
result.to_excel("C:\\Users\\taslim.siddiqui\\Downloads\\Recorating24.xlsx")
print(result)

             product_sfid  product_id   mpid course_provider_platform_name__c  \
x  0   01t8n000000JE6wAAG       10007  15551                      Skill Smith
   1   01t8n000000JE6yAAG       10009  15708                      Skill Smith
   2   01t8n000000JE6uAAG       10005  15553                      Skill Smith
   3           prwea1wbu6       32056  30730                       Expertrons
   4           prom1ezo1m       32060  30734                       Expertrons
...                   ...         ...    ...                              ...
z1 23          pr72kec05o       27984  26450                            Udemy
   24          pridfixh08       29375  27838                            Udemy
   25            5YrGr8Hy       22895  21116                            Udemy
   26            1FkNf0Wo       22871  21092                            Udemy
   27          prv7lg5yyb       29127  27590                            Udemy

                                            product_name course_level  \
x  0                        Java Booster Program Offline     Advanced
   1                      Angular Master Program Offline     Advanced
   2   Full Stack Program (React JS and Node JS) Offline     Advanced
   3                       Business Analysis using Excel     Beginner
   4                                  Basics of LinkedIn     Beginner
...                                                  ...          ...
z1 23     Lean Six Sigma Green Belt Online Course (2023)     Beginner
   24                         Enterprise Risk Management     Advanced
   25  Automated Cryptocurrency Portfolio Investing w...     Beginner
   26  ACCA MA (F2) A Complete Course on Management A...     Beginner
   27  Leadership & Management Skills: 2-in-1 Masterc...     Beginner

      duration_medium__c  course_duration__c  price__c  loan_amount__c  ...  \
x  0             Minutes                 3.0      15.0       118000.00  ...
   1             Minutes                 3.0       5.0       118000.00  ...
   2             Minutes                 6.0      15.0         1295.48  ...
   3             Minutes                18.0   20000.0        20000.00  ...
   4             Minutes                25.0   20000.0        20000.00  ...
...                  ...                 ...       ...             ...  ...
z1 23            Minutes               967.0   23850.0        23850.00  ...
   24            Minutes              1055.0   23850.0        23850.00  ...
   25            Minutes              1931.0   23850.0        23850.00  ...
   26            Minutes              2014.0   23850.0        23850.00  ...
   27            Minutes              2655.0   23850.0        23850.00  ...

       skill_id  concepts Duration_in_seconds  Is_within_a_week  Integration  \
x  0        213      6107               180.0              True        False
   1        111      5747               180.0              True        False
   2        213      6107               360.0              True        False
   3        259      5002              1080.0              True        False
   4        130      5812              1500.0              True        False
...         ...       ...                 ...               ...          ...
z1 23        39       NaN             58020.0              True        False
   24        21       NaN             63300.0              True        False
   25       261       NaN            115860.0              True        False
   26        49       NaN            120840.0              True        False
   27       255       NaN            159300.0              True        False

       concept_count  no_concept  Udemy    ABC    Rank
x  0               1       False  False  False  600.00
   1               1       False  False  False  599.99
   2               1       False  False  False  599.98
   3               1       False  False  False  599.97
   4               1       False  False  False  599.96
...              ...         ...    ...    ...     ...
z1 23              0        True   True    NaN  339.77
   24              0        True   True    NaN  339.76
   25              0        True   True    NaN  339.75
   26              0        True   True    NaN  339.74
   27              0        True   True    NaN  339.73

[20945 rows x 21 columns]

testing

In [19]:
import pandas as pd

# Define the dataset
data = {
    "duration_seconds": [2000, 5890, 5739, 6746, 2000, 2000, 5890, 2000, 67383, 784892, 6474, 5890],
    "Integration": [True, True, False, True, True, True, True, True, False, True, False, False],
    "Price": [5943843, 7744, 4744, 84433, 74484, 4438, 46746, 73782, 74383, 74873, 764673, 64473]
}

# Create a DataFrame
df = pd.DataFrame(data)

# Sort by the three columns in the desired order: duration_seconds, Integration (descending), Price
df = df.sort_values(
    by=["duration_seconds", "Integration", "Price"],
    ascending=[True, False, True]
).reset_index(drop=True)

# Assign sequence rankings based on sorted order
df['Rank'] = 600 - (df.index * 0.01)

# Display the resulting DataFrame
print(df)

    duration_seconds  Integration    Price    Rank
0               2000         True     4438  600.00
1               2000         True    73782  599.99
2               2000         True    74484  599.98
3               2000         True  5943843  599.97
4               5739        False     4744  599.96
5               5890         True     7744  599.95
6               5890         True    46746  599.94
7               5890        False    64473  599.93
8               6474        False   764673  599.92
9               6746         True    84433  599.91
10             67383        False    74383  599.90
11            784892         True    74873  599.89