# FSC Deficiet

In [1]:
import pandas as pd

In [2]:
#Function,Prod Function ID,Skill,PRODUCTION Skill ID,Skill Description,Concept,Concept Description,PRODUCTION Concepts ID,Concat,product_id


#load FSC master excel
df1 = pd.read_excel(r"C:\Users\taslim.siddiqui\Downloads\Operations - FSC - ABSLI V3 5.xlsx",sheet_name='Operation FSC')
df1.head()

,Industry,Sector,Academy,Funciton id,Skill,Skill Description,PRODUCTION Skill ID,Core/Elective,Concept,Concept Description,PRODUCTION Concepts ID,Concat
0,Financial Services,Life Insurance,Operations,35,Policy Issuance Management,Manages end-to-end policy issuance activities ...,1619,Core,Issuance Readiness Validation,"Validates underwriting approvals, payment real...",17934,OperationsPolicy Issuance ManagementIssuance R...
1,Financial Services,Life Insurance,Operations,35,Policy Issuance Management,Manages end-to-end policy issuance activities ...,1619,Core,System-Based Policy Issuance,Executes accurate policy creation in core insu...,17935,OperationsPolicy Issuance ManagementSystem-Bas...
2,Financial Services,Life Insurance,Operations,35,Policy Issuance Management,Manages end-to-end policy issuance activities ...,1619,Core,Policy Document Generation,Ensures generation of compliant policy schedul...,17936,OperationsPolicy Issuance ManagementPolicy Doc...
3,Financial Services,Life Insurance,Operations,35,Policy Issuance Management,Manages end-to-end policy issuance activities ...,1619,Core,Activation & Risk Commencement,"Confirms correct risk commencement date, under...",17937,OperationsPolicy Issuance ManagementActivation...
4,Financial Services,Life Insurance,Operations,35,Policy Issuance Management,Manages end-to-end policy issuance activities ...,1619,Core,TAT Adherence Monitoring,Tracks issuance timelines against defined SLAs...,17938,OperationsPolicy Issuance ManagementTAT Adhere...

In [3]:
#product_name,course_level,skill_id,concepts,product_id
#load data file
df2 = pd.read_excel(r"C:\Users\taslim.siddiqui\Downloads\ABSLI Additional Skills and Concepts - Ops 2.xlsx")
df2

,Function,WiZR Skills,Concepts,Concept Description,course_level,Course link,Syllabus,product_id,Concat,skill_id,concepts
0,Operations,First-Line Operational Risk Identification,Risk Flagging & Logging,Flags identified operational risks in defined ...,Beginner,https://trainingcentral.co.in/portal/product/c...,Module 1: Course Objectives – Overview of Anti...,37999,OperationsFirst-Line Operational Risk Identifi...,1606,17824
1,Operations,First-Line Operational Risk Identification,Risk Impact Assessment,Assesses potential impact of identified risks ...,Beginner,https://trainingcentral.co.in/portal/product/c...,Module 1: Course Objectives – Overview of Anti...,37999,OperationsFirst-Line Operational Risk Identifi...,1606,17826
2,Operations,First-Line Operational Risk Identification,Coordination with Risk & Control Teams,"Shares risk observations with relevant risk, c...",Beginner,https://trainingcentral.co.in/portal/product/c...,Module 1: Course Objectives – Overview of Anti...,37999,OperationsFirst-Line Operational Risk Identifi...,1606,17827
3,Operations,Leadership,Ethical Leadership,"Leading with integrity, transparency, and mora...",Beginner,https://trainingcentral.co.in/portal/product/c...,Module 1: Course Objectives – Overview of Anti...,37999,OperationsLeadershipEthical Leadership,255,4888
4,Operations,Cross-Functional Coordination,SLA Alignment Across Functions,Works with other teams to maintain SLA adheren...,Intermediate,https://trainingcentral.co.in/portal/product/f...,Module 1: Course Orientation and Working Capit...,38020,OperationsCross-Functional CoordinationSLA Ali...,1611,17861
...,...,...,...,...,...,...,...,...,...,...,...
533,Operations,Customer Resolution Governance,SLA Adherence Monitoring,"Monitors SLA performance across teams (branch,...",Advanced,https://onlinejain.com/programs/masters/mba-sy...,1st Semester:<br>- Principles of Economics and...,6767,OperationsCustomer Resolution GovernanceSLA Ad...,1626,17987
534,Operations,Customer Resolution Governance,Resolution Effectiveness Review,Reviews whether the resolution actually solved...,Advanced,https://klic.mkcl.org/klic-courses/indian-mark...,Life Insurance<br>- Introduction to Life Insur...,36909,OperationsCustomer Resolution GovernanceResolu...,1626,17989
535,Operations,Branch Performance Governance,Audit Observation Tracking,"Tracks branch audit findings, maps evidence, a...",Advanced,https://actuatorseducation.com/product/sa2/,1. Life insurance products and general busines...,36089,OperationsBranch Performance GovernanceAudit O...,1629,18007
536,Operations,Branch Performance Governance,Service Quality Scorecard Review,"Maintains a service scorecard (TAT, FTR, compl...",Advanced,https://onlinejain.com/programs/masters/mba-sy...,1st Semester:<br>- Principles of Economics and...,6767,OperationsBranch Performance GovernanceService...,1629,18008
537,Operations,Case & Relationship Management,Interdepartmental SLA Monitoring,Tracks SLA dependencies across functions and e...,Advanced,https://onlinejain.com/programs/masters/mba-sy...,1st Semester:<br>- Principles of Economics and...,6767,OperationsCase & Relationship ManagementInterd...,1630,18016

If We want to remove some CPPs

In [4]:
# df2# data is the file which will only have CPP names

# # List of values to check
# values_to_check = ['Coursera','GVC','Gyanodaya Virtual Campus','CIEL','Percipio']

# # Check if any values in the DataFrame are in the list
# df2['CPP_ABC'] = df2['CPP Name'].isin(values_to_check)
# df2 = df2.query("CPP_ABC == False")
# df2

In [5]:
# Concept Column Row splitting code
df2['concepts'] = df2['concepts'].apply(
    lambda x: [int(i.strip()) for i in x.split(',')] if isinstance(x, str) else x
)

# Explode the 'concepts' column to create separate rows
df = df2.explode('concepts', ignore_index=True)
df['concepts'] = df['concepts'].fillna(0).astype(int)
df

,Function,WiZR Skills,Concepts,Concept Description,course_level,Course link,Syllabus,product_id,Concat,skill_id,concepts
0,Operations,First-Line Operational Risk Identification,Risk Flagging & Logging,Flags identified operational risks in defined ...,Beginner,https://trainingcentral.co.in/portal/product/c...,Module 1: Course Objectives – Overview of Anti...,37999,OperationsFirst-Line Operational Risk Identifi...,1606,17824
1,Operations,First-Line Operational Risk Identification,Risk Impact Assessment,Assesses potential impact of identified risks ...,Beginner,https://trainingcentral.co.in/portal/product/c...,Module 1: Course Objectives – Overview of Anti...,37999,OperationsFirst-Line Operational Risk Identifi...,1606,17826
2,Operations,First-Line Operational Risk Identification,Coordination with Risk & Control Teams,"Shares risk observations with relevant risk, c...",Beginner,https://trainingcentral.co.in/portal/product/c...,Module 1: Course Objectives – Overview of Anti...,37999,OperationsFirst-Line Operational Risk Identifi...,1606,17827
3,Operations,Leadership,Ethical Leadership,"Leading with integrity, transparency, and mora...",Beginner,https://trainingcentral.co.in/portal/product/c...,Module 1: Course Objectives – Overview of Anti...,37999,OperationsLeadershipEthical Leadership,255,4888
4,Operations,Cross-Functional Coordination,SLA Alignment Across Functions,Works with other teams to maintain SLA adheren...,Intermediate,https://trainingcentral.co.in/portal/product/f...,Module 1: Course Orientation and Working Capit...,38020,OperationsCross-Functional CoordinationSLA Ali...,1611,17861
...,...,...,...,...,...,...,...,...,...,...,...
533,Operations,Customer Resolution Governance,SLA Adherence Monitoring,"Monitors SLA performance across teams (branch,...",Advanced,https://onlinejain.com/programs/masters/mba-sy...,1st Semester:<br>- Principles of Economics and...,6767,OperationsCustomer Resolution GovernanceSLA Ad...,1626,17987
534,Operations,Customer Resolution Governance,Resolution Effectiveness Review,Reviews whether the resolution actually solved...,Advanced,https://klic.mkcl.org/klic-courses/indian-mark...,Life Insurance<br>- Introduction to Life Insur...,36909,OperationsCustomer Resolution GovernanceResolu...,1626,17989
535,Operations,Branch Performance Governance,Audit Observation Tracking,"Tracks branch audit findings, maps evidence, a...",Advanced,https://actuatorseducation.com/product/sa2/,1. Life insurance products and general busines...,36089,OperationsBranch Performance GovernanceAudit O...,1629,18007
536,Operations,Branch Performance Governance,Service Quality Scorecard Review,"Maintains a service scorecard (TAT, FTR, compl...",Advanced,https://onlinejain.com/programs/masters/mba-sy...,1st Semester:<br>- Principles of Economics and...,6767,OperationsBranch Performance GovernanceService...,1629,18008
537,Operations,Case & Relationship Management,Interdepartmental SLA Monitoring,Tracks SLA dependencies across functions and e...,Advanced,https://onlinejain.com/programs/masters/mba-sy...,1st Semester:<br>- Principles of Economics and...,6767,OperationsCase & Relationship ManagementInterd...,1630,18016

In [6]:
# Renaming Flexible to Beginner in Course level column
df['course_level'] = df['course_level'].replace('Flexible', 'Beginner')

In [7]:
df['course_level'].unique()

array(['Beginner', 'Intermediate', 'Advanced'], dtype=object)

In [8]:
# Concat of Skill Concept
#df['FSC_concat'] = df['skill_id'].astype(str)+'|'+df['concepts'].astype(str)
#df['FSC_concat'] = df['concepts'].astype(str)
df['FSC_concat'] =  df['Function'].astype(str) + '|'+  df['skill_id'].astype(str)+'|'+df['concepts'].astype(str)
df['FSC_concat']

0      Operations|1606|17824
1      Operations|1606|17826
2      Operations|1606|17827
3        Operations|255|4888
4      Operations|1611|17861
               ...
533    Operations|1626|17987
534    Operations|1626|17989
535    Operations|1629|18007
536    Operations|1629|18008
537    Operations|1630|18016
Name: FSC_concat, Length: 538, dtype: object

In [9]:
uniquedf = df.drop_duplicates(subset=['FSC_concat'])
uniquedf=uniquedf['FSC_concat']
uniquedf

0      Operations|1606|17824
1      Operations|1606|17826
2      Operations|1606|17827
3        Operations|255|4888
4      Operations|1611|17861
               ...
518    Operations|1592|17724
522    Operations|1601|17789
533    Operations|1626|17987
536    Operations|1629|18008
537    Operations|1630|18016
Name: FSC_concat, Length: 189, dtype: object

In [10]:
# Making new dataframe of Advanced course level only.
Advanced = df[df['course_level'] == 'Advanced']
Advanced

,Function,WiZR Skills,Concepts,Concept Description,course_level,Course link,Syllabus,product_id,Concat,skill_id,concepts,FSC_concat
5,Operations,Cross-Functional Coordination,Communication Loop Closure,Ensures queries and clarifications raised by f...,Advanced,https://www.eduonix.com/corporate-leadership-a...,Section 1 : Prepare your Environment<br>Welcom...,37853,OperationsCross-Functional CoordinationCommuni...,1611,17860,Operations|1611|17860
6,Operations,Leadership,Creative Leadership,Inspiring and empowering teams to think creati...,Advanced,https://www.eduonix.com/corporate-leadership-a...,Section 1 : Prepare your Environment<br>Welcom...,37853,OperationsLeadershipCreative Leadership,255,4893,Operations|255|4893
7,Operations,Leadership,Ethical Leadership,"Leading with integrity, transparency, and mora...",Advanced,https://www.eduonix.com/corporate-leadership-a...,Section 1 : Prepare your Environment<br>Welcom...,37853,OperationsLeadershipEthical Leadership,255,4888,Operations|255|4888
8,Operations,Leadership,Interpersonal Skills,Developing and honing essential leadership com...,Advanced,https://www.eduonix.com/corporate-leadership-a...,Section 1 : Prepare your Environment<br>Welcom...,37853,OperationsLeadershipInterpersonal Skills,255,4541,Operations|255|4541
9,Operations,Leadership,Leadership - Accountability,Taking responsibility for one`s actions and de...,Advanced,https://www.eduonix.com/corporate-leadership-a...,Section 1 : Prepare your Environment<br>Welcom...,37853,OperationsLeadershipLeadership - Accountability,255,5011,Operations|255|5011
...,...,...,...,...,...,...,...,...,...,...,...,...
533,Operations,Customer Resolution Governance,SLA Adherence Monitoring,"Monitors SLA performance across teams (branch,...",Advanced,https://onlinejain.com/programs/masters/mba-sy...,1st Semester:<br>- Principles of Economics and...,6767,OperationsCustomer Resolution GovernanceSLA Ad...,1626,17987,Operations|1626|17987
534,Operations,Customer Resolution Governance,Resolution Effectiveness Review,Reviews whether the resolution actually solved...,Advanced,https://klic.mkcl.org/klic-courses/indian-mark...,Life Insurance<br>- Introduction to Life Insur...,36909,OperationsCustomer Resolution GovernanceResolu...,1626,17989,Operations|1626|17989
535,Operations,Branch Performance Governance,Audit Observation Tracking,"Tracks branch audit findings, maps evidence, a...",Advanced,https://actuatorseducation.com/product/sa2/,1. Life insurance products and general busines...,36089,OperationsBranch Performance GovernanceAudit O...,1629,18007,Operations|1629|18007
536,Operations,Branch Performance Governance,Service Quality Scorecard Review,"Maintains a service scorecard (TAT, FTR, compl...",Advanced,https://onlinejain.com/programs/masters/mba-sy...,1st Semester:<br>- Principles of Economics and...,6767,OperationsBranch Performance GovernanceService...,1629,18008,Operations|1629|18008
537,Operations,Case & Relationship Management,Interdepartmental SLA Monitoring,Tracks SLA dependencies across functions and e...,Advanced,https://onlinejain.com/programs/masters/mba-sy...,1st Semester:<br>- Principles of Economics and...,6767,OperationsCase & Relationship ManagementInterd...,1630,18016,Operations|1630|18016

In [11]:
# Counting the number of courses in Advanced course level against the FSC_concat column.
result_Advanced =  Advanced.groupby("FSC_concat")["product_id"].nunique().reset_index()
result_Advanced.columns = ["FSC_concat", "Function_count_Advanced"]
result_Advanced.head()

            FSC_concat  Function_count_Advanced
0  Operations|130|4577                        2
1  Operations|130|5452                        2
2  Operations|130|5812                        2
3  Operations|130|6118                        2
4  Operations|130|6213                        2

In [12]:
Beginner = df[df['course_level'] == 'Beginner']
Beginner

,Function,WiZR Skills,Concepts,Concept Description,course_level,Course link,Syllabus,product_id,Concat,skill_id,concepts,FSC_concat
0,Operations,First-Line Operational Risk Identification,Risk Flagging & Logging,Flags identified operational risks in defined ...,Beginner,https://trainingcentral.co.in/portal/product/c...,Module 1: Course Objectives – Overview of Anti...,37999,OperationsFirst-Line Operational Risk Identifi...,1606,17824,Operations|1606|17824
1,Operations,First-Line Operational Risk Identification,Risk Impact Assessment,Assesses potential impact of identified risks ...,Beginner,https://trainingcentral.co.in/portal/product/c...,Module 1: Course Objectives – Overview of Anti...,37999,OperationsFirst-Line Operational Risk Identifi...,1606,17826,Operations|1606|17826
2,Operations,First-Line Operational Risk Identification,Coordination with Risk & Control Teams,"Shares risk observations with relevant risk, c...",Beginner,https://trainingcentral.co.in/portal/product/c...,Module 1: Course Objectives – Overview of Anti...,37999,OperationsFirst-Line Operational Risk Identifi...,1606,17827,Operations|1606|17827
3,Operations,Leadership,Ethical Leadership,"Leading with integrity, transparency, and mora...",Beginner,https://trainingcentral.co.in/portal/product/c...,Module 1: Course Objectives – Overview of Anti...,37999,OperationsLeadershipEthical Leadership,255,4888,Operations|255|4888
22,Operations,Leadership,Creative Leadership,Inspiring and empowering teams to think creati...,Beginner,https://www.eduonix.com/day-to-day-leadership-...,Section 1 : Introduction to this Course<br>Int...,37946,OperationsLeadershipCreative Leadership,255,4893,Operations|255|4893
...,...,...,...,...,...,...,...,...,...,...,...,...
470,Operations,Audit & Regulatory Readiness,Control Discipline Adherence,Ensures defined controls are executed consiste...,Beginner,https://www.smartonlinecourse.co.in/courses/On...,General Instruction and Notice Board<br>- FAQ ...,37917,OperationsAudit & Regulatory ReadinessControl ...,1615,17887,Operations|1615|17887
471,Operations,Audit & Regulatory Readiness,Evidence Availability Management,Ensures required audit evidence can be readily...,Beginner,https://www.smartonlinecourse.co.in/courses/On...,General Instruction and Notice Board<br>- FAQ ...,37917,OperationsAudit & Regulatory ReadinessEvidence...,1615,17888,Operations|1615|17888
472,Operations,Customer Experience & NPS,Experience Escalation Governance,Ensures critical complaints and high-impact ex...,Beginner,https://www.upgrad.com/hdfc-life-insurance-fun...,Introduction to the Life Insurance Industry<br...,36122,OperationsCustomer Experience & NPSExperience ...,1625,17980,Operations|1625|17980
473,Operations,Customer Resolution Governance,Escalation and Closure Tracking,Tracks escalations with clear ownership and fo...,Beginner,https://www.upgrad.com/hdfc-life-insurance-fun...,Introduction to the Life Insurance Industry<br...,36122,OperationsCustomer Resolution GovernanceEscala...,1626,17986,Operations|1626|17986
474,Operations,Branch Performance Governance,Compliance Deviation Reporting,Identifies and reports process/regulatory devi...,Beginner,https://skillfloor.com/business-analytics-spec...,Module 1: Introduction to Business Analytics i...,10894,OperationsBranch Performance GovernanceComplia...,1629,18009,Operations|1629|18009

In [13]:
result_Beginner =  Beginner.groupby("FSC_concat")["product_id"].nunique().reset_index()
result_Beginner.columns = ["FSC_concat", "Function_count_beginner"]
result_Beginner.head()

            FSC_concat  Function_count_beginner
0  Operations|130|4577                        1
1  Operations|130|5452                        2
2  Operations|130|5812                        2
3  Operations|130|6063                        1
4  Operations|130|6118                        2

In [14]:
Intermediate = df[df['course_level'] == 'Intermediate']
Intermediate.head()

,Function,WiZR Skills,Concepts,Concept Description,course_level,Course link,Syllabus,product_id,Concat,skill_id,concepts,FSC_concat
4,Operations,Cross-Functional Coordination,SLA Alignment Across Functions,Works with other teams to maintain SLA adheren...,Intermediate,https://trainingcentral.co.in/portal/product/f...,Module 1: Course Orientation and Working Capit...,38020,OperationsCross-Functional CoordinationSLA Ali...,1611,17861,Operations|1611|17861
41,Operations,Leadership,Creative Leadership,Inspiring and empowering teams to think creati...,Intermediate,https://www.smartonlinecourse.co.in/courses/Es...,Lecture 1 Transitioning from Peer to Manager<...,37309,OperationsLeadershipCreative Leadership,255,4893,Operations|255|4893
42,Operations,Leadership,Interpersonal Skills,Developing and honing essential leadership com...,Intermediate,https://www.smartonlinecourse.co.in/courses/Es...,Lecture 1 Transitioning from Peer to Manager<...,37309,OperationsLeadershipInterpersonal Skills,255,4541,Operations|255|4541
43,Operations,Leadership,Leadership - Adaptability,Demonstrating flexibility and resilience in re...,Intermediate,https://www.smartonlinecourse.co.in/courses/Es...,Lecture 1 Transitioning from Peer to Manager<...,37309,OperationsLeadershipLeadership - Adaptability,255,4976,Operations|255|4976
44,Operations,Leadership,Leadership - Empowerment,Delegating authority and decision-making power...,Intermediate,https://www.smartonlinecourse.co.in/courses/Es...,Lecture 1 Transitioning from Peer to Manager<...,37309,OperationsLeadershipLeadership - Empowerment,255,4955,Operations|255|4955

In [15]:
result_Intermediate =  Intermediate.groupby("FSC_concat")["product_id"].nunique().reset_index()
result_Intermediate.columns = ["FSC_concat", "Function_count_intermediate"]
result_Intermediate.head()

            FSC_concat  Function_count_intermediate
0  Operations|130|5452                            2
1  Operations|130|5812                            1
2  Operations|130|6063                            1
3  Operations|130|6118                            2
4  Operations|130|6213                            2

In [16]:
unique_values_df = df.drop_duplicates(subset=['FSC_concat'])
unique_values_df = unique_values_df[['FSC_concat']]
unique_values_df.head()

              FSC_concat
0  Operations|1606|17824
1  Operations|1606|17826
2  Operations|1606|17827
3    Operations|255|4888
4  Operations|1611|17861

In [17]:
merged_df = pd.merge(unique_values_df, result_Beginner, on="FSC_concat", how="left")  # Merge df1 and df2
merged_df = pd.merge(merged_df, result_Intermediate, on="FSC_concat", how="left")  # Merge with df3
merged_df = pd.merge(merged_df, result_Advanced, on="FSC_concat", how="left")
merged_df.head()

,FSC_concat,Function_count_beginner,Function_count_intermediate,Function_count_Advanced
0,Operations|1606|17824,2.0,1.0,2.0
1,Operations|1606|17826,1.0,1.0,1.0
2,Operations|1606|17827,2.0,1.0,2.0
3,Operations|255|4888,2.0,1.0,2.0
4,Operations|1611|17861,1.0,2.0,1.0

In [18]:
# If you're working with a single column but want to keep it as a DataFrame:
merged_df['Function_count_beginner'] = merged_df['Function_count_beginner'].fillna(0).astype(int)
merged_df['Function_count_intermediate'] = merged_df['Function_count_intermediate'].fillna(0).astype(int)
merged_df['Function_count_Advanced'] = merged_df['Function_count_Advanced'].fillna(0).astype(int)
merged_df.head()

,FSC_concat,Function_count_beginner,Function_count_intermediate,Function_count_Advanced
0,Operations|1606|17824,2,1,2
1,Operations|1606|17826,1,1,1
2,Operations|1606|17827,2,1,2
3,Operations|255|4888,2,1,2
4,Operations|1611|17861,1,2,1

In [19]:
#df1['Skill ID'].unique()
#df1['FSC_concat']= df1['PRODUCTION Skill ID'].fillna(0).astype(int).astype(str)+"|"+df1['PRODUCTION Concepts ID'].fillna(0).astype(int).astype(str)
#df1.head()

In [20]:
#df1['FSC_concat'] = (
    #pd.to_numeric(df1['PRODUCTION Skill ID'], errors='coerce').fillna(0).astype(int).astype(str)
    #+ "|" + pd.to_numeric(df1['PRODUCTION Concepts ID'], errors='coerce').fillna(0).astype(int).astype(str))
#df1.head()


df1['FSC_concat'] = df1['Academy'].fillna(0).astype(str) + "|" + df1['PRODUCTION Skill ID'].fillna(0).astype(int).astype(str) + "|" + (df1['PRODUCTION Concepts ID']) .fillna(0).astype(int).astype(str)
df1.head()

,Industry,Sector,Academy,Funciton id,Skill,Skill Description,PRODUCTION Skill ID,Core/Elective,Concept,Concept Description,PRODUCTION Concepts ID,Concat,FSC_concat
0,Financial Services,Life Insurance,Operations,35,Policy Issuance Management,Manages end-to-end policy issuance activities ...,1619,Core,Issuance Readiness Validation,"Validates underwriting approvals, payment real...",17934,OperationsPolicy Issuance ManagementIssuance R...,Operations|1619|17934
1,Financial Services,Life Insurance,Operations,35,Policy Issuance Management,Manages end-to-end policy issuance activities ...,1619,Core,System-Based Policy Issuance,Executes accurate policy creation in core insu...,17935,OperationsPolicy Issuance ManagementSystem-Bas...,Operations|1619|17935
2,Financial Services,Life Insurance,Operations,35,Policy Issuance Management,Manages end-to-end policy issuance activities ...,1619,Core,Policy Document Generation,Ensures generation of compliant policy schedul...,17936,OperationsPolicy Issuance ManagementPolicy Doc...,Operations|1619|17936
3,Financial Services,Life Insurance,Operations,35,Policy Issuance Management,Manages end-to-end policy issuance activities ...,1619,Core,Activation & Risk Commencement,"Confirms correct risk commencement date, under...",17937,OperationsPolicy Issuance ManagementActivation...,Operations|1619|17937
4,Financial Services,Life Insurance,Operations,35,Policy Issuance Management,Manages end-to-end policy issuance activities ...,1619,Core,TAT Adherence Monitoring,Tracks issuance timelines against defined SLAs...,17938,OperationsPolicy Issuance ManagementTAT Adhere...,Operations|1619|17938

In [21]:
automated_df = pd.merge(df1,merged_df, on ='FSC_concat', how = 'left' )
automated_df['Function_count_beginner'] = automated_df['Function_count_beginner'].fillna(0).astype(int)
automated_df['Function_count_intermediate'] = automated_df['Function_count_intermediate'].fillna(0).astype(int)
automated_df['Function_count_Advanced'] = automated_df['Function_count_Advanced'].fillna(0).astype(int)
automated_df.head()

,Industry,Sector,Academy,Funciton id,Skill,Skill Description,PRODUCTION Skill ID,Core/Elective,Concept,Concept Description,PRODUCTION Concepts ID,Concat,FSC_concat,Function_count_beginner,Function_count_intermediate,Function_count_Advanced
0,Financial Services,Life Insurance,Operations,35,Policy Issuance Management,Manages end-to-end policy issuance activities ...,1619,Core,Issuance Readiness Validation,"Validates underwriting approvals, payment real...",17934,OperationsPolicy Issuance ManagementIssuance R...,Operations|1619|17934,1,1,0
1,Financial Services,Life Insurance,Operations,35,Policy Issuance Management,Manages end-to-end policy issuance activities ...,1619,Core,System-Based Policy Issuance,Executes accurate policy creation in core insu...,17935,OperationsPolicy Issuance ManagementSystem-Bas...,Operations|1619|17935,0,1,0
2,Financial Services,Life Insurance,Operations,35,Policy Issuance Management,Manages end-to-end policy issuance activities ...,1619,Core,Policy Document Generation,Ensures generation of compliant policy schedul...,17936,OperationsPolicy Issuance ManagementPolicy Doc...,Operations|1619|17936,1,0,0
3,Financial Services,Life Insurance,Operations,35,Policy Issuance Management,Manages end-to-end policy issuance activities ...,1619,Core,Activation & Risk Commencement,"Confirms correct risk commencement date, under...",17937,OperationsPolicy Issuance ManagementActivation...,Operations|1619|17937,1,1,1
4,Financial Services,Life Insurance,Operations,35,Policy Issuance Management,Manages end-to-end policy issuance activities ...,1619,Core,TAT Adherence Monitoring,Tracks issuance timelines against defined SLAs...,17938,OperationsPolicy Issuance ManagementTAT Adhere...,Operations|1619|17938,0,0,1

In [22]:
automated_df.to_excel("C:\\Users\\taslim.siddiqui\\Downloads//automate_FSC_deficit_ABSLI__updated_26-03-2026.xlsx")