# FSC Deficiet

In [1]:
import pandas as pd

In [2]:
#Function,Prod Function ID,Skill,PRODUCTION Skill ID,Skill Description,Concept,Concept Description,PRODUCTION Concepts ID,Concat,product_id


#load FSC master excel
df1 = pd.read_excel(r"C:\Users\taslim.siddiqui\Downloads\KOTAK Course + Deficit Tracker_Data added (4).xlsx",sheet_name='Kotak FSC Master')
df1.head()

,Academy,Prod Function ID,Skill,PRODUCTION Skill ID,Skill Description,Concept,Concept Description,PRODUCTION Concepts ID,Concat
0,Assurance - Audit,87,Audit Automation Tools and Techniques,1230,Master Audit Automation to streamline processe...,Audit Management Software,"Experience with tools such as TeamMate, Metric...",7014,Assurance - AuditAudit Automation Tools and Te...
1,Assurance - Audit,87,Audit Automation Tools and Techniques,1230,Master Audit Automation to streamline processe...,Continuous Auditing,"Leveraging technology to perform ongoing, real...",7015,Assurance - AuditAudit Automation Tools and Te...
2,Assurance - Audit,87,Audit Automation Tools and Techniques,1230,Master Audit Automation to streamline processe...,Automated Evidence Capture,Using automation scripts to collect audit evid...,15339,Assurance - AuditAudit Automation Tools and Te...
3,Assurance - Audit,87,Audit Automation Tools and Techniques,1230,Master Audit Automation to streamline processe...,Real-time Control Dashboards,Providing live visibility into automated contr...,15340,Assurance - AuditAudit Automation Tools and Te...
4,Assurance - Audit,87,Audit Automation Tools and Techniques,1230,Master Audit Automation to streamline processe...,Exception Auto-Triage,Automatically categorizing exceptions based on...,15341,Assurance - AuditAudit Automation Tools and Te...

In [3]:
#product_name,course_level,skill_id,concepts,product_id
#load data file
df2 = pd.read_excel(r"C:\Users\taslim.siddiqui\Downloads\KOTAK Course + Deficit Tracker_Data added (4).xlsx",sheet_name='HH+Other CPP Master')
df2

,Course Name,Function,Skill,Concept,course_level,Course link,CPP,Course Sylabus,product_id,Prod MP ID,...,skill_id,concepts,Corporate id,Course Learning mode,Duration,Duration_c,Price,Function 2,Client ID,Unnamed: 20
0,Management Consulting Masterclass,Assurance - Audit,Stakeholder Relationship Management,Customer Lifecycle Review,Beginner,https://www.thinkingbridge.in/courses/Manageme...,Thinking Bridge,Session 1 - 1.5 Hrs<br>Fundamentals of Managem...,37824,38948,...,1191,14777,[9],Self-paced (Recorded),20.00,Hours,2999.0,Assurance - Audit,694662d4de84b15b52c5d89a,NaN
1,Management Consulting Masterclass,Assurance - Audit,Data Analytics & Insight Generation,Analytics Tool Utilisation,Beginner,https://www.thinkingbridge.in/courses/Manageme...,Thinking Bridge,Session 1 - 1.5 Hrs<br>Fundamentals of Managem...,37824,38948,...,1193,14796,[9],Self-paced (Recorded),20.00,Hours,2999.0,Assurance - Audit,694662d4de84b15b52c5d89a,NaN
2,Management Consulting Masterclass,Assurance - Audit,Business Intelligence,Business Analytics Strategy,Beginner,https://www.thinkingbridge.in/courses/Manageme...,Thinking Bridge,Session 1 - 1.5 Hrs<br>Fundamentals of Managem...,37824,38948,...,1237,5652,[9],Self-paced (Recorded),20.00,Hours,2999.0,Assurance - Audit,694662d4de84b15b52c5d89a,NaN
3,Management Consulting Masterclass,Assurance - Audit,Business Intelligence,Data Analysis and Interpretation,Beginner,https://www.thinkingbridge.in/courses/Manageme...,Thinking Bridge,Session 1 - 1.5 Hrs<br>Fundamentals of Managem...,37824,38948,...,1237,5730,[9],Self-paced (Recorded),20.00,Hours,2999.0,Assurance - Audit,694662d4de84b15b52c5d89a,NaN
4,IND AS and IFRS Masterclass,Assurance - Audit,Financial Reporting & Ind AS Compliance,Lease Accounting (Ind AS 116),Advanced,https://www.thinkingbridge.in/courses/IND-AS--...,Thinking Bridge,Session 1 -<br>1.5 Hrs<br>IND AS & IFRS Master...,37822,38945,...,1188,14740,[9],Self-paced (Recorded),20.00,Hours,2999.0,Assurance - Audit,694670832521a451290ad559,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7694,"Executive Program in Fintech, Banking, and App...",RM-Wholesale Business - Wholesale Banking,Operational Discipline & MIS,Continuous Process Improvement,Advanced,https://www.henryharvin.com/executive-program-...,Henry Harvin,Module 1: Overview of Risk Management in Banki...,6070,1746,...,1382,16035,[9],Self-paced (Recorded),192.00,Hours,42275.0,RM-Wholesale Business - Wholesale Banking,FINTECH-BANKING,5.01
7695,Online Certificate Course in Enterprise Risk M...,RM-Wholesale Business - Wholesale Banking,Negotiation & Commercial Selling,Trade-Off Management,Advanced,https://www.smartonlinecourse.co.in/courses/On...,Smart Online Course,"Introduction to ERM:<br>What Makes a Risk ""Ent...",36116,36981,...,1384,16045,[9],Self-paced (Recorded),5.00,Hours,4200.0,RM-Wholesale Business - Wholesale Banking,694e8282f4334e63e303b84f,5.01
7696,Corporate Leadership and People Management,RM-Wholesale Business - Wholesale Banking,Negotiation & Commercial Selling,Win-Win Orientation,Advanced,https://www.eduonix.com/corporate-leadership-a...,Eduonix learning Solutions,Section 1 : Prepare your Environment<br>Welcom...,37853,38982,...,1384,16047,[9],Self-paced (Recorded),1.13,Hours,2348.2,RM-Wholesale Business - Wholesale Banking,13047,5.01
7697,"Executive Program in Fintech, Banking, and App...",RM-Wholesale Business - Wholesale Banking,Negotiation & Commercial Selling,Commercial Awareness,Advanced,https://www.henryharvin.com/executive-program-...,Henry Harvin,Module 1: Overview of Risk Management in Banki...,6070,1746,...,1384,16048,[9],Self-paced (Recorded),192.00,Hours,42275.0,RM-Wholesale Business - Wholesale Banking,FINTECH-BANKING,5.01
7698,"Executive Program in Fintech, Banking, and App...",RM-Wholesale Business - Wholesale Banking,Negotiation & Commercial Selling,Ethical Negotiation,Advanced,https://www.henryharvin.com/executive-program-...,Henry Harvin,Module 1: Overview of Risk Management in Banki...,6070,1746,...,1384,16049,[9],Self-paced (Recorded),192.00,Hours,42275.0,RM-Wholesale Business - Wholesale Banking,FINTECH-BANKING,5.01

In [4]:
df1['PRODUCTION Concepts ID'].value_counts()

PRODUCTION Concepts ID
16043    6
15951    6
15960    6
15961    6
15962    6
        ..
15527    1
15526    1
15525    1
15524    1
16147    1
Name: count, Length: 1963, dtype: int64

If We want to remove some CPPs

In [5]:
# df2# data is the file which will only have CPP names

# # List of values to check
# values_to_check = ['Coursera','GVC','Gyanodaya Virtual Campus','CIEL','Percipio']

# # Check if any values in the DataFrame are in the list
# df2['CPP_ABC'] = df2['CPP Name'].isin(values_to_check)
# df2 = df2.query("CPP_ABC == False")
# df2

In [6]:
# Concept Column Row splitting code
df2['concepts'] = df2['concepts'].apply(
    lambda x: [int(i.strip()) for i in x.split(',')] if isinstance(x, str) else x
)

# Explode the 'concepts' column to create separate rows
df = df2.explode('concepts', ignore_index=True)
df['concepts'] = df['concepts'].fillna(0).astype(int)


df

,Course Name,Function,Skill,Concept,course_level,Course link,CPP,Course Sylabus,product_id,Prod MP ID,...,skill_id,concepts,Corporate id,Course Learning mode,Duration,Duration_c,Price,Function 2,Client ID,Unnamed: 20
0,Management Consulting Masterclass,Assurance - Audit,Stakeholder Relationship Management,Customer Lifecycle Review,Beginner,https://www.thinkingbridge.in/courses/Manageme...,Thinking Bridge,Session 1 - 1.5 Hrs<br>Fundamentals of Managem...,37824,38948,...,1191,14777,[9],Self-paced (Recorded),20.00,Hours,2999.0,Assurance - Audit,694662d4de84b15b52c5d89a,NaN
1,Management Consulting Masterclass,Assurance - Audit,Data Analytics & Insight Generation,Analytics Tool Utilisation,Beginner,https://www.thinkingbridge.in/courses/Manageme...,Thinking Bridge,Session 1 - 1.5 Hrs<br>Fundamentals of Managem...,37824,38948,...,1193,14796,[9],Self-paced (Recorded),20.00,Hours,2999.0,Assurance - Audit,694662d4de84b15b52c5d89a,NaN
2,Management Consulting Masterclass,Assurance - Audit,Business Intelligence,Business Analytics Strategy,Beginner,https://www.thinkingbridge.in/courses/Manageme...,Thinking Bridge,Session 1 - 1.5 Hrs<br>Fundamentals of Managem...,37824,38948,...,1237,5652,[9],Self-paced (Recorded),20.00,Hours,2999.0,Assurance - Audit,694662d4de84b15b52c5d89a,NaN
3,Management Consulting Masterclass,Assurance - Audit,Business Intelligence,Data Analysis and Interpretation,Beginner,https://www.thinkingbridge.in/courses/Manageme...,Thinking Bridge,Session 1 - 1.5 Hrs<br>Fundamentals of Managem...,37824,38948,...,1237,5730,[9],Self-paced (Recorded),20.00,Hours,2999.0,Assurance - Audit,694662d4de84b15b52c5d89a,NaN
4,IND AS and IFRS Masterclass,Assurance - Audit,Financial Reporting & Ind AS Compliance,Lease Accounting (Ind AS 116),Advanced,https://www.thinkingbridge.in/courses/IND-AS--...,Thinking Bridge,Session 1 -<br>1.5 Hrs<br>IND AS & IFRS Master...,37822,38945,...,1188,14740,[9],Self-paced (Recorded),20.00,Hours,2999.0,Assurance - Audit,694670832521a451290ad559,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7694,"Executive Program in Fintech, Banking, and App...",RM-Wholesale Business - Wholesale Banking,Operational Discipline & MIS,Continuous Process Improvement,Advanced,https://www.henryharvin.com/executive-program-...,Henry Harvin,Module 1: Overview of Risk Management in Banki...,6070,1746,...,1382,16035,[9],Self-paced (Recorded),192.00,Hours,42275.0,RM-Wholesale Business - Wholesale Banking,FINTECH-BANKING,5.01
7695,Online Certificate Course in Enterprise Risk M...,RM-Wholesale Business - Wholesale Banking,Negotiation & Commercial Selling,Trade-Off Management,Advanced,https://www.smartonlinecourse.co.in/courses/On...,Smart Online Course,"Introduction to ERM:<br>What Makes a Risk ""Ent...",36116,36981,...,1384,16045,[9],Self-paced (Recorded),5.00,Hours,4200.0,RM-Wholesale Business - Wholesale Banking,694e8282f4334e63e303b84f,5.01
7696,Corporate Leadership and People Management,RM-Wholesale Business - Wholesale Banking,Negotiation & Commercial Selling,Win-Win Orientation,Advanced,https://www.eduonix.com/corporate-leadership-a...,Eduonix learning Solutions,Section 1 : Prepare your Environment<br>Welcom...,37853,38982,...,1384,16047,[9],Self-paced (Recorded),1.13,Hours,2348.2,RM-Wholesale Business - Wholesale Banking,13047,5.01
7697,"Executive Program in Fintech, Banking, and App...",RM-Wholesale Business - Wholesale Banking,Negotiation & Commercial Selling,Commercial Awareness,Advanced,https://www.henryharvin.com/executive-program-...,Henry Harvin,Module 1: Overview of Risk Management in Banki...,6070,1746,...,1384,16048,[9],Self-paced (Recorded),192.00,Hours,42275.0,RM-Wholesale Business - Wholesale Banking,FINTECH-BANKING,5.01
7698,"Executive Program in Fintech, Banking, and App...",RM-Wholesale Business - Wholesale Banking,Negotiation & Commercial Selling,Ethical Negotiation,Advanced,https://www.henryharvin.com/executive-program-...,Henry Harvin,Module 1: Overview of Risk Management in Banki...,6070,1746,...,1384,16049,[9],Self-paced (Recorded),192.00,Hours,42275.0,RM-Wholesale Business - Wholesale Banking,FINTECH-BANKING,5.01

In [7]:
# Concept Column Row splitting code
df2['concepts'] = df2['concepts'].apply(
    lambda x: [int(i.strip()) for i in x.split(',')] if isinstance(x, str) else x
)

# Explode the 'concepts' column to create separate rows
df = df2.explode('concepts', ignore_index=True)
df['concepts'] = df['concepts'].fillna(0).astype(int)


df

,Course Name,Function,Skill,Concept,course_level,Course link,CPP,Course Sylabus,product_id,Prod MP ID,...,skill_id,concepts,Corporate id,Course Learning mode,Duration,Duration_c,Price,Function 2,Client ID,Unnamed: 20
0,Management Consulting Masterclass,Assurance - Audit,Stakeholder Relationship Management,Customer Lifecycle Review,Beginner,https://www.thinkingbridge.in/courses/Manageme...,Thinking Bridge,Session 1 - 1.5 Hrs<br>Fundamentals of Managem...,37824,38948,...,1191,14777,[9],Self-paced (Recorded),20.00,Hours,2999.0,Assurance - Audit,694662d4de84b15b52c5d89a,NaN
1,Management Consulting Masterclass,Assurance - Audit,Data Analytics & Insight Generation,Analytics Tool Utilisation,Beginner,https://www.thinkingbridge.in/courses/Manageme...,Thinking Bridge,Session 1 - 1.5 Hrs<br>Fundamentals of Managem...,37824,38948,...,1193,14796,[9],Self-paced (Recorded),20.00,Hours,2999.0,Assurance - Audit,694662d4de84b15b52c5d89a,NaN
2,Management Consulting Masterclass,Assurance - Audit,Business Intelligence,Business Analytics Strategy,Beginner,https://www.thinkingbridge.in/courses/Manageme...,Thinking Bridge,Session 1 - 1.5 Hrs<br>Fundamentals of Managem...,37824,38948,...,1237,5652,[9],Self-paced (Recorded),20.00,Hours,2999.0,Assurance - Audit,694662d4de84b15b52c5d89a,NaN
3,Management Consulting Masterclass,Assurance - Audit,Business Intelligence,Data Analysis and Interpretation,Beginner,https://www.thinkingbridge.in/courses/Manageme...,Thinking Bridge,Session 1 - 1.5 Hrs<br>Fundamentals of Managem...,37824,38948,...,1237,5730,[9],Self-paced (Recorded),20.00,Hours,2999.0,Assurance - Audit,694662d4de84b15b52c5d89a,NaN
4,IND AS and IFRS Masterclass,Assurance - Audit,Financial Reporting & Ind AS Compliance,Lease Accounting (Ind AS 116),Advanced,https://www.thinkingbridge.in/courses/IND-AS--...,Thinking Bridge,Session 1 -<br>1.5 Hrs<br>IND AS & IFRS Master...,37822,38945,...,1188,14740,[9],Self-paced (Recorded),20.00,Hours,2999.0,Assurance - Audit,694670832521a451290ad559,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7694,"Executive Program in Fintech, Banking, and App...",RM-Wholesale Business - Wholesale Banking,Operational Discipline & MIS,Continuous Process Improvement,Advanced,https://www.henryharvin.com/executive-program-...,Henry Harvin,Module 1: Overview of Risk Management in Banki...,6070,1746,...,1382,16035,[9],Self-paced (Recorded),192.00,Hours,42275.0,RM-Wholesale Business - Wholesale Banking,FINTECH-BANKING,5.01
7695,Online Certificate Course in Enterprise Risk M...,RM-Wholesale Business - Wholesale Banking,Negotiation & Commercial Selling,Trade-Off Management,Advanced,https://www.smartonlinecourse.co.in/courses/On...,Smart Online Course,"Introduction to ERM:<br>What Makes a Risk ""Ent...",36116,36981,...,1384,16045,[9],Self-paced (Recorded),5.00,Hours,4200.0,RM-Wholesale Business - Wholesale Banking,694e8282f4334e63e303b84f,5.01
7696,Corporate Leadership and People Management,RM-Wholesale Business - Wholesale Banking,Negotiation & Commercial Selling,Win-Win Orientation,Advanced,https://www.eduonix.com/corporate-leadership-a...,Eduonix learning Solutions,Section 1 : Prepare your Environment<br>Welcom...,37853,38982,...,1384,16047,[9],Self-paced (Recorded),1.13,Hours,2348.2,RM-Wholesale Business - Wholesale Banking,13047,5.01
7697,"Executive Program in Fintech, Banking, and App...",RM-Wholesale Business - Wholesale Banking,Negotiation & Commercial Selling,Commercial Awareness,Advanced,https://www.henryharvin.com/executive-program-...,Henry Harvin,Module 1: Overview of Risk Management in Banki...,6070,1746,...,1384,16048,[9],Self-paced (Recorded),192.00,Hours,42275.0,RM-Wholesale Business - Wholesale Banking,FINTECH-BANKING,5.01
7698,"Executive Program in Fintech, Banking, and App...",RM-Wholesale Business - Wholesale Banking,Negotiation & Commercial Selling,Ethical Negotiation,Advanced,https://www.henryharvin.com/executive-program-...,Henry Harvin,Module 1: Overview of Risk Management in Banki...,6070,1746,...,1384,16049,[9],Self-paced (Recorded),192.00,Hours,42275.0,RM-Wholesale Business - Wholesale Banking,FINTECH-BANKING,5.01

In [8]:
# Renaming Flexible to Beginner in Course level column
df['course_level'] = df['course_level'].replace('Flexible', 'Beginner')

In [9]:
df['course_level'].unique()

array(['Beginner', 'Advanced', 'Intermediate'], dtype=object)

In [10]:
# Concat of Skill Concept
#df['FSC_concat'] = df['skill_id'].astype(str)+'|'+df['concepts'].astype(str)
#df['FSC_concat'] = df['concepts'].astype(str)
df['FSC_concat'] =  df['Function'].astype(str) + '|'+  df['skill_id'].astype(str)+'|'+df['concepts'].astype(str)
df['FSC_concat']

0                            Assurance - Audit|1191|14777
1                            Assurance - Audit|1193|14796
2                             Assurance - Audit|1237|5652
3                             Assurance - Audit|1237|5730
4                            Assurance - Audit|1188|14740
                              ...
7694    RM-Wholesale Business - Wholesale Banking|1382...
7695    RM-Wholesale Business - Wholesale Banking|1384...
7696    RM-Wholesale Business - Wholesale Banking|1384...
7697    RM-Wholesale Business - Wholesale Banking|1384...
7698    RM-Wholesale Business - Wholesale Banking|1384...
Name: FSC_concat, Length: 7699, dtype: object

In [11]:
uniquedf = df.drop_duplicates(subset=['FSC_concat'])
uniquedf=uniquedf['FSC_concat']
uniquedf

0                    Assurance - Audit|1191|14777
1                    Assurance - Audit|1193|14796
2                     Assurance - Audit|1237|5652
3                     Assurance - Audit|1237|5730
4                    Assurance - Audit|1188|14740
                          ...
7237        RM-Consumer Bank - Product|1441|16443
7271    RM-Consumer Bank - Proposition|1455|16544
7273    RM-Consumer Bank - Proposition|1456|16552
7281    RM-Consumer Bank - Proposition|1458|16567
7398            RM-Consumer Bank - 811|1419|16290
Name: FSC_concat, Length: 2477, dtype: object

In [12]:
# Making new dataframe of Advanced course level only.
Advanced = df[df['course_level'] == 'Advanced']
Advanced

,Course Name,Function,Skill,Concept,course_level,Course link,CPP,Course Sylabus,product_id,Prod MP ID,...,concepts,Corporate id,Course Learning mode,Duration,Duration_c,Price,Function 2,Client ID,Unnamed: 20,FSC_concat
4,IND AS and IFRS Masterclass,Assurance - Audit,Financial Reporting & Ind AS Compliance,Lease Accounting (Ind AS 116),Advanced,https://www.thinkingbridge.in/courses/IND-AS--...,Thinking Bridge,Session 1 -<br>1.5 Hrs<br>IND AS & IFRS Master...,37822,38945,...,14740,[9],Self-paced (Recorded),20.00,Hours,2999.0,Assurance - Audit,694670832521a451290ad559,NaN,Assurance - Audit|1188|14740
5,IND AS and IFRS Masterclass,Assurance - Audit,Financial Reporting & Ind AS Compliance,Acquisition Accounting,Advanced,https://www.thinkingbridge.in/courses/IND-AS--...,Thinking Bridge,Session 1 -<br>1.5 Hrs<br>IND AS & IFRS Master...,37822,38945,...,14741,[9],Self-paced (Recorded),20.00,Hours,2999.0,Assurance - Audit,694670832521a451290ad559,NaN,Assurance - Audit|1188|14741
6,IND AS and IFRS Masterclass,Assurance - Audit,Financial Reporting & Ind AS Compliance,Joint Operation Accounting,Advanced,https://www.thinkingbridge.in/courses/IND-AS--...,Thinking Bridge,Session 1 -<br>1.5 Hrs<br>IND AS & IFRS Master...,37822,38945,...,14742,[9],Self-paced (Recorded),20.00,Hours,2999.0,Assurance - Audit,694670832521a451290ad559,NaN,Assurance - Audit|1188|14742
7,IND AS and IFRS Masterclass,Assurance - Audit,Financial Reporting & Ind AS Compliance,Ind AS 8 Policies,Advanced,https://www.thinkingbridge.in/courses/IND-AS--...,Thinking Bridge,Session 1 -<br>1.5 Hrs<br>IND AS & IFRS Master...,37822,38945,...,14743,[9],Self-paced (Recorded),20.00,Hours,2999.0,Assurance - Audit,694670832521a451290ad559,NaN,Assurance - Audit|1188|14743
8,IND AS and IFRS Masterclass,Assurance - Audit,Financial Reporting & Ind AS Compliance,Cash-Settled Awards,Advanced,https://www.thinkingbridge.in/courses/IND-AS--...,Thinking Bridge,Session 1 -<br>1.5 Hrs<br>IND AS & IFRS Master...,37822,38945,...,14745,[9],Self-paced (Recorded),20.00,Hours,2999.0,Assurance - Audit,694670832521a451290ad559,NaN,Assurance - Audit|1188|14745
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7694,"Executive Program in Fintech, Banking, and App...",RM-Wholesale Business - Wholesale Banking,Operational Discipline & MIS,Continuous Process Improvement,Advanced,https://www.henryharvin.com/executive-program-...,Henry Harvin,Module 1: Overview of Risk Management in Banki...,6070,1746,...,16035,[9],Self-paced (Recorded),192.00,Hours,42275.0,RM-Wholesale Business - Wholesale Banking,FINTECH-BANKING,5.01,RM-Wholesale Business - Wholesale Banking|1382...
7695,Online Certificate Course in Enterprise Risk M...,RM-Wholesale Business - Wholesale Banking,Negotiation & Commercial Selling,Trade-Off Management,Advanced,https://www.smartonlinecourse.co.in/courses/On...,Smart Online Course,"Introduction to ERM:<br>What Makes a Risk ""Ent...",36116,36981,...,16045,[9],Self-paced (Recorded),5.00,Hours,4200.0,RM-Wholesale Business - Wholesale Banking,694e8282f4334e63e303b84f,5.01,RM-Wholesale Business - Wholesale Banking|1384...
7696,Corporate Leadership and People Management,RM-Wholesale Business - Wholesale Banking,Negotiation & Commercial Selling,Win-Win Orientation,Advanced,https://www.eduonix.com/corporate-leadership-a...,Eduonix learning Solutions,Section 1 : Prepare your Environment<br>Welcom...,37853,38982,...,16047,[9],Self-paced (Recorded),1.13,Hours,2348.2,RM-Wholesale Business - Wholesale Banking,13047,5.01,RM-Wholesale Business - Wholesale Banking|1384...
7697,"Executive Program in Fintech, Banking, and App...",RM-Wholesale Business - Wholesale Banking,Negotiation & Commercial Selling,Commercial Awareness,Advanced,https://www.henryharvin.com/executive-program-...,Henry Harvin,Module 1: Overview of Risk Management in Banki...,6070,1746,...,16048,[9],Self-paced (Recorded),192.00,Hours,42275.0,RM-Wholesale Business - Wholesale Banking,FINTECH-BANKING,5.01,RM-Wholesale Business - Wholesale Banking|1384...
7698,"Executive Program in Fintech, Banking, and App...",RM-Wholesale Business - Wholesale Banking,Negotiation & Commercial Selling,Ethical Negotiation,Advanced,https://www.henryharvin.com/executive-program-...,Henry Harvin,Module 1: Overview of Risk Management in Banki...,6070,1746,...,16049,[9],Self-paced (Recorded),192.00,Hours,42275.0,RM-Wholesale Business - Wholesale Banking,FINTECH-BANKING,5.01,RM-Wholesale Business - Wholesale Banking|1384...

In [13]:
# Counting the number of courses in Advanced course level against the FSC_concat column.
result_Advanced =  Advanced.groupby("FSC_concat")["product_id"].nunique().reset_index()
result_Advanced.columns = ["FSC_concat", "Function_count_Advanced"]
result_Advanced.head()

                     FSC_concat  Function_count_Advanced
0  Assurance - Audit|1188|14739                        1
1  Assurance - Audit|1188|14740                        2
2  Assurance - Audit|1188|14741                        1
3  Assurance - Audit|1188|14742                        1
4  Assurance - Audit|1188|14743                        2

In [14]:
Beginner = df[df['course_level'] == 'Beginner']
Beginner

,Course Name,Function,Skill,Concept,course_level,Course link,CPP,Course Sylabus,product_id,Prod MP ID,...,concepts,Corporate id,Course Learning mode,Duration,Duration_c,Price,Function 2,Client ID,Unnamed: 20,FSC_concat
0,Management Consulting Masterclass,Assurance - Audit,Stakeholder Relationship Management,Customer Lifecycle Review,Beginner,https://www.thinkingbridge.in/courses/Manageme...,Thinking Bridge,Session 1 - 1.5 Hrs<br>Fundamentals of Managem...,37824,38948,...,14777,[9],Self-paced (Recorded),20.0,Hours,2999.0,Assurance - Audit,694662d4de84b15b52c5d89a,NaN,Assurance - Audit|1191|14777
1,Management Consulting Masterclass,Assurance - Audit,Data Analytics & Insight Generation,Analytics Tool Utilisation,Beginner,https://www.thinkingbridge.in/courses/Manageme...,Thinking Bridge,Session 1 - 1.5 Hrs<br>Fundamentals of Managem...,37824,38948,...,14796,[9],Self-paced (Recorded),20.0,Hours,2999.0,Assurance - Audit,694662d4de84b15b52c5d89a,NaN,Assurance - Audit|1193|14796
2,Management Consulting Masterclass,Assurance - Audit,Business Intelligence,Business Analytics Strategy,Beginner,https://www.thinkingbridge.in/courses/Manageme...,Thinking Bridge,Session 1 - 1.5 Hrs<br>Fundamentals of Managem...,37824,38948,...,5652,[9],Self-paced (Recorded),20.0,Hours,2999.0,Assurance - Audit,694662d4de84b15b52c5d89a,NaN,Assurance - Audit|1237|5652
3,Management Consulting Masterclass,Assurance - Audit,Business Intelligence,Data Analysis and Interpretation,Beginner,https://www.thinkingbridge.in/courses/Manageme...,Thinking Bridge,Session 1 - 1.5 Hrs<br>Fundamentals of Managem...,37824,38948,...,5730,[9],Self-paced (Recorded),20.0,Hours,2999.0,Assurance - Audit,694662d4de84b15b52c5d89a,NaN,Assurance - Audit|1237|5730
19,Big 4 Masterclass,Assurance - Audit,Risk-Based Audit Methodology,Data-Driven Audit Methods,Beginner,https://www.thinkingbridge.in/courses/Big-4-Ma...,Thinking Bridge,Session 1 - 0.5 Hrs<br>Introductory Session - ...,37834,38950,...,14752,[9],Self-paced (Recorded),25.0,Hours,10000.0,Assurance - Audit,688cd0427eccb75ab122cc55,NaN,Assurance - Audit|1189|14752
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7150,Post Graduate Program in Supply Chain Management,RM-Wholesale Business - Wholesale Banking,Supply Chain Finance Solutions,Vendor Financing,Beginner,https://www.henryharvin.com/post-graduate-prog...,Henry Harvin,Module 1: Modelling & Analytics Tools<br>-Basi...,6272,1943,...,16128,[9],Self-paced (Recorded),140.0,Hours,189500.0,RM-Wholesale Business - Wholesale Banking,pg-supply-chain,3.01,RM-Wholesale Business - Wholesale Banking|1396...
7151,Post Graduate Program in Supply Chain Management,RM-Wholesale Business - Wholesale Banking,Supply Chain Finance Solutions,Buyer Financing,Beginner,https://www.henryharvin.com/post-graduate-prog...,Henry Harvin,Module 1: Modelling & Analytics Tools<br>-Basi...,6272,1943,...,16129,[9],Self-paced (Recorded),140.0,Hours,189500.0,RM-Wholesale Business - Wholesale Banking,pg-supply-chain,3.01,RM-Wholesale Business - Wholesale Banking|1396...
7152,FRM Course,RM-Wholesale Business - Wholesale Banking,Collateral Audit Coordination,Valuation Coordination,Beginner,https://henryharvin.com/frm-course,Henry Harvin,Module 1: Quantitative Analysis<br>- Discrete ...,35112,36039,...,16142,[9],Self-paced (Recorded),192.0,Hours,59500.0,RM-Wholesale Business - Wholesale Banking,FRM,3.01,RM-Wholesale Business - Wholesale Banking|1398...
7153,Banking Law Course,RM-Wholesale Business - Wholesale Banking,Collateral Audit Coordination,Audit Scheduling,Beginner,https://www.henryharvin.com/banking-law-course,Henry Harvin,Banking Law Course Curriculum<br>Module 1: Ban...,6041,1649,...,16143,[9],Self-paced (Recorded),12.0,Hours,10000.0,RM-Wholesale Business - Wholesale Banking,Banking Law,3.01,RM-Wholesale Business - Wholesale Banking|1398...
7154,FRM Course,RM-Wholesale Business - Wholesale Banking,Client Relationship Management,Relationship Risk Awareness,Beginner,https://henryharvin.com/frm-course,Henry Harvin,Module 1: Quantitative Analysis<br>- Discrete ...,35112,36039,...,15965,[9],Self-paced (Recorded),192.0,Hours,59500.0,RM-Wholesale Business - Wholesale Banking,FRM,3.01,RM-Wholesale Business - Wholesale Banking|1372...

In [15]:
result_Beginner =  Beginner.groupby("FSC_concat")["product_id"].nunique().reset_index()
result_Beginner.columns = ["FSC_concat", "Function_count_beginner"]
result_Beginner.head()

                     FSC_concat  Function_count_beginner
0  Assurance - Audit|1188|14739                        1
1  Assurance - Audit|1188|14740                        1
2  Assurance - Audit|1188|14741                        1
3  Assurance - Audit|1188|14742                        1
4  Assurance - Audit|1188|14743                        1

In [16]:
Intermediate = df[df['course_level'] == 'Intermediate']
Intermediate.head()

,Course Name,Function,Skill,Concept,course_level,Course link,CPP,Course Sylabus,product_id,Prod MP ID,...,concepts,Corporate id,Course Learning mode,Duration,Duration_c,Price,Function 2,Client ID,Unnamed: 20,FSC_concat
30,Financial Planning & Analysis (FP&A) Masterclass,Assurance - Audit,Data Analytics & Insight Generation,Data Narrative Building,Intermediate,https://www.thinkingbridge.in/courses/Financia...,Thinking Bridge,Session 1 - 1.5 Hrs<br>Introduction to FP&A & ...,37833,38955,...,14789,[9],Self-paced (Recorded),20.0,Hours,2999.0,Assurance - Audit,69466e60de84b15b52c5dd34,NaN,Assurance - Audit|1193|14789
31,Financial Planning & Analysis (FP&A) Masterclass,Assurance - Audit,Data Analytics & Insight Generation,Data Quality Validation,Intermediate,https://www.thinkingbridge.in/courses/Financia...,Thinking Bridge,Session 1 - 1.5 Hrs<br>Introduction to FP&A & ...,37833,38955,...,14790,[9],Self-paced (Recorded),20.0,Hours,2999.0,Assurance - Audit,69466e60de84b15b52c5dd34,NaN,Assurance - Audit|1193|14790
32,Financial Planning & Analysis (FP&A) Masterclass,Assurance - Audit,Data Analytics & Insight Generation,Analytics Tool Utilisation,Intermediate,https://www.thinkingbridge.in/courses/Financia...,Thinking Bridge,Session 1 - 1.5 Hrs<br>Introduction to FP&A & ...,37833,38955,...,14796,[9],Self-paced (Recorded),20.0,Hours,2999.0,Assurance - Audit,69466e60de84b15b52c5dd34,NaN,Assurance - Audit|1193|14796
33,Financial Planning & Analysis (FP&A) Masterclass,Assurance - Audit,Audit Findings & Results Reporting,Executive Reporting,Intermediate,https://www.thinkingbridge.in/courses/Financia...,Thinking Bridge,Session 1 - 1.5 Hrs<br>Introduction to FP&A & ...,37833,38955,...,14950,[9],Self-paced (Recorded),20.0,Hours,2999.0,Assurance - Audit,69466e60de84b15b52c5dd34,NaN,Assurance - Audit|1209|14950
34,Financial Planning & Analysis (FP&A) Masterclass,Assurance - Audit,Audit Findings & Results Reporting,Cross-Functional Reporting,Intermediate,https://www.thinkingbridge.in/courses/Financia...,Thinking Bridge,Session 1 - 1.5 Hrs<br>Introduction to FP&A & ...,37833,38955,...,14956,[9],Self-paced (Recorded),20.0,Hours,2999.0,Assurance - Audit,69466e60de84b15b52c5dd34,NaN,Assurance - Audit|1209|14956

In [17]:
result_Intermediate =  Intermediate.groupby("FSC_concat")["product_id"].nunique().reset_index()
result_Intermediate.columns = ["FSC_concat", "Function_count_intermediate"]
result_Intermediate.head()

                     FSC_concat  Function_count_intermediate
0  Assurance - Audit|1188|14739                            1
1  Assurance - Audit|1188|14740                            1
2  Assurance - Audit|1188|14741                            2
3  Assurance - Audit|1188|14742                            1
4  Assurance - Audit|1188|14743                            1

In [18]:
unique_values_df = df.drop_duplicates(subset=['FSC_concat'])
unique_values_df = unique_values_df[['FSC_concat']]
unique_values_df.head()

                     FSC_concat
0  Assurance - Audit|1191|14777
1  Assurance - Audit|1193|14796
2   Assurance - Audit|1237|5652
3   Assurance - Audit|1237|5730
4  Assurance - Audit|1188|14740

In [19]:
merged_df = pd.merge(unique_values_df, result_Beginner, on="FSC_concat", how="left")  # Merge df1 and df2
merged_df = pd.merge(merged_df, result_Intermediate, on="FSC_concat", how="left")  # Merge with df3
merged_df = pd.merge(merged_df, result_Advanced, on="FSC_concat", how="left")
merged_df.head()

,FSC_concat,Function_count_beginner,Function_count_intermediate,Function_count_Advanced
0,Assurance - Audit|1191|14777,1.0,1.0,1.0
1,Assurance - Audit|1193|14796,2.0,4.0,3.0
2,Assurance - Audit|1237|5652,2.0,2.0,1.0
3,Assurance - Audit|1237|5730,2.0,2.0,3.0
4,Assurance - Audit|1188|14740,1.0,1.0,2.0

In [20]:
# If you're working with a single column but want to keep it as a DataFrame:
merged_df['Function_count_beginner'] = merged_df['Function_count_beginner'].fillna(0).astype(int)
merged_df['Function_count_intermediate'] = merged_df['Function_count_intermediate'].fillna(0).astype(int)
merged_df['Function_count_Advanced'] = merged_df['Function_count_Advanced'].fillna(0).astype(int)
merged_df.head()

,FSC_concat,Function_count_beginner,Function_count_intermediate,Function_count_Advanced
0,Assurance - Audit|1191|14777,1,1,1
1,Assurance - Audit|1193|14796,2,4,3
2,Assurance - Audit|1237|5652,2,2,1
3,Assurance - Audit|1237|5730,2,2,3
4,Assurance - Audit|1188|14740,1,1,2

In [21]:
#df1['Skill ID'].unique()
#df1['FSC_concat']= df1['PRODUCTION Skill ID'].fillna(0).astype(int).astype(str)+"|"+df1['PRODUCTION Concepts ID'].fillna(0).astype(int).astype(str)
#df1.head()

In [22]:
#df1['FSC_concat'] = (
    #pd.to_numeric(df1['PRODUCTION Skill ID'], errors='coerce').fillna(0).astype(int).astype(str)
    #+ "|" + pd.to_numeric(df1['PRODUCTION Concepts ID'], errors='coerce').fillna(0).astype(int).astype(str))
#df1.head()


df1['FSC_concat'] = df1['Academy'].fillna(0).astype(str) + "|" + df1['PRODUCTION Skill ID'].fillna(0).astype(int).astype(str) + "|" + (df1['PRODUCTION Concepts ID']) .fillna(0).astype(int).astype(str)
df1.head()

,Academy,Prod Function ID,Skill,PRODUCTION Skill ID,Skill Description,Concept,Concept Description,PRODUCTION Concepts ID,Concat,FSC_concat
0,Assurance - Audit,87,Audit Automation Tools and Techniques,1230,Master Audit Automation to streamline processe...,Audit Management Software,"Experience with tools such as TeamMate, Metric...",7014,Assurance - AuditAudit Automation Tools and Te...,Assurance - Audit|1230|7014
1,Assurance - Audit,87,Audit Automation Tools and Techniques,1230,Master Audit Automation to streamline processe...,Continuous Auditing,"Leveraging technology to perform ongoing, real...",7015,Assurance - AuditAudit Automation Tools and Te...,Assurance - Audit|1230|7015
2,Assurance - Audit,87,Audit Automation Tools and Techniques,1230,Master Audit Automation to streamline processe...,Automated Evidence Capture,Using automation scripts to collect audit evid...,15339,Assurance - AuditAudit Automation Tools and Te...,Assurance - Audit|1230|15339
3,Assurance - Audit,87,Audit Automation Tools and Techniques,1230,Master Audit Automation to streamline processe...,Real-time Control Dashboards,Providing live visibility into automated contr...,15340,Assurance - AuditAudit Automation Tools and Te...,Assurance - Audit|1230|15340
4,Assurance - Audit,87,Audit Automation Tools and Techniques,1230,Master Audit Automation to streamline processe...,Exception Auto-Triage,Automatically categorizing exceptions based on...,15341,Assurance - AuditAudit Automation Tools and Te...,Assurance - Audit|1230|15341

In [23]:
automated_df = pd.merge(df1,merged_df, on ='FSC_concat', how = 'left' )
automated_df['Function_count_beginner'] = automated_df['Function_count_beginner'].fillna(0).astype(int)
automated_df['Function_count_intermediate'] = automated_df['Function_count_intermediate'].fillna(0).astype(int)
automated_df['Function_count_Advanced'] = automated_df['Function_count_Advanced'].fillna(0).astype(int)
automated_df.head()

,Academy,Prod Function ID,Skill,PRODUCTION Skill ID,Skill Description,Concept,Concept Description,PRODUCTION Concepts ID,Concat,FSC_concat,Function_count_beginner,Function_count_intermediate,Function_count_Advanced
0,Assurance - Audit,87,Audit Automation Tools and Techniques,1230,Master Audit Automation to streamline processe...,Audit Management Software,"Experience with tools such as TeamMate, Metric...",7014,Assurance - AuditAudit Automation Tools and Te...,Assurance - Audit|1230|7014,1,1,1
1,Assurance - Audit,87,Audit Automation Tools and Techniques,1230,Master Audit Automation to streamline processe...,Continuous Auditing,"Leveraging technology to perform ongoing, real...",7015,Assurance - AuditAudit Automation Tools and Te...,Assurance - Audit|1230|7015,1,1,2
2,Assurance - Audit,87,Audit Automation Tools and Techniques,1230,Master Audit Automation to streamline processe...,Automated Evidence Capture,Using automation scripts to collect audit evid...,15339,Assurance - AuditAudit Automation Tools and Te...,Assurance - Audit|1230|15339,1,1,1
3,Assurance - Audit,87,Audit Automation Tools and Techniques,1230,Master Audit Automation to streamline processe...,Real-time Control Dashboards,Providing live visibility into automated contr...,15340,Assurance - AuditAudit Automation Tools and Te...,Assurance - Audit|1230|15340,1,1,2
4,Assurance - Audit,87,Audit Automation Tools and Techniques,1230,Master Audit Automation to streamline processe...,Exception Auto-Triage,Automatically categorizing exceptions based on...,15341,Assurance - AuditAudit Automation Tools and Te...,Assurance - Audit|1230|15341,1,1,2

In [24]:
automated_df.to_excel("C:\\Users\\taslim.siddiqui\\Downloads//automate_FSC_deficit_Kotak_08-01-2026.xlsx")

In [27]:
import pandas as pd
 
path =r"C:\Users\taslim.siddiqui\Downloads\KOTAK Course + Deficit Tracker_Data added (4).xlsx"
df = pd.read_excel(path, sheet_name='HH+Other CPP Master')
 
# cpp_value = "HH+Other"   # <-- change if needed
# df_f = df[df["CPP"].astype(str).str.strip().eq(cpp_value)]
 
# --- PIVOT: Function x Proficiency, distinct count of concepts ---
pivot = pd.pivot_table(
    df,
    index=['Function'],
    columns=['course_level'],
    values="concepts"
,          # use "Concept" if you want distinct by concept name
    aggfunc=pd.Series.nunique,    # distinct count
    fill_value=0
)
 
pivot_out = pivot.reset_index()
 
print(pivot_out.head())
pivot_out.to_excel(r"C:\Users\taslim.siddiqui\Downloads\pivot_1.xlsx")

course_level                            Function  Advanced  Beginner  \
0                              Assurance - Audit       466       447
1                                             HR       447       441
2                                            Ops       299       302
3                Professional Behavior & Mindset        34        35
4             RM-Commercial Bank - Agri Business       150       165

course_level  Intermediate
0                      471
1                      406
2                      288
3                       35
4                      173

In [26]:
print("df1 dup keys:", df1['FSC_concat'].duplicated().sum())
print("merged_df dup keys:", merged_df['FSC_concat'].duplicated().sum())
print("Any 0-keys in df1:", df1['FSC_concat'].str.startswith("0|").sum(), df1['FSC_concat'].str.contains("|0|", regex=False).sum())
df1.to_excel(r"C:\Users\taslim.siddiqui\Downloads\FSC_concat.xlsx")

df1 dup keys: 0
merged_df dup keys: 0
Any 0-keys in df1: 0 0