# FSC Deficiet

In [12]:
import pandas as pd

In [13]:
#Function,Prod Function ID,Skill,PRODUCTION Skill ID,Skill Description,Concept,Concept Description,PRODUCTION Concepts ID,Concat,product_id


#load FSC master excel
df1 = pd.read_excel(r"C:\Users\taslim.siddiqui\Downloads\master_aarti_30.xlsx")
df1.head()

,Function,Prod Function id,Skill,PRODUCTION Skill ID,Concept,PRODUCTION Concepts ID,Concat
0,Capability Building,88,Digital & Microlearning Tools Usage,1108,Use of AI Tools for Content Curation,13902,Capability BuildingDigital & Microlearning Too...
1,Capability Building,88,Content Development & Instructional Design,1102,Compliance & Policy Module Drafting,13842,Capability BuildingContent Development & Instr...
2,HR Compensation & Payroll,92,End-to-End Payroll & Attendance Management,1160,Confidentiality & Data Security,14427,HR Compensation & PayrollEnd-to-End Payroll & ...
3,HR Talent - Stratigic Talent,94,Talent Analytics & Predictive Insights,1119,Attrition Risk Prediction Model,14004,HR Talent - Stratigic TalentTalent Analytics &...
4,Capability Building,88,"Learning Design, Delivery & Evaluation",1162,Learning Content Customization,14454,"Capability BuildingLearning Design, Delivery &..."

In [14]:
#product_name,course_level,skill_id,concepts,product_id
#load data file
df2 = pd.read_excel(r"C:\Users\taslim.siddiqui\Downloads\Aarti_file_input.xlsx")
df2

,Course Name,Function,Skills,Concept,course_level,Course link,CPP,Course Sylabus,product_id,Prod MP ID,Function id,skill_id,concepts,Corporate id,Course Learning mode,Duration,Duration_c,Price,Unnamed: 18
0,"ACCA Course Training (Skill level, Self Paced ...",Corporate Affairs,Statutory Compliance & Licensing Management,Authority Approval Flow Design,Beginner,https://www.henryharvin.com/acca-course,Henry Harvin,Module 1: Business and Technology<br>The busin...,33362,39141,89,1062,13440,[10],Self-paced (Recorded),Hours,180.00,249000.0,NaN
1,"ACCA Course Training (Skill level, Self Paced ...",Corporate Affairs,Legal & Regulatory Framework Awareness,Regulatory Framework Interpretation,Beginner,https://www.henryharvin.com/acca-course,Henry Harvin,Module 1: Business and Technology<br>The busin...,33362,39141,89,1063,13444,[10],Self-paced (Recorded),Hours,180.00,249000.0,NaN
2,"ACCA Course Training (Skill level, Self Paced ...",Corporate Affairs,Legal & Regulatory Framework Awareness,Policy Change Watch,Beginner,https://www.henryharvin.com/acca-course,Henry Harvin,Module 1: Business and Technology<br>The busin...,33362,39141,89,1063,13445,[10],Self-paced (Recorded),Hours,180.00,249000.0,NaN
3,"ACCA Course Training (Skill level, Self Paced ...",Corporate Affairs,Legal & Regulatory Framework Awareness,Case Precedent Monitoring,Beginner,https://www.henryharvin.com/acca-course,Henry Harvin,Module 1: Business and Technology<br>The busin...,33362,39141,89,1063,13450,[10],Self-paced (Recorded),Hours,180.00,249000.0,NaN
4,"ACCA Course Training (Skill level, Self Paced ...",Corporate Affairs,Crisis Management & Business Continuity Alignment,Continuity Risk Register,Beginner,https://www.henryharvin.com/acca-course,Henry Harvin,Module 1: Business and Technology<br>The busin...,33362,39141,89,1067,13486,[10],Self-paced (Recorded),Hours,180.00,249000.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2620,Strategic Workforce Management,TA & OM,Workforce Planning & Talent Strategy,Talent Pipeline & Succession Alignment,Beginner,https://www.eduonix.com/strategic-workforce-ma...,Eduonix learning Solutions,Section 1 : Introduction<br>Introduction<br>Se...,37850,39135,97,1183,14696,[10],Self-paced (Recorded),Hours,1.05,2348.2,30.12
2621,Strategic Workforce Management,TA & OM,Workforce Planning & Talent Strategy,Governance & Review Cadence,Beginner,https://www.eduonix.com/strategic-workforce-ma...,Eduonix learning Solutions,Section 1 : Introduction<br>Introduction<br>Se...,37850,39135,97,1183,14697,[10],Self-paced (Recorded),Hours,1.05,2348.2,30.12
2622,HR Analytics with Python,HRIS,AI & Automation,Intelligent Document Processing,Beginner,https://www.henryharvin.com/hr-analytics-with-...,Henry Harvin,Module 1 - Introduction To Analytics<br>Module...,35285,39209,96,1184,14703,[10],Self-paced (Recorded),Hours,192.00,NaN,30.12
2623,Employee Relation and Engagement-Manage and En...,Corporate Communication,Organizational Communication Excellence,Change Communication,Beginner,https://www.eduonix.com/employee-relation-and-...,Eduonix learning Solutions,Section 1 : Introduction<br>Introduction to Em...,37851,39211,90,1186,14722,[10],Self-paced (Recorded),Hours,7.37,2348.0,30.12
2624,Employee Relation and Engagement-Manage and En...,Corporate Communication,Organizational Communication Excellence,Measuring Communication Effectiveness,Beginner,https://www.eduonix.com/employee-relation-and-...,Eduonix learning Solutions,Section 1 : Introduction<br>Introduction to Em...,37851,39211,90,1186,14728,[10],Self-paced (Recorded),Hours,7.37,2348.0,30.12

In [15]:
df1['PRODUCTION Concepts ID'].value_counts()

PRODUCTION Concepts ID
13902    1
13926    1
13957    1
13956    1
13955    1
        ..
13587    1
13586    1
13563    1
13508    1
14738    1
Name: count, Length: 1305, dtype: int64

If We want to remove some CPPs

In [16]:
# df2# data is the file which will only have CPP names

# # List of values to check
# values_to_check = ['Coursera','GVC','Gyanodaya Virtual Campus','CIEL','Percipio']

# # Check if any values in the DataFrame are in the list
# df2['CPP_ABC'] = df2['CPP Name'].isin(values_to_check)
# df2 = df2.query("CPP_ABC == False")
# df2

In [17]:
# Concept Column Row splitting code
df2['concepts'] = df2['concepts'].apply(
    lambda x: [int(i.strip()) for i in x.split(',')] if isinstance(x, str) else x
)

# Explode the 'concepts' column to create separate rows
df = df2.explode('concepts', ignore_index=True)
df['concepts'] = df['concepts'].fillna(0).astype(int)


df

,Course Name,Function,Skills,Concept,course_level,Course link,CPP,Course Sylabus,product_id,Prod MP ID,Function id,skill_id,concepts,Corporate id,Course Learning mode,Duration,Duration_c,Price,Unnamed: 18
0,"ACCA Course Training (Skill level, Self Paced ...",Corporate Affairs,Statutory Compliance & Licensing Management,Authority Approval Flow Design,Beginner,https://www.henryharvin.com/acca-course,Henry Harvin,Module 1: Business and Technology<br>The busin...,33362,39141,89,1062,13440,[10],Self-paced (Recorded),Hours,180.00,249000.0,NaN
1,"ACCA Course Training (Skill level, Self Paced ...",Corporate Affairs,Legal & Regulatory Framework Awareness,Regulatory Framework Interpretation,Beginner,https://www.henryharvin.com/acca-course,Henry Harvin,Module 1: Business and Technology<br>The busin...,33362,39141,89,1063,13444,[10],Self-paced (Recorded),Hours,180.00,249000.0,NaN
2,"ACCA Course Training (Skill level, Self Paced ...",Corporate Affairs,Legal & Regulatory Framework Awareness,Policy Change Watch,Beginner,https://www.henryharvin.com/acca-course,Henry Harvin,Module 1: Business and Technology<br>The busin...,33362,39141,89,1063,13445,[10],Self-paced (Recorded),Hours,180.00,249000.0,NaN
3,"ACCA Course Training (Skill level, Self Paced ...",Corporate Affairs,Legal & Regulatory Framework Awareness,Case Precedent Monitoring,Beginner,https://www.henryharvin.com/acca-course,Henry Harvin,Module 1: Business and Technology<br>The busin...,33362,39141,89,1063,13450,[10],Self-paced (Recorded),Hours,180.00,249000.0,NaN
4,"ACCA Course Training (Skill level, Self Paced ...",Corporate Affairs,Crisis Management & Business Continuity Alignment,Continuity Risk Register,Beginner,https://www.henryharvin.com/acca-course,Henry Harvin,Module 1: Business and Technology<br>The busin...,33362,39141,89,1067,13486,[10],Self-paced (Recorded),Hours,180.00,249000.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2620,Strategic Workforce Management,TA & OM,Workforce Planning & Talent Strategy,Talent Pipeline & Succession Alignment,Beginner,https://www.eduonix.com/strategic-workforce-ma...,Eduonix learning Solutions,Section 1 : Introduction<br>Introduction<br>Se...,37850,39135,97,1183,14696,[10],Self-paced (Recorded),Hours,1.05,2348.2,30.12
2621,Strategic Workforce Management,TA & OM,Workforce Planning & Talent Strategy,Governance & Review Cadence,Beginner,https://www.eduonix.com/strategic-workforce-ma...,Eduonix learning Solutions,Section 1 : Introduction<br>Introduction<br>Se...,37850,39135,97,1183,14697,[10],Self-paced (Recorded),Hours,1.05,2348.2,30.12
2622,HR Analytics with Python,HRIS,AI & Automation,Intelligent Document Processing,Beginner,https://www.henryharvin.com/hr-analytics-with-...,Henry Harvin,Module 1 - Introduction To Analytics<br>Module...,35285,39209,96,1184,14703,[10],Self-paced (Recorded),Hours,192.00,NaN,30.12
2623,Employee Relation and Engagement-Manage and En...,Corporate Communication,Organizational Communication Excellence,Change Communication,Beginner,https://www.eduonix.com/employee-relation-and-...,Eduonix learning Solutions,Section 1 : Introduction<br>Introduction to Em...,37851,39211,90,1186,14722,[10],Self-paced (Recorded),Hours,7.37,2348.0,30.12
2624,Employee Relation and Engagement-Manage and En...,Corporate Communication,Organizational Communication Excellence,Measuring Communication Effectiveness,Beginner,https://www.eduonix.com/employee-relation-and-...,Eduonix learning Solutions,Section 1 : Introduction<br>Introduction to Em...,37851,39211,90,1186,14728,[10],Self-paced (Recorded),Hours,7.37,2348.0,30.12

In [18]:
# Concept Column Row splitting code
df2['concepts'] = df2['concepts'].apply(
    lambda x: [int(i.strip()) for i in x.split(',')] if isinstance(x, str) else x
)

# Explode the 'concepts' column to create separate rows
df = df2.explode('concepts', ignore_index=True)
df['concepts'] = df['concepts'].fillna(0).astype(int)


df

,Course Name,Function,Skills,Concept,course_level,Course link,CPP,Course Sylabus,product_id,Prod MP ID,Function id,skill_id,concepts,Corporate id,Course Learning mode,Duration,Duration_c,Price,Unnamed: 18
0,"ACCA Course Training (Skill level, Self Paced ...",Corporate Affairs,Statutory Compliance & Licensing Management,Authority Approval Flow Design,Beginner,https://www.henryharvin.com/acca-course,Henry Harvin,Module 1: Business and Technology<br>The busin...,33362,39141,89,1062,13440,[10],Self-paced (Recorded),Hours,180.00,249000.0,NaN
1,"ACCA Course Training (Skill level, Self Paced ...",Corporate Affairs,Legal & Regulatory Framework Awareness,Regulatory Framework Interpretation,Beginner,https://www.henryharvin.com/acca-course,Henry Harvin,Module 1: Business and Technology<br>The busin...,33362,39141,89,1063,13444,[10],Self-paced (Recorded),Hours,180.00,249000.0,NaN
2,"ACCA Course Training (Skill level, Self Paced ...",Corporate Affairs,Legal & Regulatory Framework Awareness,Policy Change Watch,Beginner,https://www.henryharvin.com/acca-course,Henry Harvin,Module 1: Business and Technology<br>The busin...,33362,39141,89,1063,13445,[10],Self-paced (Recorded),Hours,180.00,249000.0,NaN
3,"ACCA Course Training (Skill level, Self Paced ...",Corporate Affairs,Legal & Regulatory Framework Awareness,Case Precedent Monitoring,Beginner,https://www.henryharvin.com/acca-course,Henry Harvin,Module 1: Business and Technology<br>The busin...,33362,39141,89,1063,13450,[10],Self-paced (Recorded),Hours,180.00,249000.0,NaN
4,"ACCA Course Training (Skill level, Self Paced ...",Corporate Affairs,Crisis Management & Business Continuity Alignment,Continuity Risk Register,Beginner,https://www.henryharvin.com/acca-course,Henry Harvin,Module 1: Business and Technology<br>The busin...,33362,39141,89,1067,13486,[10],Self-paced (Recorded),Hours,180.00,249000.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2620,Strategic Workforce Management,TA & OM,Workforce Planning & Talent Strategy,Talent Pipeline & Succession Alignment,Beginner,https://www.eduonix.com/strategic-workforce-ma...,Eduonix learning Solutions,Section 1 : Introduction<br>Introduction<br>Se...,37850,39135,97,1183,14696,[10],Self-paced (Recorded),Hours,1.05,2348.2,30.12
2621,Strategic Workforce Management,TA & OM,Workforce Planning & Talent Strategy,Governance & Review Cadence,Beginner,https://www.eduonix.com/strategic-workforce-ma...,Eduonix learning Solutions,Section 1 : Introduction<br>Introduction<br>Se...,37850,39135,97,1183,14697,[10],Self-paced (Recorded),Hours,1.05,2348.2,30.12
2622,HR Analytics with Python,HRIS,AI & Automation,Intelligent Document Processing,Beginner,https://www.henryharvin.com/hr-analytics-with-...,Henry Harvin,Module 1 - Introduction To Analytics<br>Module...,35285,39209,96,1184,14703,[10],Self-paced (Recorded),Hours,192.00,NaN,30.12
2623,Employee Relation and Engagement-Manage and En...,Corporate Communication,Organizational Communication Excellence,Change Communication,Beginner,https://www.eduonix.com/employee-relation-and-...,Eduonix learning Solutions,Section 1 : Introduction<br>Introduction to Em...,37851,39211,90,1186,14722,[10],Self-paced (Recorded),Hours,7.37,2348.0,30.12
2624,Employee Relation and Engagement-Manage and En...,Corporate Communication,Organizational Communication Excellence,Measuring Communication Effectiveness,Beginner,https://www.eduonix.com/employee-relation-and-...,Eduonix learning Solutions,Section 1 : Introduction<br>Introduction to Em...,37851,39211,90,1186,14728,[10],Self-paced (Recorded),Hours,7.37,2348.0,30.12

In [19]:
# Renaming Flexible to Beginner in Course level column
df['course_level'] = df['course_level'].replace('Flexible', 'Beginner')

In [20]:
df['course_level'].unique()

array(['Beginner', 'Advanced', 'Intermediate'], dtype=object)

In [21]:
# Concat of Skill Concept
#df['FSC_concat'] = df['skill_id'].astype(str)+'|'+df['concepts'].astype(str)
#df['FSC_concat'] = df['concepts'].astype(str)
df['FSC_concat'] =  df['Function id'].astype(str) + '|'+  df['skill_id'].astype(str)+'|'+df['concepts'].astype(str)
df['FSC_concat']

0       89|1062|13440
1       89|1063|13444
2       89|1063|13445
3       89|1063|13450
4       89|1067|13486
            ...
2620    97|1183|14696
2621    97|1183|14697
2622    96|1184|14703
2623    90|1186|14722
2624    90|1186|14728
Name: FSC_concat, Length: 2625, dtype: object

In [22]:
uniquedf = df.drop_duplicates(subset=['FSC_concat'])
uniquedf=uniquedf['FSC_concat']
uniquedf

0       89|1062|13440
1       89|1063|13444
2       89|1063|13445
3       89|1063|13450
4       89|1067|13486
            ...
2237    93|1093|13744
2240    93|1097|13789
2247    96|1141|14230
2249    96|1143|14249
2251    94|1146|14277
Name: FSC_concat, Length: 990, dtype: object

In [23]:
# Making new dataframe of Advanced course level only.
Advanced = df[df['course_level'] == 'Advanced']
Advanced

,Course Name,Function,Skills,Concept,course_level,Course link,CPP,Course Sylabus,product_id,Prod MP ID,Function id,skill_id,concepts,Corporate id,Course Learning mode,Duration,Duration_c,Price,Unnamed: 18,FSC_concat
28,Advanced Certification in Core HR Specialist -...,HR Compensation & Payroll,Cost Modeling & Manpower Budgeting,Cost-per-Employee Calculator,Advanced,https://www.henryharvin.com/advanced-certifica...,Henry Harvin,Module 1: Understanding HR Analytics<br>Module...,33156,38912,92,1090,13717,[10],Self-paced (Recorded),Hours,192.0,89500.0,NaN,92|1090|13717
29,Advanced Certification in Core HR Specialist -...,HR Compensation & Payroll,Cost Modeling & Manpower Budgeting,Budget Presentation Dashboards,Advanced,https://www.henryharvin.com/advanced-certifica...,Henry Harvin,Module 1: Understanding HR Analytics<br>Module...,33156,38912,92,1090,13723,[10],Self-paced (Recorded),Hours,192.0,89500.0,NaN,92|1090|13723
30,Advanced Certification in Core HR Specialist -...,HR Compensation & Payroll,Payroll System Configuration & Automation,Payroll Engine Testing Sandbox,Advanced,https://www.henryharvin.com/advanced-certifica...,Henry Harvin,Module 1: Understanding HR Analytics<br>Module...,33156,38912,92,1091,13732,[10],Self-paced (Recorded),Hours,192.0,89500.0,NaN,92|1091|13732
31,Advanced Certification in Core HR Specialist -...,Capability Building,Learning Data & Reporting Analytics,Cost per Participant Calculator,Advanced,https://www.henryharvin.com/advanced-certifica...,Henry Harvin,Module 1: Understanding HR Analytics<br>Module...,33156,38912,88,1107,13887,[10],Self-paced (Recorded),Hours,192.0,89500.0,NaN,88|1107|13887
32,Advanced Certification in Core HR Specialist -...,Capability Building,Internal Capability Building Communication,Certificate Distribution Workflow,Advanced,https://www.henryharvin.com/advanced-certifica...,Henry Harvin,Module 1: Understanding HR Analytics<br>Module...,33156,38912,88,1109,13907,[10],Self-paced (Recorded),Hours,192.0,89500.0,NaN,88|1109|13907
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2269,Advanced Human Resource Management Course (Sel...,HRIS,AI & Automation,Workflow Orchestration,Advanced,https://www.henryharvin.com/advanced-hrm-course,Henry Harvin,Year 1<br>Module 1: HR Payroll Specialist - In...,32958,39146,96,1184,14708,[10],Self-paced (Recorded),Hours,480.0,349500.0,30.12,96|1184|14708
2270,Advanced Human Resource Management Course (Sel...,Corporate Communication,Organizational Communication Excellence,Leadership Communication,Advanced,https://www.henryharvin.com/advanced-hrm-course,Henry Harvin,Year 1<br>Module 1: HR Payroll Specialist - In...,32958,39146,90,1186,14720,[10],Self-paced (Recorded),Hours,480.0,349500.0,30.12,90|1186|14720
2271,Advanced Human Resource Management Course (Sel...,Corporate Communication,Organizational Communication Excellence,Change Communication,Advanced,https://www.henryharvin.com/advanced-hrm-course,Henry Harvin,Year 1<br>Module 1: HR Payroll Specialist - In...,32958,39146,90,1186,14722,[10],Self-paced (Recorded),Hours,480.0,349500.0,30.12,90|1186|14722
2272,Advanced Social Media Marketing Course,Corporate Communication,Organizational Communication Excellence,Multi-Channel Communication,Advanced,https://www.henryharvin.com/social-media-marke...,Henry Harvin,Module 1: Social Media Marketing Overview<br>M...,6013,16678,90,1186,14725,[10],Self-paced (Recorded),Hours,18.0,7500.0,30.12,90|1186|14725
2273,Advanced Social Media Marketing Course,Corporate Communication,Organizational Communication Excellence,Measuring Communication Effectiveness,Advanced,https://www.henryharvin.com/social-media-marke...,Henry Harvin,Module 1: Social Media Marketing Overview<br>M...,6013,16678,90,1186,14728,[10],Self-paced (Recorded),Hours,18.0,7500.0,30.12,90|1186|14728

In [24]:
# Counting the number of courses in Advanced course level against the FSC_concat column.
result_Advanced =  Advanced.groupby("FSC_concat")["product_id"].nunique().reset_index()
result_Advanced.columns = ["FSC_concat", "Function_count_Advanced"]
result_Advanced.head()

      FSC_concat  Function_count_Advanced
0  54|1080|13623                        1
1  54|1081|13624                        1
2  54|1081|13625                        1
3  54|1081|13627                        1
4  54|1081|13628                        1

In [25]:
Beginner = df[df['course_level'] == 'Beginner']
Beginner

,Course Name,Function,Skills,Concept,course_level,Course link,CPP,Course Sylabus,product_id,Prod MP ID,Function id,skill_id,concepts,Corporate id,Course Learning mode,Duration,Duration_c,Price,Unnamed: 18,FSC_concat
0,"ACCA Course Training (Skill level, Self Paced ...",Corporate Affairs,Statutory Compliance & Licensing Management,Authority Approval Flow Design,Beginner,https://www.henryharvin.com/acca-course,Henry Harvin,Module 1: Business and Technology<br>The busin...,33362,39141,89,1062,13440,[10],Self-paced (Recorded),Hours,180.00,249000.0,NaN,89|1062|13440
1,"ACCA Course Training (Skill level, Self Paced ...",Corporate Affairs,Legal & Regulatory Framework Awareness,Regulatory Framework Interpretation,Beginner,https://www.henryharvin.com/acca-course,Henry Harvin,Module 1: Business and Technology<br>The busin...,33362,39141,89,1063,13444,[10],Self-paced (Recorded),Hours,180.00,249000.0,NaN,89|1063|13444
2,"ACCA Course Training (Skill level, Self Paced ...",Corporate Affairs,Legal & Regulatory Framework Awareness,Policy Change Watch,Beginner,https://www.henryharvin.com/acca-course,Henry Harvin,Module 1: Business and Technology<br>The busin...,33362,39141,89,1063,13445,[10],Self-paced (Recorded),Hours,180.00,249000.0,NaN,89|1063|13445
3,"ACCA Course Training (Skill level, Self Paced ...",Corporate Affairs,Legal & Regulatory Framework Awareness,Case Precedent Monitoring,Beginner,https://www.henryharvin.com/acca-course,Henry Harvin,Module 1: Business and Technology<br>The busin...,33362,39141,89,1063,13450,[10],Self-paced (Recorded),Hours,180.00,249000.0,NaN,89|1063|13450
4,"ACCA Course Training (Skill level, Self Paced ...",Corporate Affairs,Crisis Management & Business Continuity Alignment,Continuity Risk Register,Beginner,https://www.henryharvin.com/acca-course,Henry Harvin,Module 1: Business and Technology<br>The busin...,33362,39141,89,1067,13486,[10],Self-paced (Recorded),Hours,180.00,249000.0,NaN,89|1067|13486
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2620,Strategic Workforce Management,TA & OM,Workforce Planning & Talent Strategy,Talent Pipeline & Succession Alignment,Beginner,https://www.eduonix.com/strategic-workforce-ma...,Eduonix learning Solutions,Section 1 : Introduction<br>Introduction<br>Se...,37850,39135,97,1183,14696,[10],Self-paced (Recorded),Hours,1.05,2348.2,30.12,97|1183|14696
2621,Strategic Workforce Management,TA & OM,Workforce Planning & Talent Strategy,Governance & Review Cadence,Beginner,https://www.eduonix.com/strategic-workforce-ma...,Eduonix learning Solutions,Section 1 : Introduction<br>Introduction<br>Se...,37850,39135,97,1183,14697,[10],Self-paced (Recorded),Hours,1.05,2348.2,30.12,97|1183|14697
2622,HR Analytics with Python,HRIS,AI & Automation,Intelligent Document Processing,Beginner,https://www.henryharvin.com/hr-analytics-with-...,Henry Harvin,Module 1 - Introduction To Analytics<br>Module...,35285,39209,96,1184,14703,[10],Self-paced (Recorded),Hours,192.00,NaN,30.12,96|1184|14703
2623,Employee Relation and Engagement-Manage and En...,Corporate Communication,Organizational Communication Excellence,Change Communication,Beginner,https://www.eduonix.com/employee-relation-and-...,Eduonix learning Solutions,Section 1 : Introduction<br>Introduction to Em...,37851,39211,90,1186,14722,[10],Self-paced (Recorded),Hours,7.37,2348.0,30.12,90|1186|14722
2624,Employee Relation and Engagement-Manage and En...,Corporate Communication,Organizational Communication Excellence,Measuring Communication Effectiveness,Beginner,https://www.eduonix.com/employee-relation-and-...,Eduonix learning Solutions,Section 1 : Introduction<br>Introduction to Em...,37851,39211,90,1186,14728,[10],Self-paced (Recorded),Hours,7.37,2348.0,30.12,90|1186|14728

In [26]:
result_Beginner =  Beginner.groupby("FSC_concat")["product_id"].nunique().reset_index()
result_Beginner.columns = ["FSC_concat", "Function_count_beginner"]
result_Beginner.head()

      FSC_concat  Function_count_beginner
0  54|1080|13614                        1
1  54|1080|13616                        1
2  54|1080|13617                        1
3  54|1080|13618                        1
4  54|1080|13619                        1

In [27]:
Intermediate = df[df['course_level'] == 'Intermediate']
Intermediate.head()

,Course Name,Function,Skills,Concept,course_level,Course link,CPP,Course Sylabus,product_id,Prod MP ID,Function id,skill_id,concepts,Corporate id,Course Learning mode,Duration,Duration_c,Price,Unnamed: 18,FSC_concat
472,Career Growth Habits: The Fast-Track to Promotion,Corporate Communication,Stakeholder Communication & Leadership Visibility,Leadership Message Calendar,Intermediate,https://www.smartonlinecourse.co.in/courses/Ca...,Smart Online,Lecture 1 Why Promotions Arent Just About Per...,37310,38161,90,1078,13594,[10],Self-paced (Recorded),Hours,1.0,750.0,NaN,90|1078|13594
473,Career Growth Habits: The Fast-Track to Promotion,Corporate Communication,Stakeholder Communication & Leadership Visibility,Leadership Thought Article Framework,Intermediate,https://www.smartonlinecourse.co.in/courses/Ca...,Smart Online,Lecture 1 Why Promotions Arent Just About Per...,37310,38161,90,1078,13602,[10],Self-paced (Recorded),Hours,1.0,750.0,NaN,90|1078|13602
474,Career Growth Habits: The Fast-Track to Promotion,HR Talent - Stratigic Talent,Leadership Pipeline Planning,Leadership Role Benchmarking,Intermediate,https://www.smartonlinecourse.co.in/courses/Ca...,Smart Online,Lecture 1 Why Promotions Arent Just About Per...,37310,38161,94,1123,14044,[10],Self-paced (Recorded),Hours,1.0,750.0,NaN,94|1123|14044
475,Career Growth Habits: The Fast-Track to Promotion,HR Talent - Stratigic Talent,Leadership Pipeline Planning,Core Leadership Competency Model,Intermediate,https://www.smartonlinecourse.co.in/courses/Ca...,Smart Online,Lecture 1 Why Promotions Arent Just About Per...,37310,38161,94,1123,14045,[10],Self-paced (Recorded),Hours,1.0,750.0,NaN,94|1123|14045
476,Career Growth Habits: The Fast-Track to Promotion,HRBP,Employee Grievance & Stakeholder Alignment,Leadership Advisory Role,Intermediate,https://www.smartonlinecourse.co.in/courses/Ca...,Smart Online,Lecture 1 Why Promotions Arent Just About Per...,37310,38161,95,1163,14472,[10],Self-paced (Recorded),Hours,1.0,750.0,NaN,95|1163|14472

In [28]:
result_Intermediate =  Intermediate.groupby("FSC_concat")["product_id"].nunique().reset_index()
result_Intermediate.columns = ["FSC_concat", "Function_count_intermediate"]
result_Intermediate.head()

      FSC_concat  Function_count_intermediate
0  54|1081|13625                            1
1  54|1082|13634                            2
2  54|1084|13659                            1
3  54|1157|14384                            1
4  54|1157|14385                            1

In [29]:
unique_values_df = df.drop_duplicates(subset=['FSC_concat'])
unique_values_df = unique_values_df[['FSC_concat']]
unique_values_df.head()

      FSC_concat
0  89|1062|13440
1  89|1063|13444
2  89|1063|13445
3  89|1063|13450
4  89|1067|13486

In [30]:
merged_df = pd.merge(unique_values_df, result_Beginner, on="FSC_concat", how="left")  # Merge df1 and df2
merged_df = pd.merge(merged_df, result_Intermediate, on="FSC_concat", how="left")  # Merge with df3
merged_df = pd.merge(merged_df, result_Advanced, on="FSC_concat", how="left")
merged_df.head()

,FSC_concat,Function_count_beginner,Function_count_intermediate,Function_count_Advanced
0,89|1062|13440,1.0,NaN,1.0
1,89|1063|13444,1.0,NaN,1.0
2,89|1063|13445,1.0,NaN,1.0
3,89|1063|13450,1.0,NaN,1.0
4,89|1067|13486,1.0,NaN,1.0

In [31]:
# If you're working with a single column but want to keep it as a DataFrame:
merged_df['Function_count_beginner'] = merged_df['Function_count_beginner'].fillna(0).astype(int)
merged_df['Function_count_intermediate'] = merged_df['Function_count_intermediate'].fillna(0).astype(int)
merged_df['Function_count_Advanced'] = merged_df['Function_count_Advanced'].fillna(0).astype(int)
merged_df.head()

,FSC_concat,Function_count_beginner,Function_count_intermediate,Function_count_Advanced
0,89|1062|13440,1,0,1
1,89|1063|13444,1,0,1
2,89|1063|13445,1,0,1
3,89|1063|13450,1,0,1
4,89|1067|13486,1,0,1

In [32]:
#df1['Skill ID'].unique()
#df1['FSC_concat']= df1['PRODUCTION Skill ID'].fillna(0).astype(int).astype(str)+"|"+df1['PRODUCTION Concepts ID'].fillna(0).astype(int).astype(str)
#df1.head()

In [33]:
#df1['FSC_concat'] = (
    #pd.to_numeric(df1['PRODUCTION Skill ID'], errors='coerce').fillna(0).astype(int).astype(str)
    #+ "|" + pd.to_numeric(df1['PRODUCTION Concepts ID'], errors='coerce').fillna(0).astype(int).astype(str))
#df1.head()


df1['FSC_concat'] = df1['Prod Function id'].fillna(0).astype(str) + "|" + df1['PRODUCTION Skill ID'].fillna(0).astype(int).astype(str) + "|" + (df1['PRODUCTION Concepts ID']) .fillna(0).astype(int).astype(str)
df1.head()

,Function,Prod Function id,Skill,PRODUCTION Skill ID,Concept,PRODUCTION Concepts ID,Concat,FSC_concat
0,Capability Building,88,Digital & Microlearning Tools Usage,1108,Use of AI Tools for Content Curation,13902,Capability BuildingDigital & Microlearning Too...,88|1108|13902
1,Capability Building,88,Content Development & Instructional Design,1102,Compliance & Policy Module Drafting,13842,Capability BuildingContent Development & Instr...,88|1102|13842
2,HR Compensation & Payroll,92,End-to-End Payroll & Attendance Management,1160,Confidentiality & Data Security,14427,HR Compensation & PayrollEnd-to-End Payroll & ...,92|1160|14427
3,HR Talent - Stratigic Talent,94,Talent Analytics & Predictive Insights,1119,Attrition Risk Prediction Model,14004,HR Talent - Stratigic TalentTalent Analytics &...,94|1119|14004
4,Capability Building,88,"Learning Design, Delivery & Evaluation",1162,Learning Content Customization,14454,"Capability BuildingLearning Design, Delivery &...",88|1162|14454

In [34]:
automated_df = pd.merge(df1,merged_df, on ='FSC_concat', how = 'left' )
automated_df['Function_count_beginner'] = automated_df['Function_count_beginner'].fillna(0).astype(int)
automated_df['Function_count_intermediate'] = automated_df['Function_count_intermediate'].fillna(0).astype(int)
automated_df['Function_count_Advanced'] = automated_df['Function_count_Advanced'].fillna(0).astype(int)
automated_df.head()

,Function,Prod Function id,Skill,PRODUCTION Skill ID,Concept,PRODUCTION Concepts ID,Concat,FSC_concat,Function_count_beginner,Function_count_intermediate,Function_count_Advanced
0,Capability Building,88,Digital & Microlearning Tools Usage,1108,Use of AI Tools for Content Curation,13902,Capability BuildingDigital & Microlearning Too...,88|1108|13902,3,2,1
1,Capability Building,88,Content Development & Instructional Design,1102,Compliance & Policy Module Drafting,13842,Capability BuildingContent Development & Instr...,88|1102|13842,6,4,1
2,HR Compensation & Payroll,92,End-to-End Payroll & Attendance Management,1160,Confidentiality & Data Security,14427,HR Compensation & PayrollEnd-to-End Payroll & ...,92|1160|14427,2,1,1
3,HR Talent - Stratigic Talent,94,Talent Analytics & Predictive Insights,1119,Attrition Risk Prediction Model,14004,HR Talent - Stratigic TalentTalent Analytics &...,94|1119|14004,3,0,1
4,Capability Building,88,"Learning Design, Delivery & Evaluation",1162,Learning Content Customization,14454,"Capability BuildingLearning Design, Delivery &...",88|1162|14454,4,0,1

In [35]:
automated_df.to_excel("C:\\Users\\taslim.siddiqui\\Downloads//automate_FSC_deficit_Aarti_30-12-2025.xlsx")

In [37]:
import pandas as pd
 
path =r"C:\Users\taslim.siddiqui\Downloads\Aarti_file_input.xlsx"
df = pd.read_excel(path, sheet_name='Sheet1')
 
# cpp_value = "HH+Other"   # <-- change if needed
# df_f = df[df["CPP"].astype(str).str.strip().eq(cpp_value)]
 
# --- PIVOT: Function x Proficiency, distinct count of concepts ---
pivot = pd.pivot_table(
    df,
    index=['Function'],
    columns=['course_level'],
    values="concepts"
,          # use "Concept" if you want distinct by concept name
    aggfunc=pd.Series.nunique,    # distinct count
    fill_value=0
)
 
pivot_out = pivot.reset_index()
 
print(pivot_out.head())
pivot_out.to_excel(r"C:\Users\taslim.siddiqui\Downloads\pivot_1.xlsx")

course_level                 Function  Advanced  Beginner  Intermediate
0                      Administration        17        42             6
1                 Capability Building        70       105            24
2                   Corporate Affairs        50        53            10
3             Corporate Communication        72        87            76
4                 Employee Experience        47        96            45

In [ ]:
print("df1 dup keys:", df1['FSC_concat'].duplicated().sum())
print("merged_df dup keys:", merged_df['FSC_concat'].duplicated().sum())
print("Any 0-keys in df1:", df1['FSC_concat'].str.startswith("0|").sum(), df1['FSC_concat'].str.contains("|0|", regex=False).sum())
df1.to_excel(r"C:\Users\taslim.siddiqui\Downloads\FSC_concat.xlsx")

df1 dup keys: 0
merged_df dup keys: 0
Any 0-keys in df1: 0 0