# FSC Deficiet

In [3]:
import pandas as pd

In [4]:
#Function,Prod Function ID,Skill,PRODUCTION Skill ID,Skill Description,Concept,Concept Description,PRODUCTION Concepts ID,Concat,product_id


#load FSC master excel
df1 = pd.read_excel(r"C:\Users\taslim.siddiqui\Downloads\Aarti Course + Deficit Tracker_Data added 07.01,26.xlsx",sheet_name='Aarti FSC Master')
df1.head()

,Function,Prod Function id,Skill,PRODUCTION Skill ID,Concept,PRODUCTION Concepts ID
0,Capability Building,88,Digital & Microlearning Tools Usage,1108,Use of AI Tools for Content Curation,13902
1,Capability Building,88,Content Development & Instructional Design,1102,Compliance & Policy Module Drafting,13842
2,HR Compensation & Payroll,92,End-to-End Payroll & Attendance Management,1160,Confidentiality & Data Security,14427
3,HR Talent - Stratigic Talent,94,Talent Analytics & Predictive Insights,1119,Attrition Risk Prediction Model,14004
4,Capability Building,88,"Learning Design, Delivery & Evaluation",1162,Learning Content Customization,14454

In [5]:
#product_name,course_level,skill_id,concepts,product_id
#load data file
df2 = pd.read_excel(r"C:\Users\taslim.siddiqui\Downloads\Aarti Course + Deficit Tracker_Data added 07.01,26.xlsx",sheet_name='HH+Other CPP Master')
df2

,Course Name,Function,Skill,Concept,course_level,Course link,CPP,Course Sylabus,product_id,Prod MP ID,Function id,skill_id,concepts,Corporate id,Course Learning mode,Duration,Duration_c,Price,Client ID,Unnamed: 19
0,"ACCA Course Training (Skill level, Self Paced ...",Corporate Affairs,Statutory Compliance & Licensing Management,Authority Approval Flow Design,Beginner,https://www.henryharvin.com/acca-course,Henry Harvin,Module 1: Business and Technology<br>The busin...,33362,39141,89,1062,13440,[10],Self-paced (Recorded),Hours,180.0,249000.0,NaN,NaN
1,"ACCA Course Training (Skill level, Self Paced ...",Corporate Affairs,Legal & Regulatory Framework Awareness,Regulatory Framework Interpretation,Beginner,https://www.henryharvin.com/acca-course,Henry Harvin,Module 1: Business and Technology<br>The busin...,33362,39141,89,1063,13444,[10],Self-paced (Recorded),Hours,180.0,249000.0,NaN,NaN
2,"ACCA Course Training (Skill level, Self Paced ...",Corporate Affairs,Legal & Regulatory Framework Awareness,Policy Change Watch,Beginner,https://www.henryharvin.com/acca-course,Henry Harvin,Module 1: Business and Technology<br>The busin...,33362,39141,89,1063,13445,[10],Self-paced (Recorded),Hours,180.0,249000.0,NaN,NaN
3,"ACCA Course Training (Skill level, Self Paced ...",Corporate Affairs,Legal & Regulatory Framework Awareness,Case Precedent Monitoring,Beginner,https://www.henryharvin.com/acca-course,Henry Harvin,Module 1: Business and Technology<br>The busin...,33362,39141,89,1063,13450,[10],Self-paced (Recorded),Hours,180.0,249000.0,NaN,NaN
4,"ACCA Course Training (Skill level, Self Paced ...",Corporate Affairs,Crisis Management & Business Continuity Alignment,Continuity Risk Register,Beginner,https://www.henryharvin.com/acca-course,Henry Harvin,Module 1: Business and Technology<br>The busin...,33362,39141,89,1067,13486,[10],Self-paced (Recorded),Hours,180.0,249000.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4127,CIPD UK Training Course,HRIS,AI & Automation,Chatbots for HR Queries,Intermediate,https://www.henryharvin.com/cipd-course,Henry Harvin,Module 1: CIPD Level 3: Foundation<br>- CIPD L...,11130,39238,96,1184,14700,[10],Self-paced (Recorded),Hours,192.0,69500.0,11198,7.01
4128,Cyber Security Professional Course,HRIS,AI & Automation,Fraud Detection in HR Processes,Intermediate,https://www.henryharvin.com/cyber-security-course,Henry Harvin,Cyber Security Professional Course Curriculum<...,8032,39178,96,1184,14707,[10],Self-paced (Recorded),Hours,288.0,129000.0,CCSP,7.01
4129,Core HR Certification Course,Administration,Travel Management,Booking & Ticketing Coordination,Intermediate,https://academy.keka.com/courses/core-hr/,Keka Academy,Module 1: Introduction & Agenda<br>- Understan...,37852,39144,54,1187,14730,[10],Self-paced (Recorded),Hours,3.0,1.0,NaN,7.01
4130,Core HR Certification Course,Administration,Travel Management,Travel Data & Reporting,Intermediate,https://academy.keka.com/courses/core-hr/,Keka Academy,Module 1: Introduction & Agenda<br>- Understan...,37852,39144,54,1187,14737,[10],Self-paced (Recorded),Hours,3.0,1.0,NaN,7.01
4131,Core HR Certification Course,Administration,Travel Management,Digital Tools for Travel Management,Intermediate,https://academy.keka.com/courses/core-hr/,Keka Academy,Module 1: Introduction & Agenda<br>- Understan...,37852,39144,54,1187,14738,[10],Self-paced (Recorded),Hours,3.0,1.0,NaN,7.01

In [6]:
df1['PRODUCTION Concepts ID'].value_counts()

PRODUCTION Concepts ID
13902    1
13926    1
13957    1
13956    1
13955    1
        ..
13587    1
13586    1
13563    1
13508    1
14738    1
Name: count, Length: 1305, dtype: int64

If We want to remove some CPPs

In [7]:
# df2# data is the file which will only have CPP names

# # List of values to check
# values_to_check = ['Coursera','GVC','Gyanodaya Virtual Campus','CIEL','Percipio']

# # Check if any values in the DataFrame are in the list
# df2['CPP_ABC'] = df2['CPP Name'].isin(values_to_check)
# df2 = df2.query("CPP_ABC == False")
# df2

In [8]:
# Concept Column Row splitting code
df2['concepts'] = df2['concepts'].apply(
    lambda x: [int(i.strip()) for i in x.split(',')] if isinstance(x, str) else x
)

# Explode the 'concepts' column to create separate rows
df = df2.explode('concepts', ignore_index=True)
df['concepts'] = df['concepts'].fillna(0).astype(int)


df

,Course Name,Function,Skill,Concept,course_level,Course link,CPP,Course Sylabus,product_id,Prod MP ID,Function id,skill_id,concepts,Corporate id,Course Learning mode,Duration,Duration_c,Price,Client ID,Unnamed: 19
0,"ACCA Course Training (Skill level, Self Paced ...",Corporate Affairs,Statutory Compliance & Licensing Management,Authority Approval Flow Design,Beginner,https://www.henryharvin.com/acca-course,Henry Harvin,Module 1: Business and Technology<br>The busin...,33362,39141,89,1062,13440,[10],Self-paced (Recorded),Hours,180.0,249000.0,NaN,NaN
1,"ACCA Course Training (Skill level, Self Paced ...",Corporate Affairs,Legal & Regulatory Framework Awareness,Regulatory Framework Interpretation,Beginner,https://www.henryharvin.com/acca-course,Henry Harvin,Module 1: Business and Technology<br>The busin...,33362,39141,89,1063,13444,[10],Self-paced (Recorded),Hours,180.0,249000.0,NaN,NaN
2,"ACCA Course Training (Skill level, Self Paced ...",Corporate Affairs,Legal & Regulatory Framework Awareness,Policy Change Watch,Beginner,https://www.henryharvin.com/acca-course,Henry Harvin,Module 1: Business and Technology<br>The busin...,33362,39141,89,1063,13445,[10],Self-paced (Recorded),Hours,180.0,249000.0,NaN,NaN
3,"ACCA Course Training (Skill level, Self Paced ...",Corporate Affairs,Legal & Regulatory Framework Awareness,Case Precedent Monitoring,Beginner,https://www.henryharvin.com/acca-course,Henry Harvin,Module 1: Business and Technology<br>The busin...,33362,39141,89,1063,13450,[10],Self-paced (Recorded),Hours,180.0,249000.0,NaN,NaN
4,"ACCA Course Training (Skill level, Self Paced ...",Corporate Affairs,Crisis Management & Business Continuity Alignment,Continuity Risk Register,Beginner,https://www.henryharvin.com/acca-course,Henry Harvin,Module 1: Business and Technology<br>The busin...,33362,39141,89,1067,13486,[10],Self-paced (Recorded),Hours,180.0,249000.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4127,CIPD UK Training Course,HRIS,AI & Automation,Chatbots for HR Queries,Intermediate,https://www.henryharvin.com/cipd-course,Henry Harvin,Module 1: CIPD Level 3: Foundation<br>- CIPD L...,11130,39238,96,1184,14700,[10],Self-paced (Recorded),Hours,192.0,69500.0,11198,7.01
4128,Cyber Security Professional Course,HRIS,AI & Automation,Fraud Detection in HR Processes,Intermediate,https://www.henryharvin.com/cyber-security-course,Henry Harvin,Cyber Security Professional Course Curriculum<...,8032,39178,96,1184,14707,[10],Self-paced (Recorded),Hours,288.0,129000.0,CCSP,7.01
4129,Core HR Certification Course,Administration,Travel Management,Booking & Ticketing Coordination,Intermediate,https://academy.keka.com/courses/core-hr/,Keka Academy,Module 1: Introduction & Agenda<br>- Understan...,37852,39144,54,1187,14730,[10],Self-paced (Recorded),Hours,3.0,1.0,NaN,7.01
4130,Core HR Certification Course,Administration,Travel Management,Travel Data & Reporting,Intermediate,https://academy.keka.com/courses/core-hr/,Keka Academy,Module 1: Introduction & Agenda<br>- Understan...,37852,39144,54,1187,14737,[10],Self-paced (Recorded),Hours,3.0,1.0,NaN,7.01
4131,Core HR Certification Course,Administration,Travel Management,Digital Tools for Travel Management,Intermediate,https://academy.keka.com/courses/core-hr/,Keka Academy,Module 1: Introduction & Agenda<br>- Understan...,37852,39144,54,1187,14738,[10],Self-paced (Recorded),Hours,3.0,1.0,NaN,7.01

In [9]:
# Concept Column Row splitting code
df2['concepts'] = df2['concepts'].apply(
    lambda x: [int(i.strip()) for i in x.split(',')] if isinstance(x, str) else x
)

# Explode the 'concepts' column to create separate rows
df = df2.explode('concepts', ignore_index=True)
df['concepts'] = df['concepts'].fillna(0).astype(int)


df

,Course Name,Function,Skill,Concept,course_level,Course link,CPP,Course Sylabus,product_id,Prod MP ID,Function id,skill_id,concepts,Corporate id,Course Learning mode,Duration,Duration_c,Price,Client ID,Unnamed: 19
0,"ACCA Course Training (Skill level, Self Paced ...",Corporate Affairs,Statutory Compliance & Licensing Management,Authority Approval Flow Design,Beginner,https://www.henryharvin.com/acca-course,Henry Harvin,Module 1: Business and Technology<br>The busin...,33362,39141,89,1062,13440,[10],Self-paced (Recorded),Hours,180.0,249000.0,NaN,NaN
1,"ACCA Course Training (Skill level, Self Paced ...",Corporate Affairs,Legal & Regulatory Framework Awareness,Regulatory Framework Interpretation,Beginner,https://www.henryharvin.com/acca-course,Henry Harvin,Module 1: Business and Technology<br>The busin...,33362,39141,89,1063,13444,[10],Self-paced (Recorded),Hours,180.0,249000.0,NaN,NaN
2,"ACCA Course Training (Skill level, Self Paced ...",Corporate Affairs,Legal & Regulatory Framework Awareness,Policy Change Watch,Beginner,https://www.henryharvin.com/acca-course,Henry Harvin,Module 1: Business and Technology<br>The busin...,33362,39141,89,1063,13445,[10],Self-paced (Recorded),Hours,180.0,249000.0,NaN,NaN
3,"ACCA Course Training (Skill level, Self Paced ...",Corporate Affairs,Legal & Regulatory Framework Awareness,Case Precedent Monitoring,Beginner,https://www.henryharvin.com/acca-course,Henry Harvin,Module 1: Business and Technology<br>The busin...,33362,39141,89,1063,13450,[10],Self-paced (Recorded),Hours,180.0,249000.0,NaN,NaN
4,"ACCA Course Training (Skill level, Self Paced ...",Corporate Affairs,Crisis Management & Business Continuity Alignment,Continuity Risk Register,Beginner,https://www.henryharvin.com/acca-course,Henry Harvin,Module 1: Business and Technology<br>The busin...,33362,39141,89,1067,13486,[10],Self-paced (Recorded),Hours,180.0,249000.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4127,CIPD UK Training Course,HRIS,AI & Automation,Chatbots for HR Queries,Intermediate,https://www.henryharvin.com/cipd-course,Henry Harvin,Module 1: CIPD Level 3: Foundation<br>- CIPD L...,11130,39238,96,1184,14700,[10],Self-paced (Recorded),Hours,192.0,69500.0,11198,7.01
4128,Cyber Security Professional Course,HRIS,AI & Automation,Fraud Detection in HR Processes,Intermediate,https://www.henryharvin.com/cyber-security-course,Henry Harvin,Cyber Security Professional Course Curriculum<...,8032,39178,96,1184,14707,[10],Self-paced (Recorded),Hours,288.0,129000.0,CCSP,7.01
4129,Core HR Certification Course,Administration,Travel Management,Booking & Ticketing Coordination,Intermediate,https://academy.keka.com/courses/core-hr/,Keka Academy,Module 1: Introduction & Agenda<br>- Understan...,37852,39144,54,1187,14730,[10],Self-paced (Recorded),Hours,3.0,1.0,NaN,7.01
4130,Core HR Certification Course,Administration,Travel Management,Travel Data & Reporting,Intermediate,https://academy.keka.com/courses/core-hr/,Keka Academy,Module 1: Introduction & Agenda<br>- Understan...,37852,39144,54,1187,14737,[10],Self-paced (Recorded),Hours,3.0,1.0,NaN,7.01
4131,Core HR Certification Course,Administration,Travel Management,Digital Tools for Travel Management,Intermediate,https://academy.keka.com/courses/core-hr/,Keka Academy,Module 1: Introduction & Agenda<br>- Understan...,37852,39144,54,1187,14738,[10],Self-paced (Recorded),Hours,3.0,1.0,NaN,7.01

In [10]:
# Renaming Flexible to Beginner in Course level column
df['course_level'] = df['course_level'].replace('Flexible', 'Beginner')

In [11]:
df['course_level'].unique()

array(['Beginner', 'Advanced', 'Intermediate'], dtype=object)

In [12]:
# Concat of Skill Concept
#df['FSC_concat'] = df['skill_id'].astype(str)+'|'+df['concepts'].astype(str)
#df['FSC_concat'] = df['concepts'].astype(str)
df['FSC_concat'] =  df['Function id'].astype(str) + '|'+  df['skill_id'].astype(str)+'|'+df['concepts'].astype(str)
df['FSC_concat']

0       89|1062|13440
1       89|1063|13444
2       89|1063|13445
3       89|1063|13450
4       89|1067|13486
            ...
4127    96|1184|14700
4128    96|1184|14707
4129    54|1187|14730
4130    54|1187|14737
4131    54|1187|14738
Name: FSC_concat, Length: 4132, dtype: object

In [13]:
uniquedf = df.drop_duplicates(subset=['FSC_concat'])
uniquedf=uniquedf['FSC_concat']
uniquedf

0       89|1062|13440
1       89|1063|13444
2       89|1063|13445
3       89|1063|13450
4       89|1067|13486
            ...
4115    97|1153|14344
4117    54|1159|14404
4119    54|1159|14410
4129    54|1187|14730
4131    54|1187|14738
Name: FSC_concat, Length: 1255, dtype: object

In [14]:
# Making new dataframe of Advanced course level only.
Advanced = df[df['course_level'] == 'Advanced']
Advanced

,Course Name,Function,Skill,Concept,course_level,Course link,CPP,Course Sylabus,product_id,Prod MP ID,...,skill_id,concepts,Corporate id,Course Learning mode,Duration,Duration_c,Price,Client ID,Unnamed: 19,FSC_concat
28,Advanced Certification in Core HR Specialist -...,HR Compensation & Payroll,Cost Modeling & Manpower Budgeting,Cost-per-Employee Calculator,Advanced,https://www.henryharvin.com/advanced-certifica...,Henry Harvin,Module 1: Understanding HR Analytics<br>Module...,33156,38912,...,1090,13717,[10],Self-paced (Recorded),Hours,192.0,89500.0,NaN,NaN,92|1090|13717
29,Advanced Certification in Core HR Specialist -...,HR Compensation & Payroll,Cost Modeling & Manpower Budgeting,Budget Presentation Dashboards,Advanced,https://www.henryharvin.com/advanced-certifica...,Henry Harvin,Module 1: Understanding HR Analytics<br>Module...,33156,38912,...,1090,13723,[10],Self-paced (Recorded),Hours,192.0,89500.0,NaN,NaN,92|1090|13723
30,Advanced Certification in Core HR Specialist -...,HR Compensation & Payroll,Payroll System Configuration & Automation,Payroll Engine Testing Sandbox,Advanced,https://www.henryharvin.com/advanced-certifica...,Henry Harvin,Module 1: Understanding HR Analytics<br>Module...,33156,38912,...,1091,13732,[10],Self-paced (Recorded),Hours,192.0,89500.0,NaN,NaN,92|1091|13732
31,Advanced Certification in Core HR Specialist -...,Capability Building,Learning Data & Reporting Analytics,Cost per Participant Calculator,Advanced,https://www.henryharvin.com/advanced-certifica...,Henry Harvin,Module 1: Understanding HR Analytics<br>Module...,33156,38912,...,1107,13887,[10],Self-paced (Recorded),Hours,192.0,89500.0,NaN,NaN,88|1107|13887
32,Advanced Certification in Core HR Specialist -...,Capability Building,Internal Capability Building Communication,Certificate Distribution Workflow,Advanced,https://www.henryharvin.com/advanced-certifica...,Henry Harvin,Module 1: Understanding HR Analytics<br>Module...,33156,38912,...,1109,13907,[10],Self-paced (Recorded),Hours,192.0,89500.0,NaN,NaN,88|1109|13907
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4004,Certified Human Resource Professional (CHRP) C...,TA & OM,Organisation Master Data Management,Reporting Line Correction Protocol,Advanced,https://www.henryharvin.com/chrp-course,Henry Harvin,Module 1: HR Operations<br>- Introduction to s...,33139,38803,...,1154,14358,[10],Self-paced (Recorded),Hours,244.0,120052.0,NaN,7.01,97|1154|14358
4005,Certified Human Resource Professional (CHRP) C...,TA & OM,Internal Mobility & Succession Backfill Planning,Internal Talent Inventory Tracker,Advanced,https://www.henryharvin.com/chrp-course,Henry Harvin,Module 1: HR Operations<br>- Introduction to s...,33139,38804,...,1155,14365,[10],Self-paced (Recorded),Hours,245.0,120053.0,NaN,7.01,97|1155|14365
4006,Certified Human Resource Professional (CHRP) C...,TA & OM,Internal Mobility & Succession Backfill Planning,Backfill Tracker Sheet,Advanced,https://www.henryharvin.com/chrp-course,Henry Harvin,Module 1: HR Operations<br>- Introduction to s...,33139,38805,...,1155,14366,[10],Self-paced (Recorded),Hours,246.0,120054.0,NaN,7.01,97|1155|14366
4007,Certified Human Resource Professional (CHRP) C...,Employee Experience,Annual Engagement Survey Rollout Plan,Leadership Reporting Templates,Advanced,https://www.henryharvin.com/chrp-course,Henry Harvin,Module 1: HR Operations<br>- Introduction to s...,33139,38806,...,1176,14627,[10],Self-paced (Recorded),Hours,247.0,120055.0,NaN,7.01,91|1176|14627
4008,Certified Human Resource Professional (CHRP) C...,Employee Experience,Survey Platform Administration,Vendor Coordination,Advanced,https://www.henryharvin.com/chrp-course,Henry Harvin,Module 1: HR Operations<br>- Introduction to s...,33139,38807,...,1178,14647,[10],Self-paced (Recorded),Hours,248.0,120056.0,NaN,7.01,91|1178|14647

In [15]:
# Counting the number of courses in Advanced course level against the FSC_concat column.
result_Advanced =  Advanced.groupby("FSC_concat")["product_id"].nunique().reset_index()
result_Advanced.columns = ["FSC_concat", "Function_count_Advanced"]
result_Advanced.head()

      FSC_concat  Function_count_Advanced
0  54|1080|13614                        1
1  54|1080|13615                        1
2  54|1080|13616                        1
3  54|1080|13617                        1
4  54|1080|13618                        1

In [16]:
Beginner = df[df['course_level'] == 'Beginner']
Beginner

,Course Name,Function,Skill,Concept,course_level,Course link,CPP,Course Sylabus,product_id,Prod MP ID,...,skill_id,concepts,Corporate id,Course Learning mode,Duration,Duration_c,Price,Client ID,Unnamed: 19,FSC_concat
0,"ACCA Course Training (Skill level, Self Paced ...",Corporate Affairs,Statutory Compliance & Licensing Management,Authority Approval Flow Design,Beginner,https://www.henryharvin.com/acca-course,Henry Harvin,Module 1: Business and Technology<br>The busin...,33362,39141,...,1062,13440,[10],Self-paced (Recorded),Hours,180.00,249000.0,NaN,NaN,89|1062|13440
1,"ACCA Course Training (Skill level, Self Paced ...",Corporate Affairs,Legal & Regulatory Framework Awareness,Regulatory Framework Interpretation,Beginner,https://www.henryharvin.com/acca-course,Henry Harvin,Module 1: Business and Technology<br>The busin...,33362,39141,...,1063,13444,[10],Self-paced (Recorded),Hours,180.00,249000.0,NaN,NaN,89|1063|13444
2,"ACCA Course Training (Skill level, Self Paced ...",Corporate Affairs,Legal & Regulatory Framework Awareness,Policy Change Watch,Beginner,https://www.henryharvin.com/acca-course,Henry Harvin,Module 1: Business and Technology<br>The busin...,33362,39141,...,1063,13445,[10],Self-paced (Recorded),Hours,180.00,249000.0,NaN,NaN,89|1063|13445
3,"ACCA Course Training (Skill level, Self Paced ...",Corporate Affairs,Legal & Regulatory Framework Awareness,Case Precedent Monitoring,Beginner,https://www.henryharvin.com/acca-course,Henry Harvin,Module 1: Business and Technology<br>The busin...,33362,39141,...,1063,13450,[10],Self-paced (Recorded),Hours,180.00,249000.0,NaN,NaN,89|1063|13450
4,"ACCA Course Training (Skill level, Self Paced ...",Corporate Affairs,Crisis Management & Business Continuity Alignment,Continuity Risk Register,Beginner,https://www.henryharvin.com/acca-course,Henry Harvin,Module 1: Business and Technology<br>The busin...,33362,39141,...,1067,13486,[10],Self-paced (Recorded),Hours,180.00,249000.0,NaN,NaN,89|1067|13486
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3838,Business Performance Management,Administration,Accommodation (Guest House and Hotels),Cost Monitoring,Beginner,https://www.eduonix.com/business-performance-m...,Eduonix learning Solutions,Section 1 : Business Performance Management<br...,37955,39218,...,1158,14399,[10],Self-paced (Recorded),Hours,2.15,2348.0,7428,6.01,54|1158|14399
3839,Business Performance Management,Administration,Facility Coordination,Space Utilization Planning,Beginner,https://www.eduonix.com/business-performance-m...,Eduonix learning Solutions,Section 1 : Business Performance Management<br...,37955,39218,...,1159,14407,[10],Self-paced (Recorded),Hours,2.15,2348.0,7428,6.01,54|1159|14407
3840,Business Performance Management,Administration,Employee Transportation,Cost & Fuel Efficiency Monitoring,Beginner,https://www.eduonix.com/business-performance-m...,Eduonix learning Solutions,Section 1 : Business Performance Management<br...,37955,39218,...,1169,14554,[10],Self-paced (Recorded),Hours,2.15,2348.0,7428,6.01,54|1169|14554
3841,Employee Relation and Engagement-Manage and En...,Capability Building,Learning Technology & Platforms,Virtual Classroom Tools,Beginner,https://www.eduonix.com/employee-relation-and-...,Eduonix learning Solutions,Section 1 : Introduction<br>Introduction to Em...,37851,39211,...,1173,14593,[10],Self-paced (Recorded),Hours,7.37,2348.0,7428,6.01,88|1173|14593
3842,AI in HR Certification Course,Employee Experience,Annual Engagement Survey Rollout Plan,Multi-Language Rollout,Beginner,https://academy.keka.com/courses/ai-in-hr/,Keka Academy,Module 1: Introduction<br>- Understand how HR ...,37815,39137,...,1176,14622,[10],Self-paced (Recorded),Hours,1.50,1.0,NaN,6.01,91|1176|14622

In [17]:
result_Beginner =  Beginner.groupby("FSC_concat")["product_id"].nunique().reset_index()
result_Beginner.columns = ["FSC_concat", "Function_count_beginner"]
result_Beginner.head()

      FSC_concat  Function_count_beginner
0  54|1080|13614                        1
1  54|1080|13616                        1
2  54|1080|13617                        1
3  54|1080|13618                        1
4  54|1080|13619                        1

In [18]:
Intermediate = df[df['course_level'] == 'Intermediate']
Intermediate.head()

,Course Name,Function,Skill,Concept,course_level,Course link,CPP,Course Sylabus,product_id,Prod MP ID,...,skill_id,concepts,Corporate id,Course Learning mode,Duration,Duration_c,Price,Client ID,Unnamed: 19,FSC_concat
472,Career Growth Habits: The Fast-Track to Promotion,Corporate Communication,Stakeholder Communication & Leadership Visibility,Leadership Message Calendar,Intermediate,https://www.smartonlinecourse.co.in/courses/Ca...,Smart Online,Lecture 1 Why Promotions Arent Just About Per...,37310,38161,...,1078,13594,[10],Self-paced (Recorded),Hours,1.0,750.0,NaN,NaN,90|1078|13594
473,Career Growth Habits: The Fast-Track to Promotion,Corporate Communication,Stakeholder Communication & Leadership Visibility,Leadership Thought Article Framework,Intermediate,https://www.smartonlinecourse.co.in/courses/Ca...,Smart Online,Lecture 1 Why Promotions Arent Just About Per...,37310,38161,...,1078,13602,[10],Self-paced (Recorded),Hours,1.0,750.0,NaN,NaN,90|1078|13602
474,Career Growth Habits: The Fast-Track to Promotion,HR Talent - Stratigic Talent,Leadership Pipeline Planning,Leadership Role Benchmarking,Intermediate,https://www.smartonlinecourse.co.in/courses/Ca...,Smart Online,Lecture 1 Why Promotions Arent Just About Per...,37310,38161,...,1123,14044,[10],Self-paced (Recorded),Hours,1.0,750.0,NaN,NaN,94|1123|14044
475,Career Growth Habits: The Fast-Track to Promotion,HR Talent - Stratigic Talent,Leadership Pipeline Planning,Core Leadership Competency Model,Intermediate,https://www.smartonlinecourse.co.in/courses/Ca...,Smart Online,Lecture 1 Why Promotions Arent Just About Per...,37310,38161,...,1123,14045,[10],Self-paced (Recorded),Hours,1.0,750.0,NaN,NaN,94|1123|14045
476,Career Growth Habits: The Fast-Track to Promotion,HRBP,Employee Grievance & Stakeholder Alignment,Leadership Advisory Role,Intermediate,https://www.smartonlinecourse.co.in/courses/Ca...,Smart Online,Lecture 1 Why Promotions Arent Just About Per...,37310,38161,...,1163,14472,[10],Self-paced (Recorded),Hours,1.0,750.0,NaN,NaN,95|1163|14472

In [19]:
result_Intermediate =  Intermediate.groupby("FSC_concat")["product_id"].nunique().reset_index()
result_Intermediate.columns = ["FSC_concat", "Function_count_intermediate"]
result_Intermediate.head()

      FSC_concat  Function_count_intermediate
0  54|1080|13614                            1
1  54|1080|13615                            1
2  54|1080|13617                            1
3  54|1080|13619                            1
4  54|1080|13623                            1

In [20]:
unique_values_df = df.drop_duplicates(subset=['FSC_concat'])
unique_values_df = unique_values_df[['FSC_concat']]
unique_values_df.head()

      FSC_concat
0  89|1062|13440
1  89|1063|13444
2  89|1063|13445
3  89|1063|13450
4  89|1067|13486

In [21]:
merged_df = pd.merge(unique_values_df, result_Beginner, on="FSC_concat", how="left")  # Merge df1 and df2
merged_df = pd.merge(merged_df, result_Intermediate, on="FSC_concat", how="left")  # Merge with df3
merged_df = pd.merge(merged_df, result_Advanced, on="FSC_concat", how="left")
merged_df.head()

,FSC_concat,Function_count_beginner,Function_count_intermediate,Function_count_Advanced
0,89|1062|13440,1.0,1.0,1.0
1,89|1063|13444,1.0,1.0,1.0
2,89|1063|13445,1.0,1.0,1.0
3,89|1063|13450,1.0,1.0,1.0
4,89|1067|13486,1.0,1.0,1.0

In [22]:
# If you're working with a single column but want to keep it as a DataFrame:
merged_df['Function_count_beginner'] = merged_df['Function_count_beginner'].fillna(0).astype(int)
merged_df['Function_count_intermediate'] = merged_df['Function_count_intermediate'].fillna(0).astype(int)
merged_df['Function_count_Advanced'] = merged_df['Function_count_Advanced'].fillna(0).astype(int)
merged_df.head()

,FSC_concat,Function_count_beginner,Function_count_intermediate,Function_count_Advanced
0,89|1062|13440,1,1,1
1,89|1063|13444,1,1,1
2,89|1063|13445,1,1,1
3,89|1063|13450,1,1,1
4,89|1067|13486,1,1,1

In [23]:
#df1['Skill ID'].unique()
#df1['FSC_concat']= df1['PRODUCTION Skill ID'].fillna(0).astype(int).astype(str)+"|"+df1['PRODUCTION Concepts ID'].fillna(0).astype(int).astype(str)
#df1.head()

In [24]:
#df1['FSC_concat'] = (
    #pd.to_numeric(df1['PRODUCTION Skill ID'], errors='coerce').fillna(0).astype(int).astype(str)
    #+ "|" + pd.to_numeric(df1['PRODUCTION Concepts ID'], errors='coerce').fillna(0).astype(int).astype(str))
#df1.head()


df1['FSC_concat'] = df1['Prod Function id'].fillna(0).astype(str) + "|" + df1['PRODUCTION Skill ID'].fillna(0).astype(int).astype(str) + "|" + (df1['PRODUCTION Concepts ID']) .fillna(0).astype(int).astype(str)
df1.head()

,Function,Prod Function id,Skill,PRODUCTION Skill ID,Concept,PRODUCTION Concepts ID,FSC_concat
0,Capability Building,88,Digital & Microlearning Tools Usage,1108,Use of AI Tools for Content Curation,13902,88|1108|13902
1,Capability Building,88,Content Development & Instructional Design,1102,Compliance & Policy Module Drafting,13842,88|1102|13842
2,HR Compensation & Payroll,92,End-to-End Payroll & Attendance Management,1160,Confidentiality & Data Security,14427,92|1160|14427
3,HR Talent - Stratigic Talent,94,Talent Analytics & Predictive Insights,1119,Attrition Risk Prediction Model,14004,94|1119|14004
4,Capability Building,88,"Learning Design, Delivery & Evaluation",1162,Learning Content Customization,14454,88|1162|14454

In [25]:
automated_df = pd.merge(df1,merged_df, on ='FSC_concat', how = 'left' )
automated_df['Function_count_beginner'] = automated_df['Function_count_beginner'].fillna(0).astype(int)
automated_df['Function_count_intermediate'] = automated_df['Function_count_intermediate'].fillna(0).astype(int)
automated_df['Function_count_Advanced'] = automated_df['Function_count_Advanced'].fillna(0).astype(int)
automated_df.head()

,Function,Prod Function id,Skill,PRODUCTION Skill ID,Concept,PRODUCTION Concepts ID,FSC_concat,Function_count_beginner,Function_count_intermediate,Function_count_Advanced
0,Capability Building,88,Digital & Microlearning Tools Usage,1108,Use of AI Tools for Content Curation,13902,88|1108|13902,3,2,1
1,Capability Building,88,Content Development & Instructional Design,1102,Compliance & Policy Module Drafting,13842,88|1102|13842,6,4,1
2,HR Compensation & Payroll,92,End-to-End Payroll & Attendance Management,1160,Confidentiality & Data Security,14427,92|1160|14427,2,1,1
3,HR Talent - Stratigic Talent,94,Talent Analytics & Predictive Insights,1119,Attrition Risk Prediction Model,14004,94|1119|14004,3,1,1
4,Capability Building,88,"Learning Design, Delivery & Evaluation",1162,Learning Content Customization,14454,88|1162|14454,4,1,1

In [26]:
automated_df.to_excel("C:\\Users\\taslim.siddiqui\\Downloads//automate_FSC_deficit_Aarti_08-01-2026.xlsx")

In [28]:
import pandas as pd
 
path =(r"C:\Users\taslim.siddiqui\Downloads\Aarti Course + Deficit Tracker_Data added 07.01,26.xlsx")
df = pd.read_excel(path, sheet_name='HH+Other CPP Master')
 
# cpp_value = "HH+Other"   # <-- change if needed
# df_f = df[df["CPP"].astype(str).str.strip().eq(cpp_value)]
 
# --- PIVOT: Function x Proficiency, distinct count of concepts ---
pivot = pd.pivot_table(
    df,
    index=['Function'],
    columns=['course_level'],
    values="concepts"
,          # use "Concept" if you want distinct by concept name
    aggfunc=pd.Series.nunique,    # distinct count
    fill_value=0
)
 
pivot_out = pivot.reset_index()
 
print(pivot_out.head())
pivot_out.to_excel(r"C:\Users\taslim.siddiqui\Downloads\pivot_1.xlsx")

course_level                 Function  Advanced  Beginner  Intermediate
0                      Administration        67        53            63
1                 Capability Building       130       127           123
2                   Corporate Affairs        77        70            70
3             Corporate Communication       101       101            99
4                 Employee Experience        99       103           104

In [ ]:
print("df1 dup keys:", df1['FSC_concat'].duplicated().sum())
print("merged_df dup keys:", merged_df['FSC_concat'].duplicated().sum())
print("Any 0-keys in df1:", df1['FSC_concat'].str.startswith("0|").sum(), df1['FSC_concat'].str.contains("|0|", regex=False).sum())
df1.to_excel(r"C:\Users\taslim.siddiqui\Downloads\FSC_concat.xlsx")

df1 dup keys: 0
merged_df dup keys: 0
Any 0-keys in df1: 0 0