# FSC Deficiet

In [14]:
import pandas as pd

In [15]:
#Function,Prod Function ID,Skill,PRODUCTION Skill ID,Skill Description,Concept,Concept Description,PRODUCTION Concepts ID,Concat,product_id


#load FSC master excel
df1 = pd.read_excel(r"C:\Users\taslim.siddiqui\Downloads\RDSLC - Assurance - Risk Academy - Internal.xlsx",sheet_name='RSL')
df1.head()

,Function,Department,Function.1,Function id,Role,Role alias,Proficiency,Skill,Level,Skill Description,Skill.1,Concept,Concept Description,Concept.1,Concat
0,Commercial Bank,Business Process Risk & Control Assurance,Assurance - Risk,1069,RCU HO Team Member,Manager - RCU HO Team Member,Master,Process Assurance Oversight,L3,Ensures processes are reviewed against defined...,10644,Process Assurance Frameworks,Structured approaches for validating process i...,137306,Process Assurance OversightProcess Assurance F...
1,Commercial Bank,Business Process Risk & Control Assurance,Assurance - Risk,1069,RCU HO Team Member,Manager - RCU HO Team Member,Master,Process Assurance Oversight,L3,Ensures processes are reviewed against defined...,10644,Process Compliance Verification,Assessment of whether processes are executed i...,137307,Process Assurance OversightProcess Compliance ...
2,Commercial Bank,Business Process Risk & Control Assurance,Assurance - Risk,1069,RCU HO Team Member,Manager - RCU HO Team Member,Master,Process Assurance Oversight,L3,Ensures processes are reviewed against defined...,10644,SOP Adherence Assessment,Evaluation of whether operational activities f...,137308,Process Assurance OversightSOP Adherence Asses...
3,Commercial Bank,Business Process Risk & Control Assurance,Assurance - Risk,1069,RCU HO Team Member,Manager - RCU HO Team Member,Master,Process Assurance Oversight,L3,Ensures processes are reviewed against defined...,10644,Workflow Validation Techniques,Methods used to verify that workflows are corr...,137423,Process Assurance OversightWorkflow Validation...
4,Commercial Bank,Business Process Risk & Control Assurance,Assurance - Risk,1069,RCU HO Team Member,Manager - RCU HO Team Member,Master,Process Assurance Oversight,L3,Ensures processes are reviewed against defined...,10644,Documentation Review Standards,"Defined approach for evaluating completeness, ...",137401,Process Assurance OversightDocumentation Revie...

In [16]:
#product_name,course_level,skill_id,concepts,product_id
#load data file
df2 = pd.read_excel(r"C:\Users\taslim.siddiqui\Downloads\Assurance - Risk (Additional Skills and Concepts).xlsx",sheet_name='Sheet1')
df2

,Function,Department,Role,Role alias,Proficiency,Skill,Level,Skill Description,Concept,Concept Description,Link,Syllabus,Source,Concat,product_id,Corporate id,Function id,Skill.1,Concept.1
0,Commercial Bank,Business Process Risk & Control Assurance,RCU HO Team Member,Manager - RCU HO Team Member,Master,Process Assurance Oversight,L3,Ensures processes are reviewed against defined...,Process Assurance Frameworks,Structured approaches for validating process i...,https://www.smartonlinecourse.co.in/courses/CO...,Lecture 1 Overview of the COSO ERM Framework<...,Bundling,Process Assurance OversightProcess Assurance F...,Prod Product id -37295,17,1069,10644,137306
1,Commercial Bank,Business Process Risk & Control Assurance,RCU HO Team Member,Manager - RCU HO Team Member,Master,Process Assurance Oversight,L3,Ensures processes are reviewed against defined...,Process Compliance Verification,Assessment of whether processes are executed i...,https://www.smartonlinecourse.co.in/courses/On...,Module 1: What is GRC? Why Integration Matters...,Bundling,Process Assurance OversightProcess Compliance ...,39002,17,1069,10644,137307
2,Commercial Bank,Business Process Risk & Control Assurance,RCU HO Team Member,Manager - RCU HO Team Member,Master,Process Assurance Oversight,L3,Ensures processes are reviewed against defined...,SOP Adherence Assessment,Evaluation of whether operational activities f...,https://www.smartonlinecourse.co.in/courses/On...,Module 1: What is GRC? Why Integration Matters...,Bundling,Process Assurance OversightSOP Adherence Asses...,39002,17,1069,10644,137308
3,Commercial Bank,Business Process Risk & Control Assurance,RCU HO Team Member,Manager - RCU HO Team Member,Master,Process Assurance Oversight,L3,Ensures processes are reviewed against defined...,Workflow Validation Techniques,Methods used to verify that workflows are corr...,https://www.smartonlinecourse.co.in/courses/On...,Module 1: What is GRC? Why Integration Matters...,Bundling,Process Assurance OversightWorkflow Validation...,39002,17,1069,10644,137423
4,Commercial Bank,Business Process Risk & Control Assurance,RCU HO Team Member,Manager - RCU HO Team Member,Master,Process Assurance Oversight,L3,Ensures processes are reviewed against defined...,Documentation Review Standards,"Defined approach for evaluating completeness, ...",https://www.smartonlinecourse.co.in/courses/On...,Module 1: What is GRC? Why Integration Matters...,Bundling,Process Assurance OversightDocumentation Revie...,39002,17,1069,10644,137401
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
214,Commercial Bank,Business Process Risk & Control Assurance,RCU HO Team Member,Manager - RCU HO Team Member,Master,Operational Risk Integration,L1,Applies operational risk principles to underst...,Risk Impact Analysis,Evaluation of the potential consequences of a ...,https://www.nulearn.in/courses/executive-devel...,Risk quantification has emerged as a very impo...,Quality,Operational Risk IntegrationRisk Impact Analys...,32170,17,1069,10658,137407
215,Commercial Bank,Business Process Risk & Control Assurance,RCU HO Team Member,Manager - RCU HO Team Member,Master,Operational Risk Integration,L1,Applies operational risk principles to underst...,Risk Likelihood Assessment,Estimation of the probability of occurrence of...,https://www.nulearn.in/courses/executive-devel...,Risk quantification has emerged as a very impo...,Quality,Operational Risk IntegrationRisk Likelihood As...,32170,17,1069,10658,137408
216,Commercial Bank,Business Process Risk & Control Assurance,RCU HO Team Member,Manager - RCU HO Team Member,Master,Operational Risk Integration,L1,Applies operational risk principles to underst...,Residual Risk Assessment,Assessment of remaining risk after control imp...,https://www.nulearn.in/courses/executive-devel...,Risk quantification has emerged as a very impo...,Quality,Operational Risk IntegrationResidual Risk Asse...,32170,17,1069,10658,137409
217,Commercial Bank,Business Process Risk & Control Assurance,RCU HO Team Member,Manager - RCU HO Team Member,Master,Operational Risk Integration,L1,Applies operational risk principles to underst...,Risk Prioritization Techniques,Methods used to rank risks based on impact and...,https://www.nulearn.in/courses/executive-devel...,Risk quantification has emerged as a very impo...,Quality,Operational Risk IntegrationRisk Prioritizatio...,32170,17,1069,10658,137410
218,Commercial Bank,Business Process Risk & Control Assurance,RCU HO Team Member,Manager - RCU HO Team Member,Master,Business Operations Understanding,L1,Develops understanding of operational workflow...,Credit Risk Basics,Awareness of fundamental credit risk concepts ...,https://www.nulearn.in/courses/executive-devel...,Risk quantification has emerged as a very impo...,Quality,Business Operations UnderstandingCredit Risk B...,32170,17,1069,10661,137426

If We want to remove some CPPs

In [17]:
# df2# data is the file which will only have CPP names

# # List of values to check
# values_to_check = ['Coursera','GVC','Gyanodaya Virtual Campus','CIEL','Percipio']

# # Check if any values in the DataFrame are in the list
# df2['CPP_ABC'] = df2['CPP Name'].isin(values_to_check)
# df2 = df2.query("CPP_ABC == False")
# df2

In [18]:
print(df2.columns)

Index(['Function', 'Department', 'Role', 'Role alias', 'Proficiency', 'Skill',
       'Level', 'Skill Description', 'Concept', 'Concept Description', 'Link',
       'Syllabus', 'Source', 'Concat', 'product_id', 'Corporate id ',
       'Function id', 'Skill.1', 'Concept.1'],
      dtype='object')

In [19]:
import pandas as pd

df2['Concept'] = df2['Concept'].astype(str).str.split(',')
df = df2.explode('Concept', ignore_index=True)
df['Concept'] = df['Concept'].str.strip()
df

,Function,Department,Role,Role alias,Proficiency,Skill,Level,Skill Description,Concept,Concept Description,Link,Syllabus,Source,Concat,product_id,Corporate id,Function id,Skill.1,Concept.1
0,Commercial Bank,Business Process Risk & Control Assurance,RCU HO Team Member,Manager - RCU HO Team Member,Master,Process Assurance Oversight,L3,Ensures processes are reviewed against defined...,Process Assurance Frameworks,Structured approaches for validating process i...,https://www.smartonlinecourse.co.in/courses/CO...,Lecture 1 Overview of the COSO ERM Framework<...,Bundling,Process Assurance OversightProcess Assurance F...,Prod Product id -37295,17,1069,10644,137306
1,Commercial Bank,Business Process Risk & Control Assurance,RCU HO Team Member,Manager - RCU HO Team Member,Master,Process Assurance Oversight,L3,Ensures processes are reviewed against defined...,Process Compliance Verification,Assessment of whether processes are executed i...,https://www.smartonlinecourse.co.in/courses/On...,Module 1: What is GRC? Why Integration Matters...,Bundling,Process Assurance OversightProcess Compliance ...,39002,17,1069,10644,137307
2,Commercial Bank,Business Process Risk & Control Assurance,RCU HO Team Member,Manager - RCU HO Team Member,Master,Process Assurance Oversight,L3,Ensures processes are reviewed against defined...,SOP Adherence Assessment,Evaluation of whether operational activities f...,https://www.smartonlinecourse.co.in/courses/On...,Module 1: What is GRC? Why Integration Matters...,Bundling,Process Assurance OversightSOP Adherence Asses...,39002,17,1069,10644,137308
3,Commercial Bank,Business Process Risk & Control Assurance,RCU HO Team Member,Manager - RCU HO Team Member,Master,Process Assurance Oversight,L3,Ensures processes are reviewed against defined...,Workflow Validation Techniques,Methods used to verify that workflows are corr...,https://www.smartonlinecourse.co.in/courses/On...,Module 1: What is GRC? Why Integration Matters...,Bundling,Process Assurance OversightWorkflow Validation...,39002,17,1069,10644,137423
4,Commercial Bank,Business Process Risk & Control Assurance,RCU HO Team Member,Manager - RCU HO Team Member,Master,Process Assurance Oversight,L3,Ensures processes are reviewed against defined...,Documentation Review Standards,"Defined approach for evaluating completeness, ...",https://www.smartonlinecourse.co.in/courses/On...,Module 1: What is GRC? Why Integration Matters...,Bundling,Process Assurance OversightDocumentation Revie...,39002,17,1069,10644,137401
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
214,Commercial Bank,Business Process Risk & Control Assurance,RCU HO Team Member,Manager - RCU HO Team Member,Master,Operational Risk Integration,L1,Applies operational risk principles to underst...,Risk Impact Analysis,Evaluation of the potential consequences of a ...,https://www.nulearn.in/courses/executive-devel...,Risk quantification has emerged as a very impo...,Quality,Operational Risk IntegrationRisk Impact Analys...,32170,17,1069,10658,137407
215,Commercial Bank,Business Process Risk & Control Assurance,RCU HO Team Member,Manager - RCU HO Team Member,Master,Operational Risk Integration,L1,Applies operational risk principles to underst...,Risk Likelihood Assessment,Estimation of the probability of occurrence of...,https://www.nulearn.in/courses/executive-devel...,Risk quantification has emerged as a very impo...,Quality,Operational Risk IntegrationRisk Likelihood As...,32170,17,1069,10658,137408
216,Commercial Bank,Business Process Risk & Control Assurance,RCU HO Team Member,Manager - RCU HO Team Member,Master,Operational Risk Integration,L1,Applies operational risk principles to underst...,Residual Risk Assessment,Assessment of remaining risk after control imp...,https://www.nulearn.in/courses/executive-devel...,Risk quantification has emerged as a very impo...,Quality,Operational Risk IntegrationResidual Risk Asse...,32170,17,1069,10658,137409
217,Commercial Bank,Business Process Risk & Control Assurance,RCU HO Team Member,Manager - RCU HO Team Member,Master,Operational Risk Integration,L1,Applies operational risk principles to underst...,Risk Prioritization Techniques,Methods used to rank risks based on impact and...,https://www.nulearn.in/courses/executive-devel...,Risk quantification has emerged as a very impo...,Quality,Operational Risk IntegrationRisk Prioritizatio...,32170,17,1069,10658,137410
218,Commercial Bank,Business Process Risk & Control Assurance,RCU HO Team Member,Manager - RCU HO Team Member,Master,Business Operations Understanding,L1,Develops understanding of operational workflow...,Credit Risk Basics,Awareness of fundamental credit risk concepts ...,https://www.nulearn.in/courses/executive-devel...,Risk quantification has emerged as a very impo...,Quality,Business Operations UnderstandingCredit Risk B...,32170,17,1069,10661,137426

In [20]:
# Concept Column Row splitting code
#df2['Concept'] = df2['Concept'].apply(
 #  lambda x: [int(i.strip()) for i in x.split(',')] if isinstance(x, str) else x
#)

# Explode the 'concepts' column to create separate rows
#df = df2.explode('concepts', ignore_index=True)
#df['concepts'] = df['concepts'].fillna(0).astype(int)
#df

In [21]:
# Renaming Flexible to Beginner in Course level column
#df['course_level'] = df['course_level'].replace('Flexible', 'Beginner')

In [22]:
#df['course_level'].unique()

In [23]:
# Concat of Skill Concept
#df['FSC_concat'] = df['skill_id'].astype(str)+'|'+df['concepts'].astype(str)
#df['FSC_concat'] = df['concepts'].astype(str)
df['FSC_concat'] =  df['Function'].astype(str) + '|'+  df['Skill'].astype(str)+'|'+df['Concept'].astype(str)#+'|'+df['Concept'].astype(str)
df['FSC_concat']

0      Commercial Bank|Process Assurance Oversight|Pr...
1      Commercial Bank|Process Assurance Oversight|Pr...
2      Commercial Bank|Process Assurance Oversight|SO...
3      Commercial Bank|Process Assurance Oversight|Wo...
4      Commercial Bank|Process Assurance Oversight|Do...
                             ...
214    Commercial Bank|Operational Risk Integration|R...
215    Commercial Bank|Operational Risk Integration|R...
216    Commercial Bank|Operational Risk Integration|R...
217    Commercial Bank|Operational Risk Integration|R...
218    Commercial Bank|Business Operations Understand...
Name: FSC_concat, Length: 219, dtype: object

In [24]:
uniquedf = df.drop_duplicates(subset=['FSC_concat'])
uniquedf=uniquedf['FSC_concat']
uniquedf

0      Commercial Bank|Process Assurance Oversight|Pr...
1      Commercial Bank|Process Assurance Oversight|Pr...
2      Commercial Bank|Process Assurance Oversight|SO...
3      Commercial Bank|Process Assurance Oversight|Wo...
4      Commercial Bank|Process Assurance Oversight|Do...
                             ...
121    Commercial Bank|Business Operations Understand...
122    Commercial Bank|Business Operations Understand...
123    Commercial Bank|Business Operations Understand...
124    Commercial Bank|Business Operations Understand...
125    Commercial Bank|Business Operations Understand...
Name: FSC_concat, Length: 126, dtype: object

In [25]:
# Making new dataframe of Advanced course level only.
#Advanced = df[df['course_level'] == 'Advanced']
#Advanced

In [26]:
# Counting the number of courses in Advanced course level against the FSC_concat column.
result_Advanced =  df.groupby("FSC_concat")["product_id"].nunique().reset_index()
result_Advanced.columns = ["FSC_concat", "Function_count_Advanced"]
result_Advanced.head()

                                          FSC_concat  Function_count_Advanced
0  Commercial Bank|Assurance Quality & Consistenc...                        2
1  Commercial Bank|Assurance Quality & Consistenc...                        1
2  Commercial Bank|Assurance Quality & Consistenc...                        2
3  Commercial Bank|Assurance Quality & Consistenc...                        2
4  Commercial Bank|Assurance Quality & Consistenc...                        1

In [27]:
#Beginner = df[df['course_level'] == 'Beginner']
#Beginner

In [28]:
##result_Beginner =  Beginner.groupby("FSC_concat")["product_id"].nunique().reset_index()
##result_Beginner.columns = ["FSC_concat", "Function_count_beginner"]
#result_Beginner.head()

In [29]:
##Intermediate = df[df['course_level'] == 'Intermediate']
#Intermediate.head()

In [30]:
##result_Intermediate =  Intermediate.groupby("FSC_concat")["product_id"].nunique().reset_index()
#result_Intermediate.columns = ["FSC_concat", "Function_count_intermediate"]
#result_Intermediate.head()

In [31]:
unique_values_df = df.drop_duplicates(subset=['FSC_concat'])
unique_values_df = unique_values_df[['FSC_concat']]
unique_values_df.head()

                                          FSC_concat
0  Commercial Bank|Process Assurance Oversight|Pr...
1  Commercial Bank|Process Assurance Oversight|Pr...
2  Commercial Bank|Process Assurance Oversight|SO...
3  Commercial Bank|Process Assurance Oversight|Wo...
4  Commercial Bank|Process Assurance Oversight|Do...

In [32]:
#merged_df = pd.merge(unique_values_df, result_Beginner, on="FSC_concat", how="left")  # Merge df1 and df2
#merged_df = pd.merge(merged_df, result_Intermediate, on="FSC_concat", how="left")  # Merge with df3
merged_df = pd.merge(unique_values_df, result_Advanced, on="FSC_concat", how="left")
merged_df.head()

                                          FSC_concat  Function_count_Advanced
0  Commercial Bank|Process Assurance Oversight|Pr...                        2
1  Commercial Bank|Process Assurance Oversight|Pr...                        2
2  Commercial Bank|Process Assurance Oversight|SO...                        2
3  Commercial Bank|Process Assurance Oversight|Wo...                        2
4  Commercial Bank|Process Assurance Oversight|Do...                        2

In [33]:
# If you're working with a single column but want to keep it as a DataFrame:
#merged_df['Function_count_beginner'] = merged_df['Function_count_beginner'].fillna(0).astype(int)
#merged_df['Function_count_intermediate'] = merged_df['Function_count_intermediate'].fillna(0).astype(int)
merged_df['Function_count_Advanced'] = merged_df['Function_count_Advanced'].fillna(0).astype(int)
merged_df.head()

                                          FSC_concat  Function_count_Advanced
0  Commercial Bank|Process Assurance Oversight|Pr...                        2
1  Commercial Bank|Process Assurance Oversight|Pr...                        2
2  Commercial Bank|Process Assurance Oversight|SO...                        2
3  Commercial Bank|Process Assurance Oversight|Wo...                        2
4  Commercial Bank|Process Assurance Oversight|Do...                        2

In [34]:
#df1['Skill ID'].unique()
#df1['FSC_concat']= df1['PRODUCTION Skill ID'].fillna(0).astype(int).astype(str)+"|"+df1['PRODUCTION Concepts ID'].fillna(0).astype(int).astype(str)
#df1.head()

In [35]:
#df1['FSC_concat'] = (
    #pd.to_numeric(df1['PRODUCTION Skill ID'], errors='coerce').fillna(0).astype(int).astype(str)
    #+ "|" + pd.to_numeric(df1['PRODUCTION Concepts ID'], errors='coerce').fillna(0).astype(int).astype(str))
#df1.head()


df1['FSC_concat'] = df1['Function'].fillna(0).astype(str) + "|" + df1['Skill'].fillna(0).astype(str) + "|" + df1['Concept'] .fillna(0).astype(str)#+ "|" + df1['Concept'] .fillna(0).astype(str)
df1.head()

,Function,Department,Function.1,Function id,Role,Role alias,Proficiency,Skill,Level,Skill Description,Skill.1,Concept,Concept Description,Concept.1,Concat,FSC_concat
0,Commercial Bank,Business Process Risk & Control Assurance,Assurance - Risk,1069,RCU HO Team Member,Manager - RCU HO Team Member,Master,Process Assurance Oversight,L3,Ensures processes are reviewed against defined...,10644,Process Assurance Frameworks,Structured approaches for validating process i...,137306,Process Assurance OversightProcess Assurance F...,Commercial Bank|Process Assurance Oversight|Pr...
1,Commercial Bank,Business Process Risk & Control Assurance,Assurance - Risk,1069,RCU HO Team Member,Manager - RCU HO Team Member,Master,Process Assurance Oversight,L3,Ensures processes are reviewed against defined...,10644,Process Compliance Verification,Assessment of whether processes are executed i...,137307,Process Assurance OversightProcess Compliance ...,Commercial Bank|Process Assurance Oversight|Pr...
2,Commercial Bank,Business Process Risk & Control Assurance,Assurance - Risk,1069,RCU HO Team Member,Manager - RCU HO Team Member,Master,Process Assurance Oversight,L3,Ensures processes are reviewed against defined...,10644,SOP Adherence Assessment,Evaluation of whether operational activities f...,137308,Process Assurance OversightSOP Adherence Asses...,Commercial Bank|Process Assurance Oversight|SO...
3,Commercial Bank,Business Process Risk & Control Assurance,Assurance - Risk,1069,RCU HO Team Member,Manager - RCU HO Team Member,Master,Process Assurance Oversight,L3,Ensures processes are reviewed against defined...,10644,Workflow Validation Techniques,Methods used to verify that workflows are corr...,137423,Process Assurance OversightWorkflow Validation...,Commercial Bank|Process Assurance Oversight|Wo...
4,Commercial Bank,Business Process Risk & Control Assurance,Assurance - Risk,1069,RCU HO Team Member,Manager - RCU HO Team Member,Master,Process Assurance Oversight,L3,Ensures processes are reviewed against defined...,10644,Documentation Review Standards,"Defined approach for evaluating completeness, ...",137401,Process Assurance OversightDocumentation Revie...,Commercial Bank|Process Assurance Oversight|Do...

In [36]:
automated_df = pd.merge(df1,merged_df, on ='FSC_concat', how = 'left' )
#automated_df['Function_count_beginner'] = automated_df['Function_count_beginner'].fillna(0).astype(int)
#automated_df['Function_count_intermediate'] = automated_df['Function_count_intermediate'].fillna(0).astype(int)
automated_df['Function_count_Advanced'] = automated_df['Function_count_Advanced'].fillna(0).astype(int)
automated_df.head()

,Function,Department,Function.1,Function id,Role,Role alias,Proficiency,Skill,Level,Skill Description,Skill.1,Concept,Concept Description,Concept.1,Concat,FSC_concat,Function_count_Advanced
0,Commercial Bank,Business Process Risk & Control Assurance,Assurance - Risk,1069,RCU HO Team Member,Manager - RCU HO Team Member,Master,Process Assurance Oversight,L3,Ensures processes are reviewed against defined...,10644,Process Assurance Frameworks,Structured approaches for validating process i...,137306,Process Assurance OversightProcess Assurance F...,Commercial Bank|Process Assurance Oversight|Pr...,2
1,Commercial Bank,Business Process Risk & Control Assurance,Assurance - Risk,1069,RCU HO Team Member,Manager - RCU HO Team Member,Master,Process Assurance Oversight,L3,Ensures processes are reviewed against defined...,10644,Process Compliance Verification,Assessment of whether processes are executed i...,137307,Process Assurance OversightProcess Compliance ...,Commercial Bank|Process Assurance Oversight|Pr...,2
2,Commercial Bank,Business Process Risk & Control Assurance,Assurance - Risk,1069,RCU HO Team Member,Manager - RCU HO Team Member,Master,Process Assurance Oversight,L3,Ensures processes are reviewed against defined...,10644,SOP Adherence Assessment,Evaluation of whether operational activities f...,137308,Process Assurance OversightSOP Adherence Asses...,Commercial Bank|Process Assurance Oversight|SO...,2
3,Commercial Bank,Business Process Risk & Control Assurance,Assurance - Risk,1069,RCU HO Team Member,Manager - RCU HO Team Member,Master,Process Assurance Oversight,L3,Ensures processes are reviewed against defined...,10644,Workflow Validation Techniques,Methods used to verify that workflows are corr...,137423,Process Assurance OversightWorkflow Validation...,Commercial Bank|Process Assurance Oversight|Wo...,2
4,Commercial Bank,Business Process Risk & Control Assurance,Assurance - Risk,1069,RCU HO Team Member,Manager - RCU HO Team Member,Master,Process Assurance Oversight,L3,Ensures processes are reviewed against defined...,10644,Documentation Review Standards,"Defined approach for evaluating completeness, ...",137401,Process Assurance OversightDocumentation Revie...,Commercial Bank|Process Assurance Oversight|Do...,2

In [37]:
automated_df.to_excel("C:\\Users\\taslim.siddiqui\\Downloads//automate_FSC_deficit_RDSCL_23-03-2026.xlsx")

In [38]:
import pandas as pd

path = r"C:\Users\taslim.siddiqui\Downloads\KOTAK Course + Deficit Tracker_Data added 20.01 2.xlsx"

df = pd.read_excel(path, sheet_name='HH+Other CPP Master')

# --- PIVOT: Function x Proficiency, distinct count of concepts ---
pivot = pd.pivot_table(
    df,
    index=['Function'],
    columns=['course_level'],
    values='concepts',          # or 'Concept' if that is the column name
    aggfunc=pd.Series.nunique,  # distinct count
    fill_value=0
)

pivot_out = pivot.reset_index()

print(pivot_out.head())

pivot_out.to_excel(
    r"C:\Users\taslim.siddiqui\Downloads\pivot_1.xlsx",
    index=False
)

course_level                            Function  Advanced  Beginner  \
0                              Assurance - Audit       396       389
1                                             HR       430       450
2                                            Ops       180       294
3                Professional Behavior & Mindset        32        35
4             RM-Commercial Bank - Agri Business       143       144

course_level  Intermediate
0                      445
1                      395
2                      292
3                       35
4                      146

In [39]:
print("df1 dup keys:", df1['FSC_concat'].duplicated().sum())
print("merged_df dup keys:", merged_df['FSC_concat'].duplicated().sum())
print("Any 0-keys in df1:", df1['FSC_concat'].str.startswith("0|").sum(), df1['FSC_concat'].str.contains("|0|", regex=False).sum())
df1.to_excel(r"C:\Users\taslim.siddiqui\Downloads\FSC_concat.xlsx")

df1 dup keys: 0
merged_df dup keys: 0
Any 0-keys in df1: 0 0