In [46]:
import pandas as pd

In [47]:
df = pd.read_excel("/Users/romitbenkar/Downloads/Additional Skills and Concepts upload - Kotak HR (Locked FSC).xlsx",sheet_name="Sheet1")
df

,Prod Course id's,Prod Course id's.1,MP ID,course_duration__c,Duration,Institute,Price,Concept id,corporate_function_id
0,6070,6070.0,16847.0,60.0,Hours,Henry Harvin,44500.0,"15162, 15183, 15188, 15312, 15318, 15169, 1517...",660.0
1,32524,32524.0,32337.0,192.0,Hours,Henry Harvin,12500.0,"15164, 15166, 15281, 15285, 15321, 15328, 1524...",660.0
2,33445,33445.0,33300.0,192.0,Hours,Henry Harvin,59500.0,"15199, 15204, 15212",660.0
3,6041,6041.0,16781.0,12.0,Hours,Henry Harvin,10000.0,"15179, 15180, 15177, 15196, 15185, 15195, 15198",660.0
4,Pre-Prod id -38933,37812.0,38900.0,2.5,Hours,Keka Academy,1.0,"15213, 13674, 13677, 13680, 13681, 15309, 1531...",660.0
5,6266,6266.0,1936.0,6.0,Months,Henry Harvin,103550.0,"15189, 15197, 15319, 15320, 15327, 15239, 1524...",660.0
6,32420,32420.0,32233.0,192.0,Hours,Henry Harvin,34500.0,"15322, 15243, 14149, 13868, 14146, 14152, 15242",660.0
7,Pre-Prod id -38836,37820.0,38904.0,28.0,Hours,Henry Harvin,22500.0,"15162, 15201, 15206, 15179, 15180, 15317, 1517...",660.0
8,37161,37161.0,38064.0,288.0,Hours,Henry Harvin,1.0,"15166, 15204, 15281, 15309, 15311, 15312, 1531...",660.0
9,Pre-Prod id -38835,37814.0,38907.0,192.0,Hours,Henry Harvin,5000.0,"15200, 15177, 15210, 15211, 15216, 15159, 1516...",660.0
10,Pre-Prod id -38932,37813.0,38909.0,1.5,Hours,Keka Academy,1.0,"15308, 14111, 15243, 15232, 14104, 14106, 1410...",660.0
11,33632,33632.0,33541.0,192.0,Hours,Henry Harvin,15000.0,"15234, 15199, 15208",660.0
12,33744,33744.0,33645.0,16.0,Hours,Henry Harvin,236000.0,"15160, 15161, 15159, 15162, 15165, 15167, 1516...",660.0
13,35161,35161.0,36021.0,288.0,Hours,Henry Harvin,798000.0,"15184, 15284, 15287, 15299, 15300, 15301, 1530...",660.0
14,35435,35435.0,36277.0,288.0,Hours,Henry Harvin,100000.0,"15281, 15285, 15309, 15310, 15311, 15313, 1531...",660.0
15,35377,35377.0,36223.0,192.0,Hours,Henry Harvin,89000.0,"15173, 15212",660.0
16,35203,35203.0,35916.0,192.0,Hours,Henry Harvin,15000.0,"14638, 14638, 14638, 13716, 13973, 14088, 1410...",660.0
17,35305,35305.0,36124.0,192.0,Hours,Henry Harvin,44500.0,"14614, 13932, 15326, 15236, 15238",660.0
18,Pre-Prod id -38930,37815.0,38902.0,1.5,Hours,Keka Academy,1.0,"14086, 14087, 14091, 14334, 14342, 14598, 1531...",660.0
19,Pre-Prod id -38938,37818.0,38906.0,2.0,Hours,Keka Academy,1.0,"14171, 15165, 15308",660.0
20,Pre-Prod id -38929,37811.0,38901.0,1.0,Hours,Keka Academy,1.0,"14482, 14483",660.0
21,Pre-Prod id -38934,37817.0,38905.0,3.5,Hours,Keka Academy,1.0,"14078, 14079, 14080, 14474, 14479, 15299, 1521...",660.0
22,Pre-Prod id -38936,37816.0,38903.0,3.0,Hours,Keka Academy,1.0,"14629, 14606, 15244, 14630, 14631, 14632, 1463...",660.0
23,33156,33156.0,33004.0,192.0,Hours,Henry Harvin,89500.0,"13717, 13723, 14075, 14078, 14079, 14082, 1408...",660.0
24,32958,32958.0,32806.0,4.0,Year,Henry Harvin,349500.0,"13718, 13968, 13973, 14106, 14428, 14613, 1532...",660.0
25,33362,33362.0,33217.0,420.0,Hours,Henry Harvin,249000.0,13623,660.0
26,37165,37165.0,38066.0,1.0,Year,Henry Harvin,1.0,"13615, 13618, 13621",660.0
27,33738,33738.0,33647.0,67.0,Hours,Henry Harvin,59500.0,"15201, 15311, 15316, 15209, 15216, 15259, 1526...",660.0
28,Pre-Prod id -38305,37819.0,38908.0,12.0,Hours,Eduonix,9086.0,"15241, 15247, 15233, 15238, 14604, 15242, 1523...",660.0
29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [48]:
df.rename(columns={'Duration': 'duration_medium__c'},inplace=True)
df.columns

Index(['Prod Course id's', 'Prod Course id's.1', 'MP ID', 'course_duration__c',
       'duration_medium__c', 'Institute', 'Price', 'Concept id',
       'corporate_function_id'],
      dtype='object')

In [49]:
# Replace 'apple' with 'orange' and 'banana' with 'grape' in column 'B'
df['duration_medium__c'] = df['duration_medium__c'].replace({'Day': 'Days', 'Month': 'Months','Year':'Years'})

# Define conversion factors to seconds for each mode
conversion_factors = {
    'years': 365 * 24 * 60 * 60,        # approximate (ignores leap years)
    'months': 30.44 * 24 * 60 * 60,     # average month
    'weeks': 7 * 24 * 60 * 60,
    'days': 24 * 60 * 60,
    'hours': 60 * 60,
    'minutes': 60
}

df['duration_medium__c']=df['duration_medium__c'].astype(str)


# Function to convert duration based on the mode
def convert_to_seconds(row):
    duration = row['course_duration__c']
    mode = row['duration_medium__c'].strip().lower()  # normalize to lowercase
    return duration * conversion_factors.get(mode, 1)  # Default to 1 if mode is not found

# Apply the conversion function to each row
df['Duration_in_seconds'] = df.apply(convert_to_seconds, axis=1)

# Add a column that checks if the duration in seconds is less than or equal to a week
df['Is_within_a_week'] = df['Duration_in_seconds'] <= 7 * 24 * 60 * 60

# Save the result back to Excel
#df.to_excel('//Users//romitbenkar//Desktop//Office//19-11-24//timeconvertoutput.xlsx', index=False)
df

,Prod Course id's,Prod Course id's.1,MP ID,course_duration__c,duration_medium__c,Institute,Price,Concept id,corporate_function_id,Duration_in_seconds,Is_within_a_week
0,6070,6070.0,16847.0,60.0,Hours,Henry Harvin,44500.0,"15162, 15183, 15188, 15312, 15318, 15169, 1517...",660.0,216000.0,True
1,32524,32524.0,32337.0,192.0,Hours,Henry Harvin,12500.0,"15164, 15166, 15281, 15285, 15321, 15328, 1524...",660.0,691200.0,False
2,33445,33445.0,33300.0,192.0,Hours,Henry Harvin,59500.0,"15199, 15204, 15212",660.0,691200.0,False
3,6041,6041.0,16781.0,12.0,Hours,Henry Harvin,10000.0,"15179, 15180, 15177, 15196, 15185, 15195, 15198",660.0,43200.0,True
4,Pre-Prod id -38933,37812.0,38900.0,2.5,Hours,Keka Academy,1.0,"15213, 13674, 13677, 13680, 13681, 15309, 1531...",660.0,9000.0,True
5,6266,6266.0,1936.0,6.0,Months,Henry Harvin,103550.0,"15189, 15197, 15319, 15320, 15327, 15239, 1524...",660.0,15780096.0,False
6,32420,32420.0,32233.0,192.0,Hours,Henry Harvin,34500.0,"15322, 15243, 14149, 13868, 14146, 14152, 15242",660.0,691200.0,False
7,Pre-Prod id -38836,37820.0,38904.0,28.0,Hours,Henry Harvin,22500.0,"15162, 15201, 15206, 15179, 15180, 15317, 1517...",660.0,100800.0,True
8,37161,37161.0,38064.0,288.0,Hours,Henry Harvin,1.0,"15166, 15204, 15281, 15309, 15311, 15312, 1531...",660.0,1036800.0,False
9,Pre-Prod id -38835,37814.0,38907.0,192.0,Hours,Henry Harvin,5000.0,"15200, 15177, 15210, 15211, 15216, 15159, 1516...",660.0,691200.0,False
10,Pre-Prod id -38932,37813.0,38909.0,1.5,Hours,Keka Academy,1.0,"15308, 14111, 15243, 15232, 14104, 14106, 1410...",660.0,5400.0,True
11,33632,33632.0,33541.0,192.0,Hours,Henry Harvin,15000.0,"15234, 15199, 15208",660.0,691200.0,False
12,33744,33744.0,33645.0,16.0,Hours,Henry Harvin,236000.0,"15160, 15161, 15159, 15162, 15165, 15167, 1516...",660.0,57600.0,True
13,35161,35161.0,36021.0,288.0,Hours,Henry Harvin,798000.0,"15184, 15284, 15287, 15299, 15300, 15301, 1530...",660.0,1036800.0,False
14,35435,35435.0,36277.0,288.0,Hours,Henry Harvin,100000.0,"15281, 15285, 15309, 15310, 15311, 15313, 1531...",660.0,1036800.0,False
15,35377,35377.0,36223.0,192.0,Hours,Henry Harvin,89000.0,"15173, 15212",660.0,691200.0,False
16,35203,35203.0,35916.0,192.0,Hours,Henry Harvin,15000.0,"14638, 14638, 14638, 13716, 13973, 14088, 1410...",660.0,691200.0,False
17,35305,35305.0,36124.0,192.0,Hours,Henry Harvin,44500.0,"14614, 13932, 15326, 15236, 15238",660.0,691200.0,False
18,Pre-Prod id -38930,37815.0,38902.0,1.5,Hours,Keka Academy,1.0,"14086, 14087, 14091, 14334, 14342, 14598, 1531...",660.0,5400.0,True
19,Pre-Prod id -38938,37818.0,38906.0,2.0,Hours,Keka Academy,1.0,"14171, 15165, 15308",660.0,7200.0,True
20,Pre-Prod id -38929,37811.0,38901.0,1.0,Hours,Keka Academy,1.0,"14482, 14483",660.0,3600.0,True
21,Pre-Prod id -38934,37817.0,38905.0,3.5,Hours,Keka Academy,1.0,"14078, 14079, 14080, 14474, 14479, 15299, 1521...",660.0,12600.0,True
22,Pre-Prod id -38936,37816.0,38903.0,3.0,Hours,Keka Academy,1.0,"14629, 14606, 15244, 14630, 14631, 14632, 1463...",660.0,10800.0,True
23,33156,33156.0,33004.0,192.0,Hours,Henry Harvin,89500.0,"13717, 13723, 14075, 14078, 14079, 14082, 1408...",660.0,691200.0,False
24,32958,32958.0,32806.0,4.0,Years,Henry Harvin,349500.0,"13718, 13968, 13973, 14106, 14428, 14613, 1532...",660.0,126144000.0,False
25,33362,33362.0,33217.0,420.0,Hours,Henry Harvin,249000.0,13623,660.0,1512000.0,False
26,37165,37165.0,38066.0,1.0,Years,Henry Harvin,1.0,"13615, 13618, 13621",660.0,31536000.0,False
27,33738,33738.0,33647.0,67.0,Hours,Henry Harvin,59500.0,"15201, 15311, 15316, 15209, 15216, 15259, 1526...",660.0,241200.0,True
28,Pre-Prod id -38305,37819.0,38908.0,12.0,Hours,Eduonix,9086.0,"15241, 15247, 15233, 15238, 14604, 15242, 1523...",660.0,43200.0,True
29,NaN,NaN,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,False
30,,NaN,NaN,NaN,nan,NaN,NaN,NaN,NaN,NaN,False

In [50]:
df.rename(columns={'Institute': 'CPP'},inplace=True)
df.columns

Index(['Prod Course id's', 'Prod Course id's.1', 'MP ID', 'course_duration__c',
       'duration_medium__c', 'CPP', 'Price', 'Concept id',
       'corporate_function_id', 'Duration_in_seconds', 'Is_within_a_week'],
      dtype='object')

In [51]:
# Define a function to count the number of concepts based on commas
def count_commas(val):
    if pd.isna(val):  # If the value is NaN (missing), return 0
        return 0
    elif ',' in val:  # If the value contains commas, count the number of commas and add 1
        return val.count(',') + 1
    else:  # If the value has no commas, assume it's a single concept
        return 1

# Apply the function to each value in the 'concepts' column
# and create a new column 'concept_count' with the result
df['concept_count'] = df['Concept id'].apply(count_commas)

In [52]:
values_to_check_keka = ['Keka Academy']

# Check if any values in the DataFrame are in the list
df['integration_keka'] = df['CPP'].isin(values_to_check_keka)
integration_keka_df = df.query("integration_keka == True")
integration_keka_df

,Prod Course id's,Prod Course id's.1,MP ID,course_duration__c,duration_medium__c,CPP,Price,Concept id,corporate_function_id,Duration_in_seconds,Is_within_a_week,concept_count,integration_keka
4,Pre-Prod id -38933,37812.0,38900.0,2.5,Hours,Keka Academy,1.0,"15213, 13674, 13677, 13680, 13681, 15309, 1531...",660.0,9000.0,True,17,True
10,Pre-Prod id -38932,37813.0,38909.0,1.5,Hours,Keka Academy,1.0,"15308, 14111, 15243, 15232, 14104, 14106, 1410...",660.0,5400.0,True,10,True
18,Pre-Prod id -38930,37815.0,38902.0,1.5,Hours,Keka Academy,1.0,"14086, 14087, 14091, 14334, 14342, 14598, 1531...",660.0,5400.0,True,16,True
19,Pre-Prod id -38938,37818.0,38906.0,2.0,Hours,Keka Academy,1.0,"14171, 15165, 15308",660.0,7200.0,True,3,True
20,Pre-Prod id -38929,37811.0,38901.0,1.0,Hours,Keka Academy,1.0,"14482, 14483",660.0,3600.0,True,2,True
21,Pre-Prod id -38934,37817.0,38905.0,3.5,Hours,Keka Academy,1.0,"14078, 14079, 14080, 14474, 14479, 15299, 1521...",660.0,12600.0,True,21,True
22,Pre-Prod id -38936,37816.0,38903.0,3.0,Hours,Keka Academy,1.0,"14629, 14606, 15244, 14630, 14631, 14632, 1463...",660.0,10800.0,True,17,True

In [53]:
values_to_check_HH = ['Henry Harvin']

# Check if any values in the DataFrame are in the list
df['integration_HH'] = df['CPP'].isin(values_to_check_HH)
integration_HH_df = df.query("integration_HH == True")
integration_HH_df

,Prod Course id's,Prod Course id's.1,MP ID,course_duration__c,duration_medium__c,CPP,Price,Concept id,corporate_function_id,Duration_in_seconds,Is_within_a_week,concept_count,integration_keka,integration_HH
0,6070,6070.0,16847.0,60.0,Hours,Henry Harvin,44500.0,"15162, 15183, 15188, 15312, 15318, 15169, 1517...",660.0,216000.0,True,22,False,True
1,32524,32524.0,32337.0,192.0,Hours,Henry Harvin,12500.0,"15164, 15166, 15281, 15285, 15321, 15328, 1524...",660.0,691200.0,False,22,False,True
2,33445,33445.0,33300.0,192.0,Hours,Henry Harvin,59500.0,"15199, 15204, 15212",660.0,691200.0,False,3,False,True
3,6041,6041.0,16781.0,12.0,Hours,Henry Harvin,10000.0,"15179, 15180, 15177, 15196, 15185, 15195, 15198",660.0,43200.0,True,7,False,True
5,6266,6266.0,1936.0,6.0,Months,Henry Harvin,103550.0,"15189, 15197, 15319, 15320, 15327, 15239, 1524...",660.0,15780096.0,False,13,False,True
6,32420,32420.0,32233.0,192.0,Hours,Henry Harvin,34500.0,"15322, 15243, 14149, 13868, 14146, 14152, 15242",660.0,691200.0,False,7,False,True
7,Pre-Prod id -38836,37820.0,38904.0,28.0,Hours,Henry Harvin,22500.0,"15162, 15201, 15206, 15179, 15180, 15317, 1517...",660.0,100800.0,True,51,False,True
8,37161,37161.0,38064.0,288.0,Hours,Henry Harvin,1.0,"15166, 15204, 15281, 15309, 15311, 15312, 1531...",660.0,1036800.0,False,28,False,True
9,Pre-Prod id -38835,37814.0,38907.0,192.0,Hours,Henry Harvin,5000.0,"15200, 15177, 15210, 15211, 15216, 15159, 1516...",660.0,691200.0,False,9,False,True
11,33632,33632.0,33541.0,192.0,Hours,Henry Harvin,15000.0,"15234, 15199, 15208",660.0,691200.0,False,3,False,True
12,33744,33744.0,33645.0,16.0,Hours,Henry Harvin,236000.0,"15160, 15161, 15159, 15162, 15165, 15167, 1516...",660.0,57600.0,True,25,False,True
13,35161,35161.0,36021.0,288.0,Hours,Henry Harvin,798000.0,"15184, 15284, 15287, 15299, 15300, 15301, 1530...",660.0,1036800.0,False,27,False,True
14,35435,35435.0,36277.0,288.0,Hours,Henry Harvin,100000.0,"15281, 15285, 15309, 15310, 15311, 15313, 1531...",660.0,1036800.0,False,30,False,True
15,35377,35377.0,36223.0,192.0,Hours,Henry Harvin,89000.0,"15173, 15212",660.0,691200.0,False,2,False,True
16,35203,35203.0,35916.0,192.0,Hours,Henry Harvin,15000.0,"14638, 14638, 14638, 13716, 13973, 14088, 1410...",660.0,691200.0,False,19,False,True
17,35305,35305.0,36124.0,192.0,Hours,Henry Harvin,44500.0,"14614, 13932, 15326, 15236, 15238",660.0,691200.0,False,5,False,True
23,33156,33156.0,33004.0,192.0,Hours,Henry Harvin,89500.0,"13717, 13723, 14075, 14078, 14079, 14082, 1408...",660.0,691200.0,False,12,False,True
24,32958,32958.0,32806.0,4.0,Years,Henry Harvin,349500.0,"13718, 13968, 13973, 14106, 14428, 14613, 1532...",660.0,126144000.0,False,81,False,True
25,33362,33362.0,33217.0,420.0,Hours,Henry Harvin,249000.0,13623,660.0,1512000.0,False,1,False,True
26,37165,37165.0,38066.0,1.0,Years,Henry Harvin,1.0,"13615, 13618, 13621",660.0,31536000.0,False,3,False,True
27,33738,33738.0,33647.0,67.0,Hours,Henry Harvin,59500.0,"15201, 15311, 15316, 15209, 15216, 15259, 1526...",660.0,241200.0,True,11,False,True

In [54]:
values_to_check_Eduonix = ['Eduonix']

# Check if any values in the DataFrame are in the list
df['integration_Eduonix'] = df['CPP'].isin(values_to_check_Eduonix)
integration_Eduonix_df = df.query("integration_Eduonix == True")
integration_Eduonix_df

,Prod Course id's,Prod Course id's.1,MP ID,course_duration__c,duration_medium__c,CPP,Price,Concept id,corporate_function_id,Duration_in_seconds,Is_within_a_week,concept_count,integration_keka,integration_HH,integration_Eduonix
28,Pre-Prod id -38305,37819.0,38908.0,12.0,Hours,Eduonix,9086.0,"15241, 15247, 15233, 15238, 14604, 15242, 1523...",660.0,43200.0,True,9,False,False,True

In [55]:
rank_integration_keka_df = integration_keka_df.sort_values(
    by=["concept_count","Duration_in_seconds"],
    ascending=[False,True]
).reset_index(drop=True)


rank_integration_keka_df['Rank'] = 150 - (rank_integration_keka_df.index * 0.01)
rank_integration_keka_df

,Prod Course id's,Prod Course id's.1,MP ID,course_duration__c,duration_medium__c,CPP,Price,Concept id,corporate_function_id,Duration_in_seconds,Is_within_a_week,concept_count,integration_keka,Rank
0,Pre-Prod id -38934,37817.0,38905.0,3.5,Hours,Keka Academy,1.0,"14078, 14079, 14080, 14474, 14479, 15299, 1521...",660.0,12600.0,True,21,True,150.00
1,Pre-Prod id -38933,37812.0,38900.0,2.5,Hours,Keka Academy,1.0,"15213, 13674, 13677, 13680, 13681, 15309, 1531...",660.0,9000.0,True,17,True,149.99
2,Pre-Prod id -38936,37816.0,38903.0,3.0,Hours,Keka Academy,1.0,"14629, 14606, 15244, 14630, 14631, 14632, 1463...",660.0,10800.0,True,17,True,149.98
3,Pre-Prod id -38930,37815.0,38902.0,1.5,Hours,Keka Academy,1.0,"14086, 14087, 14091, 14334, 14342, 14598, 1531...",660.0,5400.0,True,16,True,149.97
4,Pre-Prod id -38932,37813.0,38909.0,1.5,Hours,Keka Academy,1.0,"15308, 14111, 15243, 15232, 14104, 14106, 1410...",660.0,5400.0,True,10,True,149.96
5,Pre-Prod id -38938,37818.0,38906.0,2.0,Hours,Keka Academy,1.0,"14171, 15165, 15308",660.0,7200.0,True,3,True,149.95
6,Pre-Prod id -38929,37811.0,38901.0,1.0,Hours,Keka Academy,1.0,"14482, 14483",660.0,3600.0,True,2,True,149.94

In [56]:
rank_integration_HH_df = integration_HH_df.sort_values(
    by=["concept_count","Duration_in_seconds"],
    ascending=[False,True]
).reset_index(drop=True)


rank_integration_HH_df['Rank'] = 100 - (rank_integration_HH_df.index * 0.01)
rank_integration_HH_df

,Prod Course id's,Prod Course id's.1,MP ID,course_duration__c,duration_medium__c,CPP,Price,Concept id,corporate_function_id,Duration_in_seconds,Is_within_a_week,concept_count,integration_keka,integration_HH,Rank
0,32958,32958.0,32806.0,4.0,Years,Henry Harvin,349500.0,"13718, 13968, 13973, 14106, 14428, 14613, 1532...",660.0,126144000.0,False,81,False,True,100.00
1,Pre-Prod id -38836,37820.0,38904.0,28.0,Hours,Henry Harvin,22500.0,"15162, 15201, 15206, 15179, 15180, 15317, 1517...",660.0,100800.0,True,51,False,True,99.99
2,35435,35435.0,36277.0,288.0,Hours,Henry Harvin,100000.0,"15281, 15285, 15309, 15310, 15311, 15313, 1531...",660.0,1036800.0,False,30,False,True,99.98
3,37161,37161.0,38064.0,288.0,Hours,Henry Harvin,1.0,"15166, 15204, 15281, 15309, 15311, 15312, 1531...",660.0,1036800.0,False,28,False,True,99.97
4,35161,35161.0,36021.0,288.0,Hours,Henry Harvin,798000.0,"15184, 15284, 15287, 15299, 15300, 15301, 1530...",660.0,1036800.0,False,27,False,True,99.96
5,33744,33744.0,33645.0,16.0,Hours,Henry Harvin,236000.0,"15160, 15161, 15159, 15162, 15165, 15167, 1516...",660.0,57600.0,True,25,False,True,99.95
6,6070,6070.0,16847.0,60.0,Hours,Henry Harvin,44500.0,"15162, 15183, 15188, 15312, 15318, 15169, 1517...",660.0,216000.0,True,22,False,True,99.94
7,32524,32524.0,32337.0,192.0,Hours,Henry Harvin,12500.0,"15164, 15166, 15281, 15285, 15321, 15328, 1524...",660.0,691200.0,False,22,False,True,99.93
8,35203,35203.0,35916.0,192.0,Hours,Henry Harvin,15000.0,"14638, 14638, 14638, 13716, 13973, 14088, 1410...",660.0,691200.0,False,19,False,True,99.92
9,6266,6266.0,1936.0,6.0,Months,Henry Harvin,103550.0,"15189, 15197, 15319, 15320, 15327, 15239, 1524...",660.0,15780096.0,False,13,False,True,99.91
10,33156,33156.0,33004.0,192.0,Hours,Henry Harvin,89500.0,"13717, 13723, 14075, 14078, 14079, 14082, 1408...",660.0,691200.0,False,12,False,True,99.90
11,33738,33738.0,33647.0,67.0,Hours,Henry Harvin,59500.0,"15201, 15311, 15316, 15209, 15216, 15259, 1526...",660.0,241200.0,True,11,False,True,99.89
12,Pre-Prod id -38835,37814.0,38907.0,192.0,Hours,Henry Harvin,5000.0,"15200, 15177, 15210, 15211, 15216, 15159, 1516...",660.0,691200.0,False,9,False,True,99.88
13,6041,6041.0,16781.0,12.0,Hours,Henry Harvin,10000.0,"15179, 15180, 15177, 15196, 15185, 15195, 15198",660.0,43200.0,True,7,False,True,99.87
14,32420,32420.0,32233.0,192.0,Hours,Henry Harvin,34500.0,"15322, 15243, 14149, 13868, 14146, 14152, 15242",660.0,691200.0,False,7,False,True,99.86
15,35305,35305.0,36124.0,192.0,Hours,Henry Harvin,44500.0,"14614, 13932, 15326, 15236, 15238",660.0,691200.0,False,5,False,True,99.85
16,33445,33445.0,33300.0,192.0,Hours,Henry Harvin,59500.0,"15199, 15204, 15212",660.0,691200.0,False,3,False,True,99.84
17,33632,33632.0,33541.0,192.0,Hours,Henry Harvin,15000.0,"15234, 15199, 15208",660.0,691200.0,False,3,False,True,99.83
18,37165,37165.0,38066.0,1.0,Years,Henry Harvin,1.0,"13615, 13618, 13621",660.0,31536000.0,False,3,False,True,99.82
19,35377,35377.0,36223.0,192.0,Hours,Henry Harvin,89000.0,"15173, 15212",660.0,691200.0,False,2,False,True,99.81
20,33362,33362.0,33217.0,420.0,Hours,Henry Harvin,249000.0,13623,660.0,1512000.0,False,1,False,True,99.80

In [57]:
rank_integration_Eduonix_df = integration_Eduonix_df.sort_values(
    by=["concept_count","Duration_in_seconds"],
    ascending=[False,True]
).reset_index(drop=True)


rank_integration_Eduonix_df['Rank'] = 50 - (rank_integration_Eduonix_df.index * 0.01)
rank_integration_Eduonix_df

,Prod Course id's,Prod Course id's.1,MP ID,course_duration__c,duration_medium__c,CPP,Price,Concept id,corporate_function_id,Duration_in_seconds,Is_within_a_week,concept_count,integration_keka,integration_HH,integration_Eduonix,Rank
0,Pre-Prod id -38305,37819.0,38908.0,12.0,Hours,Eduonix,9086.0,"15241, 15247, 15233, 15238, 14604, 15242, 1523...",660.0,43200.0,True,9,False,False,True,50.0

In [58]:
# Define a dictionary with keys representing category labels 
# and values being different filtered and ranked DataFrames
pieces = {
    "x1": rank_integration_keka_df,   # Non-corporate courses marked as priority_cpp
    "x2": rank_integration_HH_df,                # Non-corporate courses that have concepts
    "x3": rank_integration_Eduonix_df,              # Non-corporate courses with no concept mapping
}

# Concatenate all the DataFrames together vertically (i.e., one below the other)
result = pd.concat(pieces)

# Save the final concatenated DataFrame to an Excel file
# result.to_excel("/Users/romitbenkar/Downloads/Recorating_Kotak_HR.xlsx")
result

         Prod Course id's  Prod Course id's.1    MP ID  course_duration__c  \
x1 0   Pre-Prod id -38934             37817.0  38905.0                 3.5
   1   Pre-Prod id -38933             37812.0  38900.0                 2.5
   2   Pre-Prod id -38936             37816.0  38903.0                 3.0
   3   Pre-Prod id -38930             37815.0  38902.0                 1.5
   4   Pre-Prod id -38932             37813.0  38909.0                 1.5
   5   Pre-Prod id -38938             37818.0  38906.0                 2.0
   6   Pre-Prod id -38929             37811.0  38901.0                 1.0
x2 0                32958             32958.0  32806.0                 4.0
   1   Pre-Prod id -38836             37820.0  38904.0                28.0
   2                35435             35435.0  36277.0               288.0
   3                37161             37161.0  38064.0               288.0
   4                35161             35161.0  36021.0               288.0
   5                33744             33744.0  33645.0                16.0
   6                 6070              6070.0  16847.0                60.0
   7                32524             32524.0  32337.0               192.0
   8                35203             35203.0  35916.0               192.0
   9                 6266              6266.0   1936.0                 6.0
   10               33156             33156.0  33004.0               192.0
   11               33738             33738.0  33647.0                67.0
   12  Pre-Prod id -38835             37814.0  38907.0               192.0
   13                6041              6041.0  16781.0                12.0
   14               32420             32420.0  32233.0               192.0
   15               35305             35305.0  36124.0               192.0
   16               33445             33445.0  33300.0               192.0
   17               33632             33632.0  33541.0               192.0
   18               37165             37165.0  38066.0                 1.0
   19               35377             35377.0  36223.0               192.0
   20               33362             33362.0  33217.0               420.0
x3 0   Pre-Prod id -38305             37819.0  38908.0                12.0

      duration_medium__c           CPP     Price  \
x1 0               Hours  Keka Academy       1.0
   1               Hours  Keka Academy       1.0
   2               Hours  Keka Academy       1.0
   3               Hours  Keka Academy       1.0
   4               Hours  Keka Academy       1.0
   5               Hours  Keka Academy       1.0
   6               Hours  Keka Academy       1.0
x2 0               Years  Henry Harvin  349500.0
   1               Hours  Henry Harvin   22500.0
   2               Hours  Henry Harvin  100000.0
   3               Hours  Henry Harvin       1.0
   4               Hours  Henry Harvin  798000.0
   5               Hours  Henry Harvin  236000.0
   6               Hours  Henry Harvin   44500.0
   7               Hours  Henry Harvin   12500.0
   8               Hours  Henry Harvin   15000.0
   9              Months  Henry Harvin  103550.0
   10              Hours  Henry Harvin   89500.0
   11              Hours  Henry Harvin   59500.0
   12              Hours  Henry Harvin    5000.0
   13              Hours  Henry Harvin   10000.0
   14              Hours  Henry Harvin   34500.0
   15              Hours  Henry Harvin   44500.0
   16              Hours  Henry Harvin   59500.0
   17              Hours  Henry Harvin   15000.0
   18              Years  Henry Harvin       1.0
   19              Hours  Henry Harvin   89000.0
   20              Hours  Henry Harvin  249000.0
x3 0               Hours       Eduonix    9086.0

                                              Concept id  \
x1 0   14078, 14079, 14080, 14474, 14479, 15299, 1521...
   1   15213, 13674, 13677, 13680, 13681, 15309, 1531...
   2   14629, 14606, 15244, 14630, 14631, 14632, 1463...
   3   14086, 14087, 14091, 14334, 14342, 14598, 1531...
   4   15308, 14111, 15243, 15232, 14104, 14106, 1410...
   5                                 14171, 15165, 15308
   6                                        14482, 14483
x2 0   13718, 13968, 13973, 14106, 14428, 14613, 1532...
   1   15162, 15201, 15206, 15179, 15180, 15317, 1517...
   2   15281, 15285, 15309, 15310, 15311, 15313, 1531...
   3   15166, 15204, 15281, 15309, 15311, 15312, 1531...
   4   15184, 15284, 15287, 15299, 15300, 15301, 1530...
   5   15160, 15161, 15159, 15162, 15165, 15167, 1516...
   6   15162, 15183, 15188, 15312, 15318, 15169, 1517...
   7   15164, 15166, 15281, 15285, 15321, 15328, 1524...
   8   14638, 14638, 14638, 13716, 13973, 14088, 1410...
   9   15189, 15197, 15319, 15320, 15327, 15239, 1524...
   10  13717, 13723, 14075, 14078, 14079, 14082, 1408...
   11  15201, 15311, 15316, 15209, 15216, 15259, 1526...
   12  15200, 15177, 15210, 15211, 15216, 15159, 1516...
   13    15179, 15180, 15177, 15196, 15185, 15195, 15198
   14    15322, 15243, 14149, 13868, 14146, 14152, 15242
   15                  14614, 13932, 15326, 15236, 15238
   16                                15199, 15204, 15212
   17                                15234, 15199, 15208
   18                                13615, 13618, 13621
   19                                       15173, 15212
   20                                              13623
x3 0   15241, 15247, 15233, 15238, 14604, 15242, 1523...

       corporate_function_id  Duration_in_seconds  Is_within_a_week  \
x1 0                   660.0              12600.0              True
   1                   660.0               9000.0              True
   2                   660.0              10800.0              True
   3                   660.0               5400.0              True
   4                   660.0               5400.0              True
   5                   660.0               7200.0              True
   6                   660.0               3600.0              True
x2 0                   660.0          126144000.0             False
   1                   660.0             100800.0              True
   2                   660.0            1036800.0             False
   3                   660.0            1036800.0             False
   4                   660.0            1036800.0             False
   5                   660.0              57600.0              True
   6                   660.0             216000.0              True
   7                   660.0             691200.0             False
   8                   660.0             691200.0             False
   9                   660.0           15780096.0             False
   10                  660.0             691200.0             False
   11                  660.0             241200.0              True
   12                  660.0             691200.0             False
   13                  660.0              43200.0              True
   14                  660.0             691200.0             False
   15                  660.0             691200.0             False
   16                  660.0             691200.0             False
   17                  660.0             691200.0             False
   18                  660.0           31536000.0             False
   19                  660.0             691200.0             False
   20                  660.0            1512000.0             False
x3 0                   660.0              43200.0              True

       concept_count  integration_keka    Rank integration_HH  \
x1 0              21              True  150.00            NaN
   1              17              True  149.99            NaN
   2              17              True  149.98            NaN
   3              16              True  149.97            NaN
   4              10              True  149.96            NaN
   5               3              True  149.95            NaN
   6               2              True  149.94            NaN
x2 0              81             False  100.00           True
   1              51             False   99.99           True
   2              30             False   99.98           True
   3              28             False   99.97           True
   4              27             False   99.96           True
   5              25             False   99.95           True
   6              22             False   99.94           True
   7              22             False   99.93           True
   8              19             False   99.92           True
   9              13             False   99.91           True
   10             12             False   99.90           True
   11             11             False   99.89           True
   12              9             False   99.88           True
   13              7             False   99.87           True
   14              7             False   99.86           True
   15              5             False   99.85           True
   16              3             False   99.84           True
   17              3             False   99.83           True
   18              3             False   99.82           True
   19              2             False   99.81           True
   20              1             False   99.80           True
x3 0               9             False   50.00          False

      integration_Eduonix
x1 0                  NaN
   1                  NaN
   2                  NaN
   3                  NaN
   4                  NaN
   5                  NaN
   6                  NaN
x2 0                  NaN
   1                  NaN
   2                  NaN
   3                  NaN
   4                  NaN
   5                  NaN
   6                  NaN
   7                  NaN
   8                  NaN
   9                  NaN
   10                 NaN
   11                 NaN
   12                 NaN
   13                 NaN
   14                 NaN
   15                 NaN
   16                 NaN
   17                 NaN
   18                 NaN
   19                 NaN
   20                 NaN
x3 0                 True

In [60]:
result.to_excel("/Users/romitbenkar/Downloads/Recorating_Kotak_HR.xlsx")

In [8]:
import pandas as pd
import json

# Read your file
df = pd.read_excel(r"C:\Users\taslim.siddiqui\Downloads\Recorating_Kotak_HR04.xlsx")

# Rename Rank → rating
df = df.rename(columns={"Rank": "rating"})

# Convert each row into JSON string format
json_data = [json.dumps([{
    "corporate_function_id": int(row["corporate_function_id"]),
    "rating": float(row["rating"])
}]) for _, row in df.iterrows()]

# Print each row as separate JSON line
for item in json_data:
    print(item)

# Create a DataFrame to save
out_df = pd.DataFrame({"final_rating": json_data})

# Save to Excel
out_df.to_excel(r"C:\Users\taslim.siddiqui\Downloads\Recorating_output.xlsx", index=False)

[{"corporate_function_id": 660, "rating": 150.0}]
[{"corporate_function_id": 660, "rating": 149.99}]
[{"corporate_function_id": 660, "rating": 149.98}]
[{"corporate_function_id": 660, "rating": 149.97}]
[{"corporate_function_id": 660, "rating": 149.96}]
[{"corporate_function_id": 660, "rating": 149.95}]
[{"corporate_function_id": 660, "rating": 149.94}]
[{"corporate_function_id": 660, "rating": 100.0}]
[{"corporate_function_id": 660, "rating": 99.99}]
[{"corporate_function_id": 660, "rating": 99.98}]
[{"corporate_function_id": 660, "rating": 99.97}]
[{"corporate_function_id": 660, "rating": 99.96}]
[{"corporate_function_id": 660, "rating": 99.95}]
[{"corporate_function_id": 660, "rating": 99.94}]
[{"corporate_function_id": 660, "rating": 99.93}]
[{"corporate_function_id": 660, "rating": 99.92}]
[{"corporate_function_id": 660, "rating": 99.91}]
[{"corporate_function_id": 660, "rating": 99.9}]
[{"corporate_function_id": 660, "rating": 99.89}]
[{"corporate_function_id": 660, "rating": 99.88}]
[{"corporate_function_id": 660, "rating": 99.87}]
[{"corporate_function_id": 660, "rating": 99.86}]
[{"corporate_function_id": 660, "rating": 99.85}]
[{"corporate_function_id": 660, "rating": 99.84}]
[{"corporate_function_id": 660, "rating": 99.83}]
[{"corporate_function_id": 660, "rating": 99.82}]
[{"corporate_function_id": 660, "rating": 99.81}]
[{"corporate_function_id": 660, "rating": 99.8}]
[{"corporate_function_id": 660, "rating": 99.79}]
[{"corporate_function_id": 660, "rating": 50.0}]