In [1]:
import pandas as pd
import numpy as np

In [2]:
df1=pd.read_excel(r"C:\Users\taslim.siddiqui\Downloads\Collate_file_concept.xlsx")
df1

,Course Sylabus,Concept
0,Introduction to the Course<br>Module 1: What's...,Benchmarking Source Identification
1,Introduction to the Course<br>Module 1: What's...,Pay Band Design Framework
2,Introduction to the Course<br>Module 1: What's...,Incentive Scheme Design Matrix
3,Module 1: Overview of Payroll Management<br>-P...,Form 16 & Tax Statement Generation
4,Module 1: Overview of Payroll Management<br>-P...,LWF State-wise Deduction Mapping
...,...,...
157440,Design a marketing funnel and assign relevant ...,NaN
157441,Design a marketing funnel and assign relevant ...,Experimentation and Reproducibility
157442,Module 1: Windows Command Line<br>Module 17 ho...,Operating System Fundamentals
157443,Getting Started with C Programming<br>- Brief ...,Variables & Data Types
157444,Getting Started with C Programming<br>- Brief ...,Control Structures

In [3]:
df1["Course Sylabus"].isnull()

0         False
1         False
2         False
3         False
4         False
          ...
157440    False
157441    False
157442    False
157443    False
157444    False
Name: Course Sylabus, Length: 157445, dtype: bool

In [4]:
df1["Course Sylabus"] = df1["Course Sylabus"].replace(["", "NA", "NaN", 0], np.nan)

In [5]:
df1 = df1.dropna(subset=["Course Sylabus"])
df1

,Course Sylabus,Concept
0,Introduction to the Course<br>Module 1: What's...,Benchmarking Source Identification
1,Introduction to the Course<br>Module 1: What's...,Pay Band Design Framework
2,Introduction to the Course<br>Module 1: What's...,Incentive Scheme Design Matrix
3,Module 1: Overview of Payroll Management<br>-P...,Form 16 & Tax Statement Generation
4,Module 1: Overview of Payroll Management<br>-P...,LWF State-wise Deduction Mapping
...,...,...
157440,Design a marketing funnel and assign relevant ...,NaN
157441,Design a marketing funnel and assign relevant ...,Experimentation and Reproducibility
157442,Module 1: Windows Command Line<br>Module 17 ho...,Operating System Fundamentals
157443,Getting Started with C Programming<br>- Brief ...,Variables & Data Types
157444,Getting Started with C Programming<br>- Brief ...,Control Structures

In [6]:
df1["Concept"] = df1["Concept"].replace(["", "NA", 0], np.nan)
df1

C:\Users\taslim.siddiqui\AppData\Local\Temp\ipykernel_12704\1516969309.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1["Concept"] = df1["Concept"].replace(["", "NA", 0], np.nan)

,Course Sylabus,Concept
0,Introduction to the Course<br>Module 1: What's...,Benchmarking Source Identification
1,Introduction to the Course<br>Module 1: What's...,Pay Band Design Framework
2,Introduction to the Course<br>Module 1: What's...,Incentive Scheme Design Matrix
3,Module 1: Overview of Payroll Management<br>-P...,Form 16 & Tax Statement Generation
4,Module 1: Overview of Payroll Management<br>-P...,LWF State-wise Deduction Mapping
...,...,...
157440,Design a marketing funnel and assign relevant ...,NaN
157441,Design a marketing funnel and assign relevant ...,Experimentation and Reproducibility
157442,Module 1: Windows Command Line<br>Module 17 ho...,Operating System Fundamentals
157443,Getting Started with C Programming<br>- Brief ...,Variables & Data Types
157444,Getting Started with C Programming<br>- Brief ...,Control Structures

In [7]:
df1 = df1.dropna(subset=["Concept"])
df1

,Course Sylabus,Concept
0,Introduction to the Course<br>Module 1: What's...,Benchmarking Source Identification
1,Introduction to the Course<br>Module 1: What's...,Pay Band Design Framework
2,Introduction to the Course<br>Module 1: What's...,Incentive Scheme Design Matrix
3,Module 1: Overview of Payroll Management<br>-P...,Form 16 & Tax Statement Generation
4,Module 1: Overview of Payroll Management<br>-P...,LWF State-wise Deduction Mapping
...,...,...
157439,Design a marketing funnel and assign relevant ...,Thought Leadership
157441,Design a marketing funnel and assign relevant ...,Experimentation and Reproducibility
157442,Module 1: Windows Command Line<br>Module 17 ho...,Operating System Fundamentals
157443,Getting Started with C Programming<br>- Brief ...,Variables & Data Types
157444,Getting Started with C Programming<br>- Brief ...,Control Structures

In [8]:
df1["Course Sylabus"] = df1["Course Sylabus"].str.replace(r"<br\s*/?>", "", regex=True)
df1

C:\Users\taslim.siddiqui\AppData\Local\Temp\ipykernel_12704\2900306188.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1["Course Sylabus"] = df1["Course Sylabus"].str.replace(r"<br\s*/?>", "", regex=True)

,Course Sylabus,Concept
0,Introduction to the CourseModule 1: What's a W...,Benchmarking Source Identification
1,Introduction to the CourseModule 1: What's a W...,Pay Band Design Framework
2,Introduction to the CourseModule 1: What's a W...,Incentive Scheme Design Matrix
3,Module 1: Overview of Payroll Management-Payro...,Form 16 & Tax Statement Generation
4,Module 1: Overview of Payroll Management-Payro...,LWF State-wise Deduction Mapping
...,...,...
157439,Design a marketing funnel and assign relevant ...,Thought Leadership
157441,Design a marketing funnel and assign relevant ...,Experimentation and Reproducibility
157442,Module 1: Windows Command LineModule 17 hours ...,Operating System Fundamentals
157443,Getting Started with C Programming- Brief Intr...,Variables & Data Types
157444,Getting Started with C Programming- Brief Intr...,Control Structures

In [9]:
df1=df1[['Course Sylabus' , 'Concept']]
df1

,Course Sylabus,Concept
0,Introduction to the CourseModule 1: What's a W...,Benchmarking Source Identification
1,Introduction to the CourseModule 1: What's a W...,Pay Band Design Framework
2,Introduction to the CourseModule 1: What's a W...,Incentive Scheme Design Matrix
3,Module 1: Overview of Payroll Management-Payro...,Form 16 & Tax Statement Generation
4,Module 1: Overview of Payroll Management-Payro...,LWF State-wise Deduction Mapping
...,...,...
157439,Design a marketing funnel and assign relevant ...,Thought Leadership
157441,Design a marketing funnel and assign relevant ...,Experimentation and Reproducibility
157442,Module 1: Windows Command LineModule 17 hours ...,Operating System Fundamentals
157443,Getting Started with C Programming- Brief Intr...,Variables & Data Types
157444,Getting Started with C Programming- Brief Intr...,Control Structures

In [10]:
unique_course_syllabus = df1[["Course Sylabus"]].drop_duplicates()
unique_course_syllabus

                                           Course Sylabus
0       Introduction to the CourseModule 1: What's a W...
3       Module 1: Overview of Payroll Management-Payro...
7       Course ContentIntroductionFord's Model T - The...
10      Module 1: HR Value Added-In this module candid...
16      Module 1: Introduction to AI in HR-Overview of...
...                                                   ...
156537  Module 1: Introduction to Non-Disclosure Agree...
156876  Developers to learn how to code securlySecurit...
157139  Module 1 Crisis Management vs BCP  Whats the D...
157372  In Clustering or Segmentation we reduce the nu...
157384  Module 1: Thesis management   - Research   - R...

[10164 rows x 1 columns]

In [11]:
# Extract relevant columns
df3 = unique_course_syllabus["Course Sylabus"]
df4 = df1[["Concept", "Course Sylabus"]]

In [12]:
# Merge df3 with df4 based on 'Unique_id'
merged_df = pd.merge(df3, df4, on="Course Sylabus", how="left")

In [13]:
# Group by 'Unique_id' and aggregate 'Skill_conc' values into a list
grouped_df = merged_df.groupby("Course Sylabus")["Concept"].apply(list).reset_index()
grouped_df

,Course Sylabus,Concept
0,\tIlluminate how to work with variablesConfer ...,[Deployment and App Store Optimization]
1,- A comprehensive overview of all topics outl...,"[Forensic Analysis, Financial Performance Anal..."
2,- An Introduction To RMODULE 1: ESSENTIAL TO ...,"[Statistical Analysis, Statistical Analysis, Q..."
3,- Android Development & KotlinMODULE 1: ANDRO...,"[Platform-Specific Development, Platform-Speci..."
4,- AngularMODULE-1 INTRODUCTION TO TYPESCRIPTW...,"[NoSQL and Non-Relational Databases, NoSQL and..."
...,...,...
10159,Ã¯Â»Â¿MODULE 01 Introduction to Penetration Te...,"[Penetration Testing, Penetration Testing]"
10160,Ã¯Â»Â¿Module 01 - Introduction to IT and Cyber...,"[Network Design, Network Security, Network Sec..."
10161,Ã¯Â»Â¿Module 01 - Introduction to bug hunting....,"[Penetration Testing, Threat Analysis, Penetra..."
10162,Ã¯Â»Â¿Module 1: Retail Banking -Indian Financi...,"[Foreign Exchange Management, Cash Management,..."
10163,Ã¯Â»Â¿Programing Fundamentals-Introduction to ...,"[HTML, CSS, JavaScript, Customising Bootstrap ..."

In [14]:
# Convert the list of skill_conc to a string for each Unique_id
# grouped_df['id'] = grouped_df['id'].apply(lambda x: ', '.join(map(str, x)))
grouped_df['Concept'] = grouped_df['Concept'].apply(lambda x: str(x))
grouped_df['Concept'].astype(str)
grouped_df

,Course Sylabus,Concept
0,\tIlluminate how to work with variablesConfer ...,['Deployment and App Store Optimization']
1,- A comprehensive overview of all topics outl...,"['Forensic Analysis', 'Financial Performance A..."
2,- An Introduction To RMODULE 1: ESSENTIAL TO ...,"['Statistical Analysis', 'Statistical Analysis..."
3,- Android Development & KotlinMODULE 1: ANDRO...,"['Platform-Specific Development', 'Platform-Sp..."
4,- AngularMODULE-1 INTRODUCTION TO TYPESCRIPTW...,"['NoSQL and Non-Relational Databases', 'NoSQL ..."
...,...,...
10159,Ã¯Â»Â¿MODULE 01 Introduction to Penetration Te...,"['Penetration Testing', 'Penetration Testing']"
10160,Ã¯Â»Â¿Module 01 - Introduction to IT and Cyber...,"['Network Design', 'Network Security', 'Networ..."
10161,Ã¯Â»Â¿Module 01 - Introduction to bug hunting....,"['Penetration Testing', 'Threat Analysis', 'Pe..."
10162,Ã¯Â»Â¿Module 1: Retail Banking -Indian Financi...,"['Foreign Exchange Management', 'Cash Manageme..."
10163,Ã¯Â»Â¿Programing Fundamentals-Introduction to ...,"['HTML', 'CSS', 'JavaScript', 'Customising Boo..."

In [15]:
grouped_df['Concept'] = grouped_df['Concept'].str.translate(str.maketrans({"[": "", "]": ""}))

In [16]:
grouped_df['Concept'] = grouped_df['Concept'].str.replace(".0", "", regex=False)
grouped_df

,Course Sylabus,Concept
0,\tIlluminate how to work with variablesConfer ...,'Deployment and App Store Optimization'
1,- A comprehensive overview of all topics outl...,"'Forensic Analysis', 'Financial Performance An..."
2,- An Introduction To RMODULE 1: ESSENTIAL TO ...,"'Statistical Analysis', 'Statistical Analysis'..."
3,- Android Development & KotlinMODULE 1: ANDRO...,"'Platform-Specific Development', 'Platform-Spe..."
4,- AngularMODULE-1 INTRODUCTION TO TYPESCRIPTW...,"'NoSQL and Non-Relational Databases', 'NoSQL a..."
...,...,...
10159,Ã¯Â»Â¿MODULE 01 Introduction to Penetration Te...,"'Penetration Testing', 'Penetration Testing'"
10160,Ã¯Â»Â¿Module 01 - Introduction to IT and Cyber...,"'Network Design', 'Network Security', 'Network..."
10161,Ã¯Â»Â¿Module 01 - Introduction to bug hunting....,"'Penetration Testing', 'Threat Analysis', 'Pen..."
10162,Ã¯Â»Â¿Module 1: Retail Banking -Indian Financi...,"'Foreign Exchange Management', 'Cash Managemen..."
10163,Ã¯Â»Â¿Programing Fundamentals-Introduction to ...,"'HTML', 'CSS', 'JavaScript', 'Customising Boot..."

In [17]:
def remove_duplicates_from_string(cell_value):
    # Split the string by commas and strip any spaces
    values = cell_value.split(", ")
    
    # Remove duplicates by converting to a set and back to a list
    unique_values = list(set(values))
    
    # Join the unique values back into a string, separating by commas
    return ", ".join(unique_values)

# Example usage:
grouped_df['Concept'].apply(remove_duplicates_from_string)
grouped_df

,Course Sylabus,Concept
0,\tIlluminate how to work with variablesConfer ...,'Deployment and App Store Optimization'
1,- A comprehensive overview of all topics outl...,"'Forensic Analysis', 'Financial Performance An..."
2,- An Introduction To RMODULE 1: ESSENTIAL TO ...,"'Statistical Analysis', 'Statistical Analysis'..."
3,- Android Development & KotlinMODULE 1: ANDRO...,"'Platform-Specific Development', 'Platform-Spe..."
4,- AngularMODULE-1 INTRODUCTION TO TYPESCRIPTW...,"'NoSQL and Non-Relational Databases', 'NoSQL a..."
...,...,...
10159,Ã¯Â»Â¿MODULE 01 Introduction to Penetration Te...,"'Penetration Testing', 'Penetration Testing'"
10160,Ã¯Â»Â¿Module 01 - Introduction to IT and Cyber...,"'Network Design', 'Network Security', 'Network..."
10161,Ã¯Â»Â¿Module 01 - Introduction to bug hunting....,"'Penetration Testing', 'Threat Analysis', 'Pen..."
10162,Ã¯Â»Â¿Module 1: Retail Banking -Indian Financi...,"'Foreign Exchange Management', 'Cash Managemen..."
10163,Ã¯Â»Â¿Programing Fundamentals-Introduction to ...,"'HTML', 'CSS', 'JavaScript', 'Customising Boot..."

In [18]:
grouped_df["Course Sylabus"] = (
    grouped_df["Course Sylabus"]
    .astype(str)
    .str.encode("ascii", "ignore")
    .str.decode("ascii")
)

In [19]:
def remove_duplicates_in_cell(x):
    # 1. Handle missing values
    if x is None or (isinstance(x, float) and pd.isna(x)):
        return x
    
    # 2. If value is already a list or array
    if isinstance(x, (list, tuple)):
        items = [str(i).strip() for i in x]
    else:
        # 3. Otherwise treat it as a string
        items = [i.strip() for i in str(x).split(',')]
    
    # 4. Remove duplicates while keeping order
    unique_items = list(dict.fromkeys(items))
    
    # 5. Join back into a clean string
    return ", ".join(unique_items)

# Apply safely
grouped_df['Concept'] = grouped_df['Concept'].apply(remove_duplicates_in_cell)

In [20]:
grouped_df=grouped_df.to_excel(r"C:\Users\taslim.siddiqui\Downloads\TEXTJOIN_output_concept.xlsx")
grouped_df